"""Modul 1: Die Bergfreiheiten, 1521–1554. Schreibt data/freiheit.json.

Quelle, am Seitenbild gelesen: H. Calvör, Historische Nachricht von der Unter- und
gesamten Ober-Harzischen Bergwerke (Braunschweig 1765), III.–V. Anhang, S. 215–222
(Internet Archive 10705761bsb; S. 215 = Blatt n234, Blatt = S.+19).
"""
import json
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "data" / "freiheit.json"

HOHNSTEIN = [
    dict(n=1, titel="Holz aus allen Wäldern, ‚nun und zu ewigen Zeiten‘", pg="Calvör 1765, S. 215", lang="fnhd",
         orig="Gräfliche Hohnsteinische Berg-Freyheit in der Herrschafft Hohnstein und Lauterberg, vom Jahr 1521. welche noch niemahls gedrucket ist.\n\nWir Heinrich und Ernst Gebrüdere Grafen von Hohnstein, Herren zu Lohra und Klettenberg, bekennen vor uns, und die Wohlgebohrnen unsere freundliche lieben Gebrüdere Erben und Erbnehmen, und thun öffentlich gegen männiglich wissen; Nachdem sich durch Gnade GOttes Bergwerck auf Silber und anderer Metall in unserer Herrschafft Hohnstein und Lauterberg eräuget, welche Bergwercke wir mit aller Befreyung, wie Bergwercks-Recht und Gewohnheit ist, und wie jedes freyes Bergwerck haben soll, begnadet und begabet haben, wollen auch diese hernach beschriebene Freyheiten hiemit zugesaget und gegeben haben. Allen und jeden Gewercken, so sich an allen Orten, wo es einem jeden gefällig, einlegen, Bergwerck suchen und bauen und sich des gebrauchen werden, daß sie sich auf unsern Wäldern zu aller ihrer Nohtdurfft Schacht-Holtz, Bau-Holtz, zu bauen Schächte, Hütten, Mühlen, Puchwercke, Röste-Holtz, nun und zu ewigen Zeiten, auch Bren-Holtz, Treib-Holtz, Wohn-Häuser, dieweil diese Bergwercke beständig und ganghaftig, auch Kohl-Holtz auf zehen Jahr lang nach dato frey ohne allen Forst-Zinß zu hohlen und gebrauchen mögen, in allen unsern Gehöltzen, wo ihnen das bequemlich, als sie das zugenanter und anderer Nohtdurfft bedürffen werden, doch nichts davon zu verkauffen.",
         en="Gräfliche Hohnsteinische Bergfreiheit in der Herrschaft Hohnstein und Lauterberg, vom Jahr 1521, die noch niemals gedruckt worden ist.\n\nWir, Heinrich und Ernst, Gebrüder, Grafen von Hohnstein, Herren zu Lohra und Klettenberg, bekennen für uns und unsere wohlgeborenen, freundlich lieben Brüder, Erben und Erbnehmer und tun öffentlich jedermann kund: Nachdem sich durch Gottes Gnade Bergwerk auf Silber und anderes Metall in unserer Herrschaft Hohnstein und Lauterberg gezeigt hat, haben wir diese Bergwerke mit aller Befreiung begnadet und begabt, wie es Bergwerksrecht und Gewohnheit ist und wie jedes freie Bergwerk sie haben soll, und wollen auch die hier beschriebenen Freiheiten hiermit zugesagt und gegeben haben. Allen und jeden Gewerken, die sich an allen Orten, wo es einem jeden gefällt, einlegen, Bergwerk suchen und bauen und es nutzen werden, gestatten wir, aus unseren Wäldern zu all ihrem Bedarf Schachtholz und Bauholz zum Bau von Schächten, Hütten, Mühlen und Pochwerken und Röstholz zu holen, jetzt und zu ewigen Zeiten, dazu Brennholz, Treibholz und Holz für Wohnhäuser, solange diese Bergwerke beständig und ganghaftig sind, und Kohlholz zehn Jahre lang von heute an, frei ohne jeden Forstzins, in allen unseren Gehölzen, wo es ihnen bequem ist, soweit sie es zu diesem und anderem Bedarf brauchen werden; doch nichts davon zu verkaufen.",
         note="Die Bergfreiheit der Grafen von Hohnstein für ihre Herrschaft Lauterberg, in der St. Andreasberg lag; Calvör druckte sie nach seiner Angabe zum ersten Mal. Datiert ist sie ‚Sontags nach Viti‘ 1521 ([5]); der Veitstag (15. Juni) war 1521 ein Samstag, gemeint ist also Sonntag, der 16. Juni 1521. Gewerken sind die Anteilseigner einer Grube, die ihre Kosten tragen und an ihrem Ertrag teilhaben. Röstholz braucht man, um das Erz vor dem Schmelzen zu rösten; Treibholz für das Treiben, das Abscheiden des Silbers aus dem Blei; Kohlholz für die Holzkohle der Hütten. ‚Ganghaftig‘: solange die Erzgänge anhalten. Das erste, was die Freiheit verspricht, ist Holz, und das Holz ist auf Dauer frei, nur die Holzkohle auf zehn Jahre."),
    dict(n=2, titel="Schenken, handeln, keine Schuldklage", pg="Calvör 1765, S. 215", lang="fnhd",
         orig="Sie sollen auch Macht haben Schenckstetten zu wehlen und legen Schenck-Häuser, Brau-Häuser und Wohn-Häuser, Scheuern und Ställe nach ihrer Nohtdurfft zu bauen, und aufzurichten, allerley Bier und Wein, wo sie das zu bekommen wissen, nach ihren Gefallen zu kauffen, zu sich bringen, und ohne alles Ungeld frey schencken und forttreiben mögen; Desgleichen auch alle andere Gewerbe und Handthierung nichts ausgeschlossen, was einem jeden zu Erhaltung seiner Nahrung, und für gemeinem Nutz dienende zu gebrauchen weiß, soll einem jeden ohne alle Beschwerung frey vergönt und zugelassen seyn, auch alles, das dem Bergwerck zu Nohtdurfft und Gute zugeführet, zugetrieben oder getragen wird, solches, so weit sich unsere Herrschafft erstrecket, soll alles Wege-Gelds, Zolls und Geleits zu ewigen Zeiten gefreyet seyn; Es sollen auch alle, die sich wesentlich dahin wenden, und niederlassen, oder sonsten die Bergwercke bauen werden, um Schuld, die daselbst nicht gemacht, mit keiner Gerichts-Hülffe zur Bezahlung gezwungen, geängstet, auch nicht aufgehalten oder gehemmet werden; [...] auch sollen dieselbigen, so dem Bergwercke zu gute Nohtdurfft zuführen, treiben und tragen werden, für aller Gewalt geschützet werden.",
         en="Sie sollen auch die Macht haben, Schankstätten zu wählen und Schankhäuser, Brauhäuser und Wohnhäuser, Scheunen und Ställe nach ihrem Bedarf zu bauen und zu errichten, allerlei Bier und Wein, wo sie es zu bekommen wissen, nach ihrem Gefallen zu kaufen, herbeizubringen und ohne jedes Ungeld frei auszuschenken und zu verkaufen. Ebenso soll jedem alles andere Gewerbe und jede Hantierung, nichts ausgeschlossen, was einer zum Erhalt seines Lebensunterhalts und zum gemeinen Nutzen zu gebrauchen weiß, ohne jede Belastung frei vergönnt und zugelassen sein; und alles, was dem Bergwerk zu Bedarf und Nutzen zugeführt, zugetrieben oder getragen wird, soll, so weit sich unsere Herrschaft erstreckt, zu ewigen Zeiten von allem Wegegeld, Zoll und Geleit befreit sein. Auch sollen alle, die sich mit ihrem Wohnsitz dahin wenden und niederlassen oder sonst die Bergwerke bauen werden, wegen Schulden, die sie nicht dort gemacht haben, durch keine Gerichtshilfe zur Bezahlung gezwungen, bedrängt, aufgehalten oder behindert werden; [...] und die, die dem Bergwerk zu seinem Nutzen das Nötige zuführen, treiben und tragen werden, sollen vor aller Gewalt geschützt werden.",
         note="Ungeld ist die Verbrauchssteuer auf Bier und Wein, Geleit die Gebühr für den Schutz auf der Straße. Die Klausel über die Schulden ist die auffälligste: Wer anderswo Schulden hatte, konnte im neuen Bergwerk nicht dafür belangt werden. Die Bergfreiheiten lockten also auch Leute, die anderswo nicht mehr bleiben konnten. Ausgelassen ist eine Wiederholung über den freien Zugang zu den Bergwerken."),
    dict(n=3, titel="Drei Jahre den fünfzehnten statt den zehnten Teil", pg="Calvör 1765, S. 215–216", lang="fnhd",
         orig="Und ob GOtt der Allmächtige (wie zu hoffen) durch seine milde Göttliche Gnade das Bergwerck fündig machen, daß man Ertz treffen und erbauen würde, so wollen wir gutwillig nachlassen und bewilligen, daß sie uns von gemachten Silber drey Jahr lang nicht mehr, denn die funffzehnte Marck Silbers in unsere Zehnt-Cammer, die wir dazu verordnen wollen, zum Zehnten reichen und geben sollen, da entgegen wollen wir ihnen den fünffzehnten Pfennig Hüttensteur wieder statten und inne lassen [...] und alles Silbers, Kupffer, Zinn, Bley, oder ander Metall, so sie machen, sollen, und mögen sie Macht und Gewalt haben, so sie uns, wie oben berühret, unsern gebührenden Theil die funffzehnte Marck zum Zehnten entrichten und geben, zu verführen und zuvertreiben, wo sie wollen nach eines jeden Gutdüncken und Gefallen von uns und männiglichen unverhindert fünff Jahr lang, und nach Ausgang der fünff Jahre soll alles Geld und Silber in unsern Zehnten geantwortet werden, und die Marck von uns, wie im Fürstenthum Sachsen geschiehet, so hoch bezahlet werden [...] es soll auch nach Uberantwortung des Geldes oder Silbers die Bezahlung mit angezeigter Müntz denen Gewercken, oder ihren Factoren binnen 14 Tagen nach Ueberantwortung bezahlet werden, und wo den Gewercken in bemeldten vierzehn Tagen Verlegung von Nöhten, soll ihnen auch zur Nohtdurfft aus unsern Zehnten gereichet werden.",
         en="Und sollte Gott der Allmächtige, wie zu hoffen ist, durch seine milde göttliche Gnade das Bergwerk fündig machen, so dass man Erz treffen und abbauen würde, so wollen wir gutwillig nachlassen und bewilligen, dass sie uns von dem gemachten Silber drei Jahre lang nicht mehr als die fünfzehnte Mark Silber als Zehnten in unsere Zehntkammer, die wir dazu einrichten wollen, reichen und geben sollen; dagegen wollen wir ihnen den fünfzehnten Pfennig Hüttensteuer erstatten und lassen [...] Und alles Silber, Kupfer, Zinn, Blei oder andere Metall, das sie machen, sollen und dürfen sie, wenn sie uns, wie oben gesagt, unseren gebührenden Teil, die fünfzehnte Mark, als Zehnten entrichtet haben, fünf Jahre lang ausführen und verkaufen, wohin sie wollen, nach eines jeden Gutdünken und Gefallen, von uns und jedermann ungehindert; und nach Ablauf der fünf Jahre soll alles Geld und Silber in unseren Zehnten abgeliefert und die Mark von uns so hoch bezahlt werden, wie es im Fürstentum Sachsen geschieht [...] Auch soll nach der Ablieferung des Geldes oder Silbers die Bezahlung in der genannten Münze den Gewerken oder ihren Faktoren binnen 14 Tagen nach der Ablieferung geleistet werden; und brauchen die Gewerken in diesen vierzehn Tagen Vorschuss, so soll ihnen auch der aus unserem Zehnten gereicht werden.",
         note="Der Zehnt war der Anteil des Landesherrn am Ertrag. Die Grafen verlangen drei Jahre lang statt jeder zehnten nur jede fünfzehnte Mark Silber. Die Mark ist hier ein Gewicht, kein Geld. Nach fünf Jahren soll alles Silber an den Landesherrn abgeliefert und von ihm bezahlt werden: Das Silber gehörte dann nicht mehr den Gewerken zum freien Verkauf, sondern dem Landesherrn zum festen Preis. Ausgelassen sind die Bestimmungen über Kupfer, Zinn und Blei und über Münze und Gewicht."),
    dict(n=4, titel="Eine freie Bergstadt: Rat, Markt, Äcker", pg="Calvör 1765, S. 216", lang="fnhd",
         orig="So auch GOtt Gnade würde geben, daß sich Bergleute in unserer Herrschafft seßhaftig würden niederlassen und bauen, es sey zu Lauterberg oder an einem gelegenen Ort des Bergwerckes, so wollen wir ihnen zu Aufnehmung, Mehrung und Erhaltung gemeines Nutzens und Friedes alle Erb- und Bürgerliche Gerichte aus Gnaden zugestellet haben, und daß sie unter sich Burgemeister, Richter und Rath zu erwehlen Macht haben, doch daß sie von uns confirmiret und bestätiget werden. [...]\n\nWir ordnen auch hiemit und lassen zu, alle Sonnabend einen freyen Wochen-Marckt, auch sonsten alle Tage, ausgeschlossen den heiligen Sontag, und sonsten alle hohe Fest-Tage und Feyer-Tage daselbst zum Lauterberg oder wo eine freye Berg-Stadt in unser Herrschafft erbauet würde, zu halten, daß alle diejenigen, so dahin Küchen-Speise, Brodt, Butter, Käse, Fleisch, Rinder, Schweine, Schöpse und alle andere Nohtdurfft, dem Bergwercke zuführen, treiben, tragen und bringen, nichts ausgeschlossen, soll auch alles Geleites, Zolles, Stadt-Geldes zu geben befreyet seyn; so auch die Einwohner daselbst zum Lauterberg oder in einer andern freyen Berg-Stadt in unserer Herrschafft die sich dahin niederlassen, Acker, Wiesen, Gärten räumen, bauen und machen würden, soll ihnen jetzige bemeldete Freyheit ewig zugestellet seyn, nichts davon zu geben, auch alle Vorbothe, Frohne und Hoff-Dienste zu thun befreyet seyn [...]",
         en="Und wenn Gott die Gnade geben würde, dass sich Bergleute in unserer Herrschaft sesshaft niederlassen und bauen, sei es zu Lauterberg oder an einem günstig gelegenen Ort des Bergwerks, so wollen wir ihnen zur Aufnahme, Mehrung und Erhaltung des gemeinen Nutzens und Friedens alle Erb- und Bürgergerichte aus Gnaden übertragen haben, und sie sollen die Macht haben, unter sich Bürgermeister, Richter und Rat zu wählen, doch so, dass diese von uns bestätigt werden. [...]\n\nWir ordnen auch hiermit an und lassen zu, jeden Samstag einen freien Wochenmarkt zu halten, und auch sonst an allen Tagen außer dem heiligen Sonntag und den hohen Fest- und Feiertagen, dort in Lauterberg oder wo eine freie Bergstadt in unserer Herrschaft gebaut würde; und alle, die Küchenspeise, Brot, Butter, Käse, Fleisch, Rinder, Schweine, Hammel und allen anderen Bedarf, nichts ausgeschlossen, dem Bergwerk zuführen, treiben, tragen und bringen, sollen von allem Geleit, Zoll und Stadtgeld befreit sein. Und wenn die Einwohner dort in Lauterberg oder in einer anderen freien Bergstadt unserer Herrschaft, die sich dorthin niederlassen, Äcker, Wiesen und Gärten roden, bebauen und anlegen würden, soll ihnen diese Freiheit ewig gelten, nichts davon abzugeben, und sie sollen von allen Aufgeboten, Fronen und Hofdiensten befreit sein [...]",
         note="Eine ‚freie Bergstadt‘ ist hier keine Stadt mit eigener Herrschaft, sondern eine Siedlung, deren Bürger Rat und Richter selbst wählen, unter Bestätigung des Landesherrn, und die von Fronen und Abgaben frei ist. Der Markt war lebenswichtig: Auf dem Oberharz wuchs kaum Getreide, und alles Essen musste heraufgebracht werden. Ausgelassen ist eine Bestimmung über Brauhäuser, Fleischbänke, Badstuben und Mühlen und eine über Erbgüter, die von anderen Untertanen gekauft werden."),
    dict(n=5, titel="Hasen ja, Hirsche nein; freier Zu- und Abzug", pg="Calvör 1765, S. 216–217", lang="fnhd",
         orig="Wir wollen auch aus gnädigem Willen zu und nachgelassen haben, Hasel-Hüner und Vögel nach ihren Gefallen zu fangen Macht haben, und Haasen, so weit sich der Lauterbergische Fluer erstrecket, wie sie mögen, nachgelassen haben; Aber grob Feder-Willprät, Rehe und Haupt-Wildt zu fahen, soll sich ein jeder enthalten. Wir lassen auch nach die Speer Lutter am Steige nach dem Vogels Gesang und den Breitenbach dem Bergwerck frey zu fischen, und alle andere unsere Wasser zu vermeiden [...] Wir geben auch hiemit allen und jeden, die sich auf unsere Bergwerke häußlichen, oder sonsten niederlassen werden, einen freyen Zu- und Abzug mit allen und jeden ihren Gütern, nun und zu ewigen Zeiten. Und dieweil eine gemeine Berg-Ordnung muß begriffen und aufgerichtet werden, sollen und wollen wir die mit Rahte, Wissen und Willen Rechts und Gerichts zu bequemer Zeit nach Gelegenheit dieses Bergwercks anstellen [...] Der gegeben ist nach Christi unsers Herrn Gebuhrt im ein tausend fünff hundert und ein und zwantzigsten Jahre Sontags nach Viti.\n\nDiese Berg-Freyheit, oder Privilegia sind von Herzog Philip zu Grubenhagen der freyen Bergstadt St. Andreasberg unter diesen Worten: „so viel sie deren bis dato in geruhiglichen Besitz und Gebrauch gehabt, und hergebracht, und weiter nicht, confirmiret, im Funfzehn hundert und fünf und neunzigsten Jahre nach Christi unsers Herrn Gebuhrt den vierdten Manahts-Tag Octobris.",
         en="Wir wollen auch aus gnädigem Willen zugelassen haben, dass sie Haselhühner und Vögel nach ihrem Gefallen fangen dürfen, und Hasen, so weit sich die Lauterberger Flur erstreckt, wie sie können; aber das große Federwild, Rehe und Hochwild zu fangen, soll sich jeder enthalten. Wir lassen auch die Sperrlutter am Steig nach dem Vogelsang und den Breitenbach dem Bergwerk zum freien Fischen, und alle anderen unserer Gewässer sind zu meiden [...] Wir geben auch hiermit allen und jeden, die sich auf unseren Bergwerken häuslich oder sonst niederlassen werden, einen freien Zu- und Abzug mit allen ihren Gütern, jetzt und zu ewigen Zeiten. Und weil eine allgemeine Bergordnung verfasst und aufgerichtet werden muss, wollen wir sie mit Rat, Wissen und Willen des Rechts und Gerichts zu passender Zeit, wie es dieses Bergwerk erfordert, aufstellen [...] Gegeben nach Christi, unseres Herrn, Geburt im eintausendfünfhunderteinundzwanzigsten Jahr, am Sonntag nach Veit.\n\nDiese Bergfreiheit oder diese Privilegien hat Herzog Philipp zu Grubenhagen der freien Bergstadt St. Andreasberg mit diesen Worten bestätigt: „soweit sie sie bis heute in ruhigem Besitz und Gebrauch gehabt und hergebracht haben, und nicht weiter“, im fünfzehnhundertfünfundneunzigsten Jahr nach Christi, unseres Herrn, Geburt, am vierten Tag des Monats Oktober.",
         note="Das Hochwild blieb der Herrschaft. Die Sperrlutter und der Breitenbach sind Bäche bei St. Andreasberg; die Namen stehen im Druck so. Der freie Abzug war die Kehrseite der Anwerbung: Wer kam, durfte auch wieder gehen, mit seinem Gut. Der Schlusssatz in kleinerem Druck ist Calvörs Nachsatz: 1595, nach dem Aussterben der Grafen von Hohnstein (1593), bestätigte der neue Landesherr die Freiheit, aber nur, soweit die Stadt sie ‚bis dato in geruhiglichem Besitz‘ hatte, ‚und weiter nicht‘. Freiheiten wurden mit jedem Herrscherwechsel neu verhandelt. Ausgelassen ist ein Satz, mit dem die Grafen auf Hütten, Schlacken und Halden verzichten."),
]

HEINRICH = [
    dict(n=1, titel="Der Erbstollen nimmt den Gruben die Wassernot", pg="Calvör 1765, S. 217", lang="fnhd",
         orig="Herzog Heinrich des Jüngern zu Braunschweig und Lüneburg A. 1532. ertheilte erste Bergfreiheit, aus Häckens geschriebener Historie vom Harzischen Bergwerke im Fürstenthum Braunschweig.\n\nVon GOttes Gnaden, Wir Heinrich, Herzog zu Braunschweig, und Lüneburg bekennen und bekräfftigen für uns, dem Hochgebohrnen Fürsten, unsern freundlichen lieben Bruder, Herrn Wilhelm, auch Herzog zu Braunschweig und Lüneburg, unsere Erben, und thun hiemit zu wissen, kund und offenbahr männiglich also, der allmächtige GOtt, ohne Zweiffel aus sonderlicher Vorsehung und Begnadigung, vornemlich zu mehrer Erbreitung seines ewigen Lobes, und auch vielen Menschen zu sonderbahrer Besserunge unsers Bergwercks zu unserm Fürstenthum an dem Iberge zu Gittelde und im Grunde, also daß das Ertz den Erbstollen den Gruben die Wasser-Noht gäntzlich und wol benommen fordert. Dergleichen aufn Zellerfelde, welches Bergwerck wir auch mit dem Hochgebohrnen Fürsten, unsern freundlichen lieben Vettern, Herrn Philip, Herzog zu Braunschweig und Lüneburg vergleichet, vertragen, und wol vereiniget, einen sonderlichen zuselben Vorgang gewinnen, und sich daraus einen treflichen Nutzen ereugnet ungezweiffelt. So beruhet unser Bergwerck mit guter ordentlicher Regierung, auch Gnade und Freyheit löblichen versehen, und begnadet, daß sie für und für größern und mehrern Fortgang gewinnen [...] haben Wir nachfolgende Gnade und Freyheit hier aufgeben und thun wollen.",
         en="Die erste Bergfreiheit, die Herzog Heinrich der Jüngere zu Braunschweig und Lüneburg im Jahr 1532 erteilt hat, aus Häckes handschriftlicher Geschichte des Harzer Bergwerks im Fürstentum Braunschweig.\n\nVon Gottes Gnaden wir, Heinrich, Herzog zu Braunschweig und Lüneburg, bekennen und bekräftigen für uns, für den hochgeborenen Fürsten, unseren freundlich lieben Bruder, Herrn Wilhelm, ebenfalls Herzog zu Braunschweig und Lüneburg, und für unsere Erben, und tun hiermit jedermann kund und offenbar: Der allmächtige Gott hat ohne Zweifel aus besonderer Vorsehung und Begnadung, vor allem zur weiteren Ausbreitung seines ewigen Lobes und vielen Menschen zum Besten, unser Bergwerk in unserem Fürstentum am Iberg bei Gittelde und im Grund so gebessert, dass das Erz den Erbstollen fördert, der den Gruben die Wassernot ganz und gut genommen hat. Ebenso wird das Bergwerk auf dem Zellerfeld, über das wir uns mit dem hochgeborenen Fürsten, unserem freundlich lieben Vetter, Herrn Philipp, Herzog zu Braunschweig und Lüneburg, verglichen, vertragen und gut geeinigt haben, ohne Zweifel einen besonderen Fortgang nehmen und großen Nutzen bringen. Damit nun unser Bergwerk mit guter, ordentlicher Regierung, mit Gnade und Freiheit löblich versehen und begnadet sei, so dass es immer größeren Fortgang gewinne [...], haben wir die folgende Gnade und Freiheit erteilen wollen.",
         note="Heinrich der Jüngere von Braunschweig-Wolfenbüttel (1489–1568) war nach der neueren Literatur der Landesherr, der den Oberharzer Bergbau in großem Stil wieder in Gang brachte. Der Satz über den Erbstollen ist im Druck schwer gebaut (‚also daß das Ertz den Erbstollen den Gruben die Wasser-Noht gäntzlich und wol benommen fordert‘); übertragen ist nach dem Sinn, unsicher. Klar ist der Inhalt: Schon 1532 ist das Wasser das erste Thema einer Bergfreiheit. Ein Erbstollen ist ein Stollen, der von einem tiefer gelegenen Tal aus in den Berg getrieben wird, damit das Grubenwasser von selbst abläuft. ‚Häckens geschriebene Historie‘ ist eine Handschrift, die Calvör benutzte; über ihren Verfasser sagt er hier nichts."),
    dict(n=2, titel="Offene Wege, sicheres Geleit, freier Abzug", pg="Calvör 1765, S. 218", lang="fnhd",
         orig="Anfänglich sol männiglich durch Unser Fürstenthum, Obrigkeit, Gericht und Gebieten zu und abe bemeldten Unsern Bergwercks Straßen, Stege und Wege offen und frey seyn, samt dem Wasser Hütten und Puchwerck, auch allen andern Gebäuden, wie altes Herkommens und Bergwerks-Recht und Gewohnheit ist.\n\nZudem sollen alle und jede Bergleute, und die auf bemeldten unsern Bergwercke setzen, und sich wenden wollen, vor aller Gewalt sicher frey und ohngefährlich Geleit haben [...]\n\nIngleichen sollen die Bergleute ihre Güter, so sie mit sich bringen, oder aber der Oerter bey und an unserm Bergwerke überkommen werden, mögen sie ihres besten behaglichen Wolgefallens damit zugeparen, zu verkauffen, oder zu verpeuten, Gewalt haben, und sonst nach eines jeden Gelegenheit mit seinem Haab und Gütern ziehen, unserntwegen und sonst von männiglich ungehindert und ungekümmert, doch daß zuvor der Abzug der Schulden, welche der abziehende auf unsern Bergwercke gemacht, zu billig und bührlich bezahlet werden.",
         en="Zuerst sollen für jedermann durch unser Fürstentum, unsere Obrigkeit, unser Gericht und Gebiet zu und von unserem Bergwerk Straßen, Stege und Wege offen und frei sein, samt dem Wasser, den Hütten und Pochwerken und allen anderen Gebäuden, wie es altes Herkommen und Bergwerksrecht und Gewohnheit ist.\n\nZudem sollen alle und jede Bergleute und die, die sich auf unser Bergwerk setzen und dorthin wenden wollen, vor aller Gewalt sicher, frei und ungefährdet Geleit haben [...]\n\nEbenso sollen die Bergleute mit ihren Gütern, die sie mitbringen oder dort bei und an unserem Bergwerk erwerben werden, nach ihrem besten Gefallen verfahren dürfen, sie aufbewahren, verkaufen oder vertauschen, und sonst nach eines jeden Gelegenheit mit ihrer Habe und ihren Gütern wegziehen, von uns und jedermann ungehindert und unbehelligt; doch so, dass vor dem Abzug die Schulden, die der Abziehende auf unserem Bergwerk gemacht hat, billig und gebührlich bezahlt werden.",
         note="Gleich im ersten Artikel steht das Wasser neben den Wegen: Es soll frei sein, wie die Straßen. ‚Verpeuten‘ ist ‚vertauschen‘ (von ‚Beute‘ im alten Sinn von Tausch); ‚zugeparen‘ ist unsicher, wohl ‚aufbewahren, beiseitelegen‘. Anders als die Hohnsteiner Freiheit ([Hohnstein 2]) schützt diese nicht vor alten Schulden, verlangt aber, dass die vor Ort gemachten bezahlt werden, ehe einer weiterzieht."),
    dict(n=3, titel="Markt, Bier, keine Steuer, Bauholz nach Anweisung", pg="Calvör 1765, S. 218", lang="fnhd",
         orig="Ferner ordnen und setzen wir, und geben nach, daß die Bergleute einen freyen Wochen Marckt alle Sonnabend bey Gittel im Grunde, und aufn Zellerfeld halten, haben sollen und mögen [...] mit Brod, Wein, Bier, Butter, Käse, Eyer, Saltz, Gewand, und alle dem, das die Bergleute nohtdürfftig seyn werden, zu besuchen, und abzuführen Zollfrey unbeschweret. Ueber das geben wir befreyen, und begnaden alle Bergleute, so auf dem berührten unsern Bergwerck wohnen, daß sie selbst mögen backen, brauen, schlachten, Wein und Bier, zudem auch allerley fremd Getränke schenken, und so sie auf bemeldte Bergwercke ziehen, alda mit Haus sitzen, und wohnen werden, sol ihnen frey seyn, ohn allen Zol zu handeln, und aller Steuer und Hoffdienste, auch Accise ledig und ohne seyn. Alleine, so gemeine hohe Landes-Noht erfodert, was denn jedermann aus guten Willen thun wollt, doch sollen sie alle und ein jeder ungenöhtiget seyn.\n\nWir wollen auch in unserm Fürstenthum und Gebiet Bauholz, so viel auf die Zechen, und in den Gruben zu setzen, zu Zimmern, und zu Häusern von nöhten, frey ohne allen Zins hauen, zu gebrauchen, und genießen lassen. Alleine, daß nach Anweisung unsers Försters ordentlich und nohtdürfftiglich gehauen werde.",
         en="Ferner ordnen und setzen wir fest und gestatten, dass die Bergleute jeden Samstag einen freien Wochenmarkt bei Gittelde im Grund und auf dem Zellerfeld halten sollen und dürfen [...], mit Brot, Wein, Bier, Butter, Käse, Eiern, Salz, Tuch und allem, was die Bergleute brauchen werden, ihn zu besuchen und davon abzufahren, zollfrei und unbelastet. Überdies befreien und begnaden wir alle Bergleute, die auf unserem Bergwerk wohnen: Sie dürfen selbst backen, brauen, schlachten, Wein und Bier und auch allerlei fremde Getränke ausschenken; und wenn sie auf das Bergwerk ziehen und dort mit eigenem Haus sitzen und wohnen werden, soll ihnen frei sein, ohne jeden Zoll zu handeln, und sie sollen aller Steuer, aller Hofdienste und auch der Akzise ledig und frei sein. Nur wenn eine allgemeine hohe Not des Landes es erfordert, soll jedermann aus gutem Willen tun, was er will; doch sollen sie alle und jeder Einzelne ungenötigt bleiben.\n\nWir wollen sie auch in unserem Fürstentum und Gebiet Bauholz, so viel für die Zechen, zum Setzen in den Gruben, zum Zimmern und für Häuser nötig ist, frei ohne jeden Zins hauen, gebrauchen und nutzen lassen; nur dass es nach Anweisung unseres Försters ordentlich und nach Bedarf gehauen werde.",
         note="Elf Jahre nach Hohnstein steht beim Holz schon ein Vorbehalt: ‚nach Anweisung unsers Försters‘. Der Wald war nicht mehr unbegrenzt. ‚Gewand‘ ist Tuch für Kleidung. Akzise ist eine Verbrauchssteuer wie das Ungeld."),
    dict(n=4, titel="Das Silber gehört in die Kammer; die Ordnung von Joachimsthal", pg="Calvör 1765, S. 218–219", lang="fnhd",
         orig="Zudem allen wollen wir bemeldeten Bergleuten und Gewerken drey Jahr nach einander den ordentlichen unsern gebührenden Zehnten frey geben, und nachgelassen haben, wie wir das gegenwärtiglichen thun, und dermaßen befreyen und begnaden.\n\nDamit nun zu allen in diesem Fall gute Ordnung und Versehung gemacht, wollen wir den itzigen und zukünftigen Gewerken alle das Silber, so sie auf berührten unsern Bergwercke machen, und zukünfftig machen werden, eine jegliche Marck mit acht Gulden und ein Orth Müntze, und einen jeden Centner Bley mit XXXIII. Ss. (wird Schilling bedeuten sollen) Goslarsche aus unser Kammer wollen bezahlen lassen, dahin sie es uns, wie in andern Chur- und Fürstenthümern, Graf- und Herrschaften der Bergwerke Recht und Gewohnheit bey gebührlicher und schwerer Unser Straffe antworten sollen.\n\nUnd diese Unsere und andere Unsers Fürstenthums Bergwerke, so itzunder, und darinnen hernachmals aufkommen werden, sollen nach Unserer Berg-Ordnung, die wir gleich St. Jochimsthal, und Annenberger Berg-Ordnung, aufgerichtet haben, von unsern darzu verordneten Amtleuten regieret, und von jedermänniglich gehalten werden. [...] Im Jahr Christi 32. Unsers lieben Herrn 1500. den Montag nach Quasimodogeniti.",
         en="Zu alledem wollen wir den genannten Bergleuten und Gewerken drei Jahre nacheinander unseren ordentlichen, gebührenden Zehnten erlassen, wie wir es hiermit tun, und sie insoweit befreien und begnaden.\n\nDamit nun in alledem gute Ordnung und Vorsorge getroffen sei, wollen wir den jetzigen und künftigen Gewerken alles Silber, das sie auf unserem Bergwerk machen und künftig machen werden, die Mark mit acht Gulden und einem Ort Münze, und jeden Zentner Blei mit 33 Schilling (‚wird Schilling bedeuten sollen‘) Goslarscher Münze aus unserer Kammer bezahlen lassen; dorthin sollen sie es uns, wie es in anderen Kur- und Fürstentümern, Grafschaften und Herrschaften Recht und Gewohnheit der Bergwerke ist, bei gebührlicher und schwerer Strafe abliefern.\n\nUnd diese unsere und die anderen Bergwerke unseres Fürstentums, die jetzt bestehen und künftig darin aufkommen werden, sollen nach unserer Bergordnung, die wir nach der Bergordnung von St. Joachimsthal und Annaberg aufgerichtet haben, von unseren dazu verordneten Amtleuten regiert und von jedermann gehalten werden. [...] Im Jahr Christi 1532, am Montag nach Quasimodogeniti.",
         note="Quasimodogeniti, der erste Sonntag nach Ostern, war 1532 der 7. April; der Montag danach also der 8. April 1532. Ein Ort ist ein Viertelgulden. Die Klammer ‚(wird Schilling bedeuten sollen)‘ ist Calvörs Erklärung der Abkürzung im Druck. Der Kern: Das Silber muss zu einem festen Preis an die Kammer des Herzogs abgeliefert werden, bei schwerer Strafe. Joachimsthal und Annaberg im Erzgebirge waren die großen Silberstädte der Zeit; nach ihrem Vorbild wird der Oberharz geordnet, und aus dem Erzgebirge kamen nach der neueren Literatur auch viele der ersten Bergleute. Die Jahreszahl steht im Druck in dieser umständlichen Form: ‚Im Jahr Christi 32. Unsers lieben Herrn 1500.‘"),
]

CLAUSTHAL = [
    dict(n=1, titel="Die Freiheit für den Clausberg; Holz nach Anweisung, Kohlholz fünf Jahre frei", pg="Calvör 1765, S. 219", lang="fnhd",
         orig="Herzog Ernst zu Braunschweig und Lüneburg zu Grubenhagen A. 1554. ertheilete Bergfreyheit, nach dem Original so auf Pergament geschrieben, und auf einer großen im Clausthalischen Bergamte hangenden Tafel geheftet ist.\n\nWir von GOttes Gnaden Ernst, Herzog zu Braunschweig und Lüneburg &c. thun kund hiemit, und bekennen vor Uns, und die Hochgebohrne Fürsten, Herrn Johansen, Herrn Wolffgangen, und Herrn Philipsen, auch Herzoge zu Braunschweig und Lüneburg, alle Herzog Philips seliger Söhne, unsere freundliche liebe Brüder [...] Wollen auch diese nachgeschriebene sünderliche Freyheite allen und jeden Gewerken, so sich auf unsere freye Bergstadt auf dem Clausberge, in und an den Clausthälern samt andern umliegenden Bergen und Thälern in unserm Fürstenthum allenthalben einleggen, Bergwerck suchen, bauen, und sich der Oerter gebrauchen werden, daß sie 1) uff unsern Wäldern zu aller Nohtdurfft Schachtholtz, Bauholtz zu Bauung der Schächte, Hütten, Puchwercke, Röste-Holtz, auch Brennholtz nach nohtdurfft ohne allen Forst-Zinß, doch durch Anweisung unserer Förster, in unsern Gehöltzen, wo das wil gelegen seyn, (doch nichts davon zu verkauffen) bedürffen werden, zu hohlen, und zu gebrauchen nachlassen. Aber Kol- und Treibholtz sol jedern nach Unserer Ordnung, und uf Anweisung unser Förster zu hauen, und fünf Jahr lang, die nechstkünfftigen, Zinsen frey seyn, folgend um einen gebührlichen ziemlichen benanten Waldzinß gegeben werden.",
         en="Die Bergfreiheit, die Herzog Ernst zu Braunschweig und Lüneburg zu Grubenhagen im Jahr 1554 erteilt hat, nach dem Original, das auf Pergament geschrieben und auf eine große Tafel geheftet ist, die im Clausthaler Bergamt hängt.\n\nWir, von Gottes Gnaden Ernst, Herzog zu Braunschweig und Lüneburg usw., tun hiermit kund und bekennen für uns und für die hochgeborenen Fürsten, Herrn Johann, Herrn Wolfgang und Herrn Philipp, ebenfalls Herzöge zu Braunschweig und Lüneburg, alle Söhne des seligen Herzogs Philipp, unsere freundlich lieben Brüder [...]: Wir wollen diese hier aufgeschriebenen besonderen Freiheiten allen und jeden Gewerken geben, die sich auf unserer freien Bergstadt auf dem Clausberg, in und an den Clausthälern und in den anderen umliegenden Bergen und Tälern unseres Fürstentums überall einlegen, Bergwerk suchen, bauen und die Orte nutzen werden, nämlich 1): dass sie aus unseren Wäldern zu allem Bedarf Schachtholz, Bauholz zum Bau der Schächte, Hütten und Pochwerke, Röstholz und auch Brennholz nach Bedarf ohne jeden Forstzins, doch nach Anweisung unserer Förster, in unseren Gehölzen, wo es günstig liegt, holen und gebrauchen dürfen, soweit sie es brauchen werden (doch nichts davon zu verkaufen). Aber Kohl- und Treibholz soll jeder nach unserer Ordnung und auf Anweisung unserer Förster hauen; es soll die nächsten fünf Jahre zinsfrei sein und danach gegen einen gebührlichen, angemessenen, festgesetzten Waldzins abgegeben werden.",
         note="Herzog Ernst von Braunschweig-Grubenhagen; Clausthal gehörte zu Grubenhagen, Zellerfeld zu Wolfenbüttel (nach der neueren Literatur). Calvör druckt nach dem Original, das im Bergamt Clausthal noch 1765 öffentlich aushing. Wieder steht das Holz an erster Stelle, aber nun ganz unter der Anweisung der Förster, und die Holzkohle kostet nach fünf Jahren einen Waldzins. Zwischen 1521 und 1554 wird das Holz vom Geschenk zur Ware."),
    dict(n=2, titel="Belohnung für neue Gänge; die Stadt wird abgemessen", pg="Calvör 1765, S. 220", lang="fnhd",
         orig="2) Allen und jeden Bergleuten, so sich auf und um bemeldte Unsere Bergstädte und Fürstenthum Bergwerck zu suchen und schürffen einlegen werden, neue unverschrottene Gänge, so Silber halten, entplösen, und also erfindlich anzeigen werden, gegen die wollen wir Uns mit stattlicher Verehrung in Gnaden erzeigen.\n\nWas auch hinfürter in eröfneten, und uneröfneten Feldern von Silber und allerley Metall von dato an erbauet, sollen von Uns fünf Jahr des Zehnten gefreyet seyn.\n\n3) Wir wollen auch dieses, als ein frey Bergwerck begnaden und befreyen, wie auf der Chur- und Fürsten, Grafen und Herren Bergstädten gewöhnlich ist; Also, daß sie Hütten, Puchwercke, Wohnhäuser, Scheunen und Ställe nach ihrer Nohtdurfft zu bauen, und anzurichten haben; doch sollen sie alles ordentlich bauen, wie wir die Städte ordentlich abmeßen lassen wollen, wohin der Marckt, die Gassen, Kirchen, Rahthauß, und alles andere sol gesetzet werden.",
         en="2) Allen und jeden Bergleuten, die sich auf und um unsere genannten Bergstädte und im Bergwerk unseres Fürstentums zum Suchen und Schürfen einlegen und neue, noch nicht angehauene Gänge, die Silber führen, freilegen und so nachweisbar anzeigen werden, wollen wir uns mit einer stattlichen Belohnung gnädig erweisen.\n\nUnd was künftig in eröffneten und noch nicht eröffneten Feldern an Silber und allerlei Metall von heute an abgebaut wird, soll von uns fünf Jahre lang vom Zehnten befreit sein.\n\n3) Wir wollen dies auch als ein freies Bergwerk begnaden und befreien, wie es auf den Bergstädten der Kur- und Fürsten, Grafen und Herren üblich ist: dass sie Hütten, Pochwerke, Wohnhäuser, Scheunen und Ställe nach ihrem Bedarf bauen und anlegen dürfen; doch sollen sie alles ordentlich bauen, so wie wir die Städte ordentlich abmessen lassen wollen, wo der Markt, die Gassen, Kirchen, das Rathaus und alles andere hingesetzt werden soll.",
         note="‚Unverschrotten‘: noch nicht angehauen. Die Belohnung für das Finden neuer Gänge ist ein Prämiensystem für Prospektoren. Fünf Freijahre beim Zehnten statt drei (1532, [Heinrich 4]). Neu gegenüber 1521: Die Bergstadt wird nicht gewachsen gelassen, sondern vom Landesherrn abgemessen, mit Markt, Gassen, Kirche und Rathaus an vorgegebenen Plätzen."),
    dict(n=3, titel="Berghauptmann und Bergmeister; die Hütte des Herzogs; vier Kuxe", pg="Calvör 1765, S. 220–221", lang="fnhd",
         orig="8) So wollen wir auch erstlich unser Bergstadt einen Berghauptmann, Bergmeister, Richter und Schöppen setzen und ordnen, die sie von unserntwegen regieren und halten, wie auf einer freyen Bergstadt üblich und gebräuchlich ist. So sich auch jemand an Urtheil und Recht beschweret finden würde, dem sol an Uns, oder an unsere Rähte zu appelliren frey stehen. [...]\n\n10) Nachdem auch diese unsere Bergwercke neu, die auch Hütten und Puchwercke bedürffig, welche den Gewercken im Anfange zu erbauen beschwerlich; So haben wir aus sonderbahren gnädigen bedächtigen Willen eine Schmeltz-Hütte und Puchwerck auf unsere Unkosten erbauen und anrichten lassen, darin wir die gnädige Versehung thun lassen wollen, daß die Hütten- und Puch-Gäste, so unserer Hütten und Puchwercke gebrauchen, durch solch schmeltz und puchen zu lassen, mit keiner ungebührlichen Beschwerung übernommen werden [...] hierentgegen sollen auch die Gewercken in keiner andern Herrschafft, oder Obrigkeit puchen, oder schmeltzen lassen.\n\n11) Uns behalten wir zuvor in allen Zechen die Erb-Kuckes, als auf jeder Zechen 4. zu bauen.",
         en="8) So wollen wir auch zuerst unserer Bergstadt einen Berghauptmann, einen Bergmeister, Richter und Schöffen setzen und bestellen, die sie in unserem Namen regieren und halten, wie es auf einer freien Bergstadt üblich und gebräuchlich ist. Und wenn sich jemand durch ein Urteil oder Recht beschwert fühlen würde, dem soll es freistehen, sich an uns oder unsere Räte zu wenden. [...]\n\n10) Weil diese unsere Bergwerke neu sind und Hütten und Pochwerke brauchen, die den Gewerken im Anfang zu bauen schwerfällt, haben wir aus besonderem, gnädigem und bedachtem Willen eine Schmelzhütte und ein Pochwerk auf unsere Kosten bauen und einrichten lassen; darin wollen wir gnädig dafür sorgen lassen, dass die Hütten- und Pochgäste, die unsere Hütte und unser Pochwerk benutzen, beim Schmelzen- und Pochenlassen mit keiner ungebührlichen Belastung übervorteilt werden [...]; dagegen sollen die Gewerken auch in keiner anderen Herrschaft oder Obrigkeit pochen oder schmelzen lassen.\n\n11) Wir behalten uns zuvor in allen Zechen die Erbkuxe vor, auf jeder Zeche vier zu bauen.",
         note="Hier entsteht das Bergamt, das in diesem Apparat und im Begleitspiel die Hauptrolle hat: Berghauptmann und Bergmeister ‚von unserntwegen‘, eingesetzt vom Landesherrn, nicht gewählt wie Rat und Richter in Hohnstein 1521 ([Hohnstein 4]). Die Hütte des Herzogs ist eine Hilfe für die Anfänger und zugleich ein Zwang: Gepocht und geschmolzen wird nur im eigenen Land. Ein Kux ist ein Anteil an einer Grube; Erbkuxe gehörten dem Grundherrn. Ob ‚zu bauen‘ heißt, dass der Herzog für seine vier Kuxe wie jeder Gewerke Zubuße zahlte, sagt der Text nicht. Ausgelassen ist Artikel 9 über Badstuben, Brot- und Fleischbänke, Mühlen und Salzkästen."),
    dict(n=4, titel="Ein Teil der Kirche, einer der Gemeinde; zwölf, dann zehn Gulden", pg="Calvör 1765, S. 221", lang="fnhd",
         orig="12) Nachdem auch auf allen löblichen Bergstädten gewöhnlich, da durch die Gnade GOttes Zechen fündig, und zu der Ausbeute gerahten, daß die Austheilung auf hundert und dreißig partes gelegt, und der eine Theil der Kirchen, der andere der Gemeine zugestellet wird, daß die gottselige und löbliche Gewohnheit also uf unserm Bergwercke sol gehalten werden. Damit auch allerseits in diesem Fall gute Ordnung, und Versicherung gemacht, wollen wir den itzigen und künftigen Gewercken die Silber, Bley und Glödt die jetzt künfftigen fünf Jahr Zehent frey lassen, aber die ersten zwey Jahr eine jede Marck fein gebrant Silber Erfurdischer Gewicht wollen wir ihnen mit zwölff Gulden Braunschweigischer Landesweriger Müntze, und nach Ausgange der zweyer Jahr jede Marck mit zehen Gulden berührten Gewicht und Wehrt aus unser Zehnt-Kammer (die wir an unserm gelegenen Orte dazu anordnen werden) dergleichen die ersten zwey Jahr einen jeden Centner Bley mit zweyen Gulden, und ein Centner Glödt, wie es zu Goslar in der Zehnt-Kammer bezahlet wird, wol bezahlen lassen.\n\n13) Es soll auch Silber, Bley und Glödt in unsere Zehnt-Kammer, wo wir solches verordnen werden, uns, wie auf Königlichen, Chur- und Fürstlichen, Grafen und Herrschafften Bergwercken gebräuchlich, bey gebührlicher schwerer Straffe überantwortet werden.",
         en="12) Weil es auch auf allen löblichen Bergstädten üblich ist, dass, wenn durch Gottes Gnade Zechen fündig werden und Ausbeute geben, die Verteilung auf hundertdreißig Teile gelegt und ein Teil der Kirche, ein anderer der Gemeinde zugeteilt wird, soll diese gottselige und löbliche Gewohnheit auch auf unserem Bergwerk gehalten werden. Und damit in diesem Fall allerseits gute Ordnung und Sicherheit herrsche, wollen wir den jetzigen und künftigen Gewerken Silber, Blei und Glätte die nächsten fünf Jahre zehntfrei lassen; aber die ersten zwei Jahre wollen wir ihnen jede Mark fein gebranntes Silber Erfurter Gewichts mit zwölf Gulden braunschweigischer Landeswährung bezahlen lassen und nach Ablauf der zwei Jahre jede Mark mit zehn Gulden dieses Gewichts und Werts, aus unserer Zehntkammer (die wir an einem dafür gelegenen Ort einrichten werden), ebenso in den ersten zwei Jahren jeden Zentner Blei mit zwei Gulden und einen Zentner Glätte so, wie er in Goslar in der Zehntkammer bezahlt wird.\n\n13) Silber, Blei und Glätte sollen uns auch in unsere Zehntkammer, wo wir sie einrichten werden, abgeliefert werden, wie es auf königlichen, kur- und fürstlichen, gräflichen und herrschaftlichen Bergwerken üblich ist, bei gebührlicher schwerer Strafe.",
         note="Ausbeute ist der Gewinn, der an die Gewerken verteilt wird, wenn eine Grube mehr bringt, als sie kostet; Zubuße das Geld, das sie nachschießen müssen, wenn sie weniger bringt. Von 130 Teilen gehen je einer an Kirche und Gemeinde; die übrigen 128 sind, wie sonst üblich, die Kuxe der Gewerken (das sagt der Text nicht ausdrücklich). Glätte (‚Glödt‘) ist Bleiglätte, Bleioxid aus dem Treiben des Silbers. Der Silberpreis sinkt nach zwei Jahren von zwölf auf zehn Gulden die Mark: Die Anfangszeit wird belohnt, danach verdient der Landesherr mehr am Ankauf. 1532 hatte Heinrich der Jüngere acht Gulden und einen Ort bezahlt ([Heinrich 4]); die Gewichte (Erfurter Mark hier) und Münzen sind nicht ohne Weiteres vergleichbar."),
    dict(n=5, titel="Die Bäche bei Zellerfeld ‚zum Bergwercke nothdürfftig‘", pg="Calvör 1765, S. 221–222", lang="fnhd",
         orig="16) Da aber Unserm Fürstenthum, Herrschafften und Gebiethe Noht für fiele, welches der allmächtige GOtt nach seinen Gnaden gnädig verhüten wolle, so sollen die, so uf unsern Bergwercken sich enthalten würden, wie getreuen Unterthanen gebührlich, und wol anstehet, sich unterthäniglich erzeigen und halten. [...]\n\n18) Wir wollen auch aus gnädigen Willen zu, und nachgelassen haben, uf unsern Theil des Haartzes, nemlich um das Zellerfeld von dem Fürbke, in, und um den Abtshanff, den Dietrichsberg, und alsdenn den Weg hinaus bis für dem Kehrwieder vor dem schwart Zencke, von dar bis an den Honscher Weg vor den Ornborn hin bis an die Inderste, und zwischen der Inderste und dem Zellbach, welches der Herbach genant, und nicht drüber, oder weiter Hasel-Hüner, und Vogel zu fahen, und die Wasser den Zellbach, und die Inderste von der Hüttenstette, die unter Fronefels Sagemühlen, oder Brettmühlen lieget, bis dar dasselbige Wasser die Inderste in den Zellbach fleußt, derselben Wasser mit fischen, und sonsten zum Bergwercke nothdürfftig betreffend, zu gebrauchen, und sonsten alles hohen Vogel Wildpräts, Auer- und Berghahnen, und Hüner, auch Hirsch, Hinden und Rehen Wildpräts, und sonsten auch aller ander Wasser, Fischereyen, und Wildwercks bey schwerer Straffe zu meiden. [...]\n\nZu Uhrkund mit unserm Fürstlichen Hand-Secret befestiget, geschehen nach Christi, unsers lieben HErrn und Seligmachers Geburt, als man schrieb funfzehen hundert, funfzig und vier Jahr, am Donnerstage nach Viti, den II. Monats-Tag Junii.",
         en="16) Sollte aber unserem Fürstentum, unseren Herrschaften und Gebieten eine Not zufallen, die der allmächtige Gott nach seiner Gnade gnädig verhüten wolle, so sollen die, die sich auf unseren Bergwerken aufhalten, sich so untertänig erweisen und verhalten, wie es getreuen Untertanen gebührt und wohl ansteht. [...]\n\n18) Wir wollen auch aus gnädigem Willen zugelassen haben, auf unserem Teil des Harzes, nämlich um das Zellerfeld vom Fürbke, im und um den Abtshanf, den Dietrichsberg und dann den Weg hinaus bis vor das Kehrwieder vor der schwarzen Zenke, von dort bis an den Honscher Weg vor dem Ornborn bis an die Innerste, und zwischen der Innerste und dem Zellbach, der Herbach genannt wird, und nicht darüber hinaus oder weiter, Haselhühner und Vögel zu fangen, und die Gewässer, den Zellbach und die Innerste, von der Hüttenstätte, die unterhalb von Fronefels Säge- oder Brettmühle liegt, bis dahin, wo dieses Wasser, die Innerste, in den Zellbach fließt, mit Fischen und sonst, was das Bergwerk an Notdurft betrifft, zu gebrauchen; und sonst sollen sie alles hohe Federwild, Auer- und Birkhähne und -hühner, auch Hirsche, Hindinnen und Rehe, und auch alle anderen Gewässer, Fischereien und Jagden bei schwerer Strafe meiden. [...]\n\nZur Urkunde mit unserem fürstlichen Handsiegel befestigt, geschehen nach Christi, unseres lieben Herrn und Seligmachers, Geburt, als man fünfzehnhundertvierundfünfzig Jahre schrieb, am Donnerstag nach Veit, dem II. Tag des Monats Juni.",
         note="Der Druck datiert ‚am Donnerstage nach Viti, den II. Monats-Tag Junii‘. Der Veitstag (15. Juni) war 1554 ein Freitag, der Donnerstag danach also der 21. Juni; ‚II.‘ ist demnach wohl ein Druck- oder Lesefehler für 21. In Artikel 18 erscheint das Wasser zum ersten Mal als Recht des Bergwerks: Zellbach und Innerste dürfen nicht nur befischt, sondern ‚zum Bergwercke nothdürfftig‘ gebraucht werden, für Räder und Pochwerke. Die Flurnamen stehen im Druck so; einige (Fürbke, Abtshanff, Zencke, Ornborn) sind hier nicht aufgelöst. Dass Ernst von Grubenhagen Rechte ‚um das Zellerfeld‘ vergibt, das nach der neueren Literatur zu Wolfenbüttel gehörte, steht so im Druck; die Grenzen des Grubenhagener Teils sind hier nicht geprüft. Calvörs Kolumnentitel auf S. 221 nennt irrtümlich ‚Herzog Heinrich des Jüngern erste Bergfreiheit im Fürstent. Grubenhagen‘, und S. 220 ist als 218 gedruckt. Ausgelassen sind die Artikel 14, 15 und 17 (Markt, Felder, Zu- und Abzug, wie 1521) und die Bestimmung über Rat und Gericht."),
]

doc = {
    "id": "freiheit",
    "titel": "Die Bergfreiheiten, 1521–1554",
    "autor": "Die Grafen von Hohnstein (1521); Herzog Heinrich der Jüngere von Braunschweig (1532); Herzog Ernst von Braunschweig-Grubenhagen (1554)",
    "jahr": "1521–1554",
    "sprache": "de",
    "orig_sprache": "fnhd",
    "pg_label": "",
    "quelle": "H. Calvör, Historische Nachricht von der Unter- und gesamten Ober-Harzischen Bergwerke, überhaupt, auch verschiedener zu den letztern gehörigen, insonderheit [...] (Braunschweig 1765), III.–V. Anhang, S. 215–222 (Internet Archive: 10705761bsb). Übertragung: eigene Arbeit.",
    "hinweis": "Die drei Freiheitsbriefe nach Calvörs Abdruck von 1765, am Seitenbild gelesen (die Texterkennung des Fraktursatzes ist unbrauchbar), in seiner Schreibung; Calvör druckte die Hohnsteiner Freiheit nach eigener Angabe zum ersten Mal, die von 1532 nach einer Handschrift (‚Häckens geschriebene Historie‘), die von 1554 nach dem Original, das im Bergamt Clausthal aushing. Wie genau Calvör seine Vorlagen wiedergab, lässt sich hier nicht prüfen; die Schreibung ist die des 18. Jahrhunderts, nicht die der Urkunden. Auslassungen sind mit [...] bezeichnet. Die Tagesdaten sind nach dem julianischen Kalender berechnet.",
    "sections": [
        {"id": "hohnstein", "autor": "Heinrich und Ernst, Grafen von Hohnstein", "titel": "Hohnstein und Lauterberg, 1521", "zk": "Hohnstein",
         "plates": ["calvoer_s215", "merian_zellerfeld"],
         "viz": "freiheiten",
         "blurb": "Die älteste der Oberharzer Bergfreiheiten, für die Herrschaft Lauterberg, in der St. Andreasberg entstand: Holz aus allen Wäldern ‚nun und zu ewigen Zeiten‘, Bier ohne Steuer, keine Klage um alte Schulden, drei Jahre nur der fünfzehnte statt des zehnten Teils, ein selbst gewählter Rat, freier Zu- und Abzug. Was ein Landesherr versprach, um Bergleute in ein Gebirge zu locken, auf dem kein Getreide wuchs.",
         "units": HOHNSTEIN},
        {"id": "heinrich", "autor": "Herzog Heinrich der Jüngere von Braunschweig-Wolfenbüttel", "titel": "Herzog Heinrich, 1532", "zk": "Heinrich",
         "plates": [],
         "blurb": "Elf Jahre später für das Fürstentum Braunschweig, mit Zellerfeld: Der Brief beginnt mit einem Erbstollen, der den Gruben ‚die Wasser-Noht‘ genommen hat. Wege und Wasser offen, Markt am Samstag, Bier und Brot frei, keine Steuer; aber das Bauholz nur ‚nach Anweisung unsers Försters‘, das Silber zum festen Preis in die Kammer des Herzogs, und die Bergordnung nach dem Vorbild von Joachimsthal.",
         "units": HEINRICH},
        {"id": "clausthal", "autor": "Herzog Ernst von Braunschweig-Grubenhagen", "titel": "Clausthal, 1554", "zk": "Clausthal",
         "plates": ["calvoer_s219", "merian_clausthal"],
         "blurb": "Die Freiheit für die Bergstadt auf dem Clausberg, deren Original noch 1765 im Bergamt hing: Holz nur nach Anweisung der Förster, Holzkohle nach fünf Jahren gegen Waldzins, eine Stadt, die der Herzog abmessen lässt, ein Berghauptmann und ein Bergmeister von seinetwegen, eine Hütte auf seine Kosten, in der allein geschmolzen werden darf. Und zum ersten Mal das Wasser als Recht: Zellbach und Innerste ‚zum Bergwercke nothdürfftig‘ zu gebrauchen.",
         "units": CLAUSTHAL},
    ],
}

OUT.write_text(json.dumps(doc, ensure_ascii=False, indent=1), encoding="utf-8")
print("freiheit.json:", sum(len(s["units"]) for s in doc["sections"]), "Einheiten")
