"""Modul 8: Der Bergarzt. Schreibt data/arzt.json.

Quellen, am Seitenbild gelesen (Lebrecht Friedrich Benjamin Lentin, Bergmedicus und
Stadtphysicus zu Clausthal):
Beobachtungen einiger Krankheiten (Göttingen 1774), S. 13–14 (IA 11269090bsb, n24–n25).
Beyträge zur ausübenden Arzneywissenschaft [Bd. 1] (Leipzig 1789), S. 4–15, 65, 95
(IA 11107337bsb; Blatt = S.+9).
Beyträge [...], Bd. 2 (1798), S. 153–154 (IA 11741619bsb; Blatt = S.+9).
Beyträge [...], Supplementband, hg. von W. Sachse (Leipzig 1808), S. 65–66, 82–83
(IA 11741621bsb; n81–n82, n98–n99).
"""
import json
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "data" / "arzt.json"

STADT = [
    dict(n=1, titel="Gesunde Jahre, und die Dürre von 1781", pg="Lentin 1789, S. 4–5", lang="nhd",
         orig="Es hat mir der Mühe sehr werth geschienen, den Ursachen jener Dauer und Unverlezheit der allgemeinen Gesundheit meine Aufmerksamkeit zu widmen. […]\n\nWenn ich die ausserordentliche Dürre des Sommers 1781 ausnehme, bey der man eine solche Abnahme des Quellwassers spürete, daß auf Clausthal die wenigste Brunnen, und auf Zellerfeld fast gar keiner mehr Wasser gab, so liefen alle Jahrszeiten nach gewöhnlichem Wechsel ab. Obst, Früchte, Gemüse und Fleisch, alles war schmackhaft, gehörig reif, vollkommen, reichlich, und um billigste Preise zu haben. Daher waren ausser den gewöhnlichen Catarrhen, Frühjahr- und Herbstrheumatismen keine Epidemien weder unter Kindern noch Erwachsenen. Selbst jene Krankheiten, die die Geduld des Kranken und des Arztes so oft wankend machen, die chronischen, schienen weit bändiger, gelinder, seltener und bezwingbarer, so daß mir oft, wenn ich nicht an den großen Einfluß der wohlthätigsten Witterung und der Nahrungsmittel dachte, der Stolz anwandelte, ich hätte nun einen bessern Weg zu Heilung dieser Uebel gefunden.",
         en="Es schien mir sehr der Mühe wert, den Ursachen dieser langen, ungestörten allgemeinen Gesundheit meine Aufmerksamkeit zu widmen. […]\n\nWenn ich die außerordentliche Dürre des Sommers 1781 ausnehme, bei der das Quellwasser so abnahm, dass in Clausthal die meisten Brunnen und in Zellerfeld fast keiner mehr Wasser gab, verliefen alle Jahreszeiten im gewohnten Wechsel. Obst, Früchte, Gemüse und Fleisch, alles war schmackhaft, richtig reif, vollkommen, reichlich und zu den billigsten Preisen zu haben. Darum gab es außer den gewöhnlichen Katarrhen und den Rheumatismen im Frühjahr und Herbst keine Epidemien, weder unter Kindern noch unter Erwachsenen. Selbst die chronischen Krankheiten, die die Geduld des Kranken und des Arztes so oft ins Wanken bringen, schienen viel zahmer, milder, seltener und leichter zu bezwingen, so dass mich oft, wenn ich nicht an den großen Einfluss der wohltätigsten Witterung und der Nahrungsmittel dachte, der Stolz anwandelte, ich hätte einen besseren Weg zur Heilung dieser Übel gefunden.",
         note="Lentin schrieb diese Einleitung 1788 in Lüneburg, im Rückblick auf seine Clausthaler Jahre; die gesunde Zeit, von der er spricht, reicht von 1777 bis zum Spätherbst 1781 (Stadt [6]). Die Dürre von 1781, die in Clausthal und Zellerfeld die Brunnen austrocknete, ist dieselbe Sorge, die das Bergamt mit seinen Teichen hatte (Modul 4), hier aus der Sicht der Haushalte. Bemerkenswert ist die Selbstkritik des Arztes: Nicht seine Kunst, sondern Wetter und Essen hielten die Stadt gesund. Ausgelassen [‚…‘] ist ein Absatz über Hippokrates."),
    dict(n=2, titel="Was ‚der gemeine Mann‘ isst", pg="Lentin 1789, S. 7–8", lang="nhd",
         orig="Ueberhaupt genommen, fand ich zu Clausthal die Krankheiten des Herbstes weit gelinder, menschenschonender, als die Krankheiten des Frühlings. Die Ursachen dieser Verschlimmerung liegen theils darinne, daß der gemeine Mann, der neuankommenden frischen Gemüse gar zu lange ins Jahr hin, entbehren muß: früher nicht als im Junius können sie sich Otterzungen, Sauerampfer, wilde Cichorien, und dergleichen von den Wiesen zum Gemüse sammlen, und erst im Julius sind die gelben Wurzeln für sie so wohlfeil, daß sie sie kaufen können. Da es auch ihr Vermögensstand nicht zuläßt, sich mit solchen Gemüsen Vorräthe zu machen, die spät in den Winter hin zu genießen sind; so müssen Hülsenfrüchte, Mehlspeisen, Schweinefleisch und Rindfleisch — aber auch dies nicht täglich; Schweineschmalz, Wurst, Sülze, Butter ꝛc. die Speisen seyn, an denen sie sich sättigen. Milch ist schon nicht für alle: theils liegen die Ursachen aber auch in der Witterung der Jahrszeit. Der Schnee pflegt auf diesen Gebirgen bis in den April und May zu liegen, und nur bey Tage zu schmelzen.",
         en="Im Ganzen fand ich die Krankheiten des Herbstes in Clausthal viel milder und schonender als die des Frühlings. Die Ursachen dieser Verschlimmerung liegen teils darin, dass der gemeine Mann das frische Gemüse viel zu lange ins Jahr hinein entbehren muss: Nicht vor Juni können sie Natternzungen, Sauerampfer, wilde Zichorie und dergleichen auf den Wiesen als Gemüse sammeln, und erst im Juli sind die gelben Rüben so billig, dass sie sie kaufen können. Da ihre Vermögenslage es auch nicht erlaubt, sich mit Gemüse zu bevorraten, das bis spät in den Winter hinein zu essen wäre, müssen Hülsenfrüchte, Mehlspeisen, Schweine- und Rindfleisch (aber auch das nicht täglich), Schweineschmalz, Wurst, Sülze, Butter usw. die Speisen sein, an denen sie sich satt essen. Milch gibt es schon nicht für alle. Teils liegen die Ursachen aber auch in der Witterung der Jahreszeit: Der Schnee bleibt auf diesen Bergen gewöhnlich bis in den April und Mai liegen und schmilzt nur am Tag.",
         note="Der Bergarzt als Sozialbeobachter: Er erklärt die Frühjahrskrankheiten mit der Armut. Bis Juni kein frisches Gemüse, im Juni Wildkräuter von den Wiesen, im Juli die ersten bezahlbaren Möhren; Vorräte kann sich ‚der gemeine Mann‘ nicht leisten, ‚Milch ist schon nicht für alle‘. Auf der Hochfläche wuchs nach Lentin kein Obst (Stadt [5]); Getreide musste ohnehin ins Gebirge geschafft werden, was die Bergfreiheiten mit Zollfreiheit erleichtern wollten (Modul 1). Wer genau ‚der gemeine Mann‘ ist, sagt Lentin nicht; gemeint sind wohl die Familien der Berg-, Poch- und Hüttenleute."),
    dict(n=3, titel="Der Ostwind bringt dreißig, vierzig Kranke", pg="Lentin 1789, S. 6, 9", lang="nhd",
         orig="Gar vielfältig habe ich bey unzeitigem, anhaltendem Regen wenig Kranke gesehen, die aber mein Haus stürmen zu wollen schienen, nachdem entweder Hitze oder Frost unmittelbar darauf gefolgt war. […]\n\nDer Ostwind, der die eißkalte Schneeluft vom Brocken und seinen hochaufgethürmten Nachbaren, noch dann auf uns herabbläßt, wenn man in den niedrigern Provinzen Gärten und Land bestellt, und Frühlingsluft athmet, ist hier einer der beschwerlichsten. Sehr oft habe ich die Bemerkung gemacht, daß einige Stunden Ostwind, mir gleich dreißig, vierzig Kranke von einerley Art zuwege brachte.",
         en="Sehr oft habe ich bei unzeitigem, anhaltendem Regen wenige Kranke gesehen, die aber mein Haus stürmen zu wollen schienen, wenn unmittelbar danach Hitze oder Frost folgte. […]\n\nDer Ostwind, der die eiskalte Schneeluft vom Brocken und seinen hoch aufgetürmten Nachbarn noch dann auf uns herabbläst, wenn man in den tieferen Gegenden Gärten und Felder bestellt und Frühlingsluft atmet, ist hier einer der beschwerlichsten. Sehr oft habe ich bemerkt, dass einige Stunden Ostwind mir sogleich dreißig, vierzig Kranke derselben Art einbrachten.",
         note="Eine Praxis ohne Krankenhaus: Die Kranken kommen zum Haus des Arztes, und bei einem Wetterumschlag ‚stürmen‘ sie es. Lentin beobachtet die Gesundheit einer ganzen Stadt wie ein Meteorologe; an anderer Stelle beschreibt er, wie er bei Epidemien täglich ‚vierzig, sechzig und mehrere‘ zu versorgen hatte (S. 16). Ausgelassen [‚…‘] sind seine Erklärungen nach der Säftelehre seiner Zeit."),
    dict(n=4, titel="Heidelbeeren und ‚der immerwährende Leckerbissen des Bergmanns‘", pg="Lentin 1789, S. 12", lang="nhd",
         orig="Ganz sichtbar hat sich die Anzahl der Kranken vermehret, wenn die Erfrischungen, die sich das Volk häufig anschaffen kann, fehlten: wenn entweder im Frühjahre die Erdbeere, oder im Sommer die Kirschen, und Heidelbeere (vaccinium myrtillus Linn.), und der immerwährende Leckerbissen des Bergmanns, die Krohnsbeere (vaccinium vitis idaea Linn.), mangelten. Es ist dahero schon zum Sprichwort geworden, daß die Heidelbeerenzeit die gesundeste im Jahre sey. Allein ausser der Wohlthätigkeit dieser Frucht, kommt noch das in Betracht: daß der häufigste Genuß derselben, just in die Jahrszeit fällt, in welcher die Frühjahrskrankheiten geendigt, und die Krankheiten des Herbsts sich noch nicht gebildet haben, und vom Volke nichts ungesundes genossen wird.\n\nAn Fleisch hat Clausthal nie Mangel. Ausser dem frischen Fleische und dem Wildpret, so aber größtentheils nur aus Rothwild, und wenigem Schwarzwild bestehet, wurde der Harz vordem reichlich von Zugvögeln, vornehmlich Schildamseln, Drosseln und Zippen, auch andern Kleinern, und Singvögeln besucht, deren Menge aber von Jahr zu Jahr mit zunehmender Geschicklichkeit der Nachbaren im Vogelfang, sehr abgenommen hat.",
         en="Ganz sichtbar hat sich die Zahl der Kranken vermehrt, wenn die Erfrischungen fehlten, die sich das Volk sonst reichlich verschaffen kann: wenn im Frühjahr die Erdbeeren oder im Sommer die Kirschen und Heidelbeeren (Vaccinium myrtillus L.) und der immerwährende Leckerbissen des Bergmanns, die Preiselbeere (Vaccinium vitis-idaea L.), ausblieben. Darum ist es schon zum Sprichwort geworden, dass die Heidelbeerzeit die gesündeste im Jahr sei. Außer der Wohltat dieser Frucht kommt aber noch hinzu, dass man sie gerade in der Jahreszeit am meisten isst, in der die Frühjahrskrankheiten vorüber sind und die Herbstkrankheiten sich noch nicht gebildet haben, und das Volk nichts Ungesundes isst.\n\nAn Fleisch hat Clausthal nie Mangel. Außer frischem Fleisch und Wildbret, das aber größtenteils nur aus Rotwild und wenig Schwarzwild besteht, wurde der Harz früher reichlich von Zugvögeln besucht, vor allem Ringdrosseln, Drosseln und Singdrosseln, auch anderen kleineren und Singvögeln, deren Zahl aber mit der zunehmenden Geschicklichkeit der Nachbarn im Vogelfang von Jahr zu Jahr stark abgenommen hat.",
         note="Was der Wald zur Ernährung gab: Beeren, die man sammeln konnte, ohne zu kaufen, und Vögel aus dem Vogelfang. Die Preiselbeere als ‚Leckerbissen des Bergmanns‘ ist eine der wenigen Stellen, an denen Lentin den Bergmann ausdrücklich nennt. ‚Krohnsbeere‘ ist ein regionaler Name der Preiselbeere; ‚Schildamseln‘ und ‚Zippen‘ übertragen wir nach der neueren Literatur als Ringdrosseln und Singdrosseln. ‚An Fleisch hat Clausthal nie Mangel‘ steht neben Stadt [2], wo Fleisch ‚nicht täglich‘ auf den Tisch kommt: Es gab Fleisch, aber nicht für jeden Tag."),
    dict(n=5, titel="Die Frauen tragen das Land herauf", pg="Lentin 1789, S. 13", lang="nhd",
         orig="Da ausser obgenannten Obstarten hier nichts recht reif und schmackhaft werden kann, denn in dem Luftniveau des Oberharzes wächst im Walde weder Eiche noch Büche mehr, […] und folglich weder Apfel- noch Birnbaum; so treibt die Lust zu Gewinn unsere Weibsleute, alles was wir von Obst bedürfen, oder vielmehr was zu bekommen ist, aus dem Lande zusammen zu holen, und auf dem Rücken heraufzutragen. Daher es denn aber auch kommt, daß das Obst, da es zwey bis drey Meilen weit hergeholt werden muß, nicht ausgesucht gut ist, und durch das lange Tragen gedrückt und gequetscht, dem Verderben nicht lange widersteht, man also dieser Erfrischung gar bald wieder entbehren muß. Dieser Art Gewerbe, das sich auch auf das Eintragen des Heues, Nachgrases, des goßlarischen Biers erstreckt, ist es aber auch zuzuschreiben, daß Mißfälle an keinem Orte leicht häufiger statt finden, als hier. Es trägt sich auch nicht gar selten zu, daß eine Schwangere unterwegens Geburtsschmerzen bekommt, mit einer Gehülfinn hinter Busch gehet, und gebähret, dann ihre Last wieder auf den Rücken, und das neugebohrne Kind in die Schürze nimmt, und so ihre Heimreise endigt. Diese Bemerkung scheint dem ersten Ansehen nach denen Geschichten sehr gleich, wie sie die Liebe zum wunderbaren zur Welt zu bringen pflegt; allein die Wahrheit dieses hebraismus hat sich zur Genüge bestätiget.",
         en="Da außer den genannten Obstarten hier nichts recht reif und schmackhaft werden kann – denn in der Höhenlage des Oberharzes wächst im Wald weder Eiche noch Buche mehr […] und folglich auch weder Apfel- noch Birnbaum –, treibt die Lust zum Erwerb unsere Frauen dazu, alles Obst, das wir brauchen, oder vielmehr, was zu bekommen ist, im Land zusammenzuholen und auf dem Rücken heraufzutragen. Daher kommt es aber auch, dass das Obst, weil es zwei bis drei Meilen weit hergeholt werden muss, nicht besonders gut ist, durch das lange Tragen gedrückt und gequetscht wird, nicht lange hält und man diese Erfrischung bald wieder entbehren muss. Diesem Gewerbe, das sich auch auf das Hereintragen von Heu, Grummet und Goslarer Bier erstreckt, ist es aber auch zuzuschreiben, dass Fehlgeburten kaum an einem Ort häufiger vorkommen als hier. Es kommt auch nicht gar selten vor, dass eine Schwangere unterwegs Wehen bekommt, mit einer Helferin hinter einen Busch geht und gebiert, dann ihre Last wieder auf den Rücken und das Neugeborene in die Schürze nimmt und so ihren Heimweg beendet. Diese Bemerkung gleicht auf den ersten Blick den Geschichten, die die Liebe zum Wunderbaren in die Welt zu setzen pflegt; aber die Wahrheit dieser biblischen Wendung hat sich zur Genüge bestätigt.",
         note="Die Arbeit, die in keiner Bergordnung steht: Frauen tragen Obst, Heu und Bier zwei bis drei Meilen auf dem Rücken ins Gebirge, ein Erwerb, den Lentin ‚Lust zu Gewinn‘ nennt. Er verbindet ihn mit einer medizinischen Folge, den häufigen Fehlgeburten, und berichtet von Geburten am Wegrand. Der ‚hebraismus‘ spielt auf die Hebräerinnen in Exodus 1,19 an, die gebären, bevor die Hebamme kommt. Die Gewalt dieser Lebensverhältnisse ist keine Tat eines Einzelnen; Lentin beschreibt sie nüchtern, ohne Abhilfe vorzuschlagen. Ausgelassen [‚…‘] ist ein Verweis auf Soulavie."),
    dict(n=6, titel="Siebenhundert Frauen mehr, Schwindsucht und die Pochknaben", pg="Lentin 1789, S. 14–15", lang="nhd",
         orig="Unter so günstigen Umständen der regelmäßigsten Witterung, dem Ueberfluß und Güte aller Nahrungsmittel, dem Glücke allgemeiner Zufriedenheit, genossen also die Einwohner des Oberharzes, jedes Alters und jedes Geschlechts überhaupt genommen, gänzliche Verschonung von herrschenden Krankheiten, vom Jahre 1777 an, bis zum Spätherbst 1781. […] Nach jährlicher genauer Volkszählung wird zu Clausthal immer eine Pluralität von 7 bis 800 Personen weiblichen Geschlechts gefunden.\n\nDie Schwindsucht und Epilepsie, waren sonst hier sehr häufig. Die Beschäftigung, Nahrungsmittel, und oft wiederkommende Hustens, gaben zu den Uranfängen der Schwindsucht, den Tuberkeln in der Lunge, Gelegenheit. Man mochte in vorigen Zeiten die Catarrhalhustens nicht für so wichtig angesehen, und vielleicht aus Sparsamkeit, Kranken dieser Art, die Hände nur mit Brustkuchen gefüllet haben; […]\n\nDie Epilepsie war sonst häufig unter den Puchknaben. Sie hatte ihren Ursprung, allergrößtentheils von Würmern, oder von zurückgetriebenem Ausschlag am Kopf.",
         en="Unter so günstigen Umständen, bei der regelmäßigsten Witterung, dem Überfluss und der Güte aller Nahrungsmittel und dem Glück allgemeiner Zufriedenheit, blieben die Einwohner des Oberharzes jeden Alters und Geschlechts also im Ganzen vom Jahr 1777 bis zum Spätherbst 1781 völlig von herrschenden Krankheiten verschont. […] Nach der jährlichen genauen Volkszählung findet man in Clausthal immer einen Überschuss von 700 bis 800 Personen weiblichen Geschlechts.\n\nSchwindsucht und Epilepsie waren hier früher sehr häufig. Die Beschäftigung, die Nahrung und oft wiederkehrender Husten gaben Anlass zu den Anfängen der Schwindsucht, den Tuberkeln in der Lunge. Man mag in früheren Zeiten den Katarrhhusten nicht für so wichtig gehalten und Kranken dieser Art, vielleicht aus Sparsamkeit, nur Brustkuchen in die Hand gegeben haben; […]\n\nDie Epilepsie war früher häufig unter den Pochknaben. Sie kam größtenteils von Würmern oder von zurückgetriebenem Ausschlag am Kopf.",
         note="Drei Sätze mit großem Gewicht. Erstens: 700 bis 800 Frauen mehr als Männer in einer Stadt von rund 7000 bis 8000 Einwohnern (Lentin nennt für Clausthal einen Anstieg von 7125 auf 7996 in neun Jahren, darunter ‚das zahlreiche Heer der Kinder‘, 1600, die noch keine Pocken gehabt hatten, S. 2). Den Grund nennt er nicht; dass Männer im Bergbau früher starben, liegt nahe, steht aber nicht da. Zweitens: ‚Die Beschäftigung‘ als erste Ursache der Schwindsucht, ohne dass er sagt, welche; Staub unter Tage ist nach der neueren Literatur die wahrscheinliche Deutung. Drittens: die Pochknaben, Kinder, die in den Pochwerken das Erz sortierten (Modul 2), und ihre Krämpfe, die Lentin mit Würmern und Kopfausschlag erklärt, also mit Armut und Schmutz. Er rühmt sich, die Schwindsucht auf ‚ein oder zwey‘ Kranke im Jahr verringert zu haben, durch Blasenpflaster; ausgelassen [‚…‘] sind die Rezepte und ein Satz über die Seltenheit der Geschlechtskrankheiten."),
]

ARBEIT = [
    dict(n=1, titel="Bleikolik und ‚Hüttenkatze‘, 1774", pg="Lentin 1774, S. 14", lang="nhd",
         orig="Die Bleicolic und die Hüttenkatze sind mit eben solchen Zufälle begleitet. Es gehen die Leibschmertzen in den Magenkrampf mit Schwindel, Ohnmacht, abmattenden Ohnmachtsschweiß, schwerem Othem, Hertzklopfen, Ueblichkeit und Erbrechen über, wodurch oft zähe, und wie Pech klebrige, grüne, oder sonst übelfarbige Unreinigkeiten ausgeworfen werden. Es pflegen zu diesen Leibschmertzen Zuckungen in Arm und Bein zu kommen, mit denen jene abwechseln. Oefter aber gehn die Schmertzen der Gedärme in Gliederschmertzen über, worauf entweder bald oder später eine Lähmung und endlich eine Schwindung erfolgt. Endlich kommen auch zuweilen allerhand langwierige Uebel dazu: […]",
         en="Die Bleikolik und die Hüttenkatze gehen mit ebensolchen Erscheinungen einher. Die Leibschmerzen gehen in Magenkrämpfe über, mit Schwindel, Ohnmacht, erschöpfendem Ohnmachtsschweiß, schwerem Atem, Herzklopfen, Übelkeit und Erbrechen, wobei oft zähe, pechartig klebrige, grüne oder sonst übel gefärbte Stoffe ausgeworfen werden. Zu diesen Leibschmerzen kommen gewöhnlich Zuckungen in Armen und Beinen, mit denen sie sich abwechseln. Öfter aber gehen die Darmschmerzen in Gliederschmerzen über, worauf früher oder später eine Lähmung und schließlich ein Muskelschwund folgt. Zuletzt kommen manchmal noch allerlei langwierige Übel hinzu: […]",
         note="Die ‚Hüttenkatze‘ ist die Bleivergiftung der Hüttenleute, die beim Schmelzen der bleihaltigen Silbererze Rauch und Staub einatmeten. Lentin erwähnt sie 1774, im Jahr seiner Clausthaler Anstellung, nur zum Vergleich: Sein Buch handelt hauptsächlich von der Mutterkornvergiftung (‚Gribbelkrankheit‘), die er zuvor im Herzogtum Lauenburg behandelt hatte. Dass er die Hüttenkatze ohne Erklärung nennt, zeigt, dass sie seinen Lesern bekannt war. Ausgelassen [‚…‘] sind die Folgekrankheiten (Blindheit, Gelbsucht, Wassersucht) mit Verweisen auf die Bleiärzte Stockhausen und Henkel."),
    dict(n=2, titel="Bäder aus dem Hochofen", pg="Lentin 1789, S. 65", lang="nhd",
         orig="Nachdem der Herr Berghauptmann von Reden den Entschluß gefasset, die, bisher am Harze üblich gewesene, Schmelzungsart der Silberhaltigen Erze dahin abzuändern, daß sie über hohe Oefen sollten geschmolzen werden, so bedurfte er, um dem Schwefel die Metalle zu entführen, eines Zuschlags von Eisen. Da sich nun Eisengranalien am bequemsten und gleichsten durch die Beschickung vertheilen ließen, so wurden auf mehreren Königl. und der Communioneisenhütte zu Gittelde zu diesem Behuf Eisengranalien, und zwar folgendermaßen gemacht. Aus einer verhältnismäßigen Vermischung verschiedener, in dasiger Gegend gebrochener, meist eine Thon- oder Kalcherde zum Grunde habender Eisensteine, wird mit Zusatz einer hinreichenden Menge Kohlen über dem hohen Ofen, vor dem Gebläse, Eisen geschmolzen, und täglich zweymal gestochen. Man öffnet nämlich unten, wo das geschmolzene Eisen sich gesammelt hat, den Heerd, und läßt es in Rillen, die von Stübbe vorbereitet sind, in fingerdicken Strängen, in einen länglich viereckigten hölzernen Kasten laufen, der in die Erde eingelassen und mit Wasser aus dem naheliegenden Teiche, angefüllet ist: dabey ist die Vorrichtung so gemacht, daß mittelst eines Gerennes (Lutte) frisch Wasser zu- und das heißgewordene aus dem Kasten abgelassen werden […]",
         en="Nachdem der Herr Berghauptmann von Reden den Entschluss gefasst hatte, die bisher im Harz übliche Schmelzart der silberhaltigen Erze dahin zu ändern, dass sie in Hochöfen geschmolzen werden sollten, brauchte er einen Zuschlag von Eisen, um dem Schwefel die Metalle zu entziehen. Da sich Eisengranalien am bequemsten und gleichmäßigsten in der Beschickung verteilen ließen, wurden auf mehreren königlichen Hütten und auf der Kommunion-Eisenhütte zu Gittelde dafür Eisengranalien gemacht, und zwar so: Aus einer passenden Mischung verschiedener, in der dortigen Gegend gebrochener Eisensteine, meist mit Ton- oder Kalkerde als Grundlage, wird mit Zusatz einer ausreichenden Menge Kohlen im Hochofen vor dem Gebläse Eisen geschmolzen und täglich zweimal abgestochen. Man öffnet nämlich unten den Herd, wo sich das geschmolzene Eisen gesammelt hat, und lässt es in Rinnen, die aus Kohlenlösche vorbereitet sind, in fingerdicken Strängen in einen länglich-viereckigen Holzkasten laufen, der in die Erde eingelassen und mit Wasser aus dem nahen Teich gefüllt ist; dabei ist alles so eingerichtet, dass über eine Rinne (Lutte) frisches Wasser zu- und das heiß gewordene aus dem Kasten abgelassen werden kann […]",
         note="Wie aus einer Hüttentechnik eine Heilbehandlung wurde: Das Wasser, in dem das glühende Eisen zu Körnern erstarrte, nutzte Lentin als Heilbad. Der Anlass ist Redens Umstellung auf Hochöfen, dieselbe ‚Hohe-Ofen-Arbeit‘, für die Dahme ihn 1777 in seiner Predigt lobte (Modul 7, Predigt [2]). Das Wasser kam ‚aus dem naheliegenden Teiche‘: auch hier hängt alles am Wasser. Ob die Eisenbäder medizinisch wirkten, können wir nicht beurteilen; Lentin berichtet nur Heilungen."),
    dict(n=3, titel="‚Lähmung nach der Hüttenkatze‘: auf herrschaftliche Kosten nach Gittelde", pg="Lentin 1789, S. 95", lang="nhd",
         orig="Lähmung nach der Hüttenkatze.\n\nDiese Lähmung trift vorzüglich die Arme und Hände, dabey die Finger krumm gebogen, und unbeweglich in der Hand liegen, und sich eine Schwindung der Muskeln einfindet. Sie widerstehet oft allen andern Mitteln. Nach dem Pyrmonter Bade sind dergleichen Kranke immer sehr gebessert wieder zurück gekommen. Ich schickte diesen, da es ausser der Jahrszeit war, ebenfalls auf herrschaftliche Kosten nach Gittelde, und er kam nach acht Tagen so weit gebessert zurück, daß er seine vorige Arbeit auf hiesiger Silberhütte wieder verrichten konnte.",
         en="Lähmung nach der Hüttenkatze.\n\nDiese Lähmung trifft vor allem Arme und Hände; dabei liegen die Finger krumm gebogen und unbeweglich in der Hand, und die Muskeln schwinden. Sie widersteht oft allen anderen Mitteln. Aus dem Pyrmonter Bad sind solche Kranke immer sehr gebessert zurückgekommen. Diesen schickte ich, weil es außerhalb der Badesaison war, ebenfalls auf herrschaftliche Kosten nach Gittelde, und er kam nach acht Tagen so weit gebessert zurück, dass er seine frühere Arbeit auf der hiesigen Silberhütte wieder verrichten konnte.",
         note="Die Fallgeschichte eines namenlosen Hüttenarbeiters: Fallhand und Muskelschwund durch Blei, Heilbad ‚auf herrschaftliche Kosten‘, nach acht Tagen zurück an die Arbeit auf der Silberhütte, also zurück an den Ort, an dem er sich vergiftet hatte. Lentin sieht darin einen Erfolg. Dass die Herrschaft die Kur bezahlte, zeigt eine Fürsorge, die zugleich die Arbeitskraft erhielt. Wie viele Hüttenleute gelähmt blieben, sagt Lentin nicht. Mit ‚Pyrmonter Bade‘ ist das Heilbad Pyrmont gemeint, wohin offenbar auch schon Kranke geschickt worden waren."),
    dict(n=4, titel="Ein Stück Berg auf den Rücken", pg="Lentin 1798, S. 153–154", lang="nhd",
         orig="Auch durch gar zu große Eiterung, verlohr ich einen rüstigen, jungen, und sonst ganz gesunden Bergmann, auf dessen ganzen Rücken, da er eben gebückt in der Grube gestanden hatte, ein großes Stück Berg herabgestürzt war. Der ganze Rücken gerieth in Eiterung, die ganze tunica adiposa ging verlohren, und ohnerachtet die nahrhaftesten Speisen, und die stärkendsten Mittel gegeben wurden, so verminderte sich doch das Eiter, die Muskeln des ganzen Rückens wurden trocken, und schwarz, und er starb abgezehrt. So wie durch die überaus große Eiterung alle Kräfte verschwanden, so verschwand auch alles Verdauungs- und Assimilationsvermögen. Die nahrhaftesten Speisen fielen bey ihm, als in einen leblosen Sack.",
         en="Durch allzu große Eiterung verlor ich auch einen rüstigen, jungen und sonst ganz gesunden Bergmann, dem, als er gerade gebückt in der Grube stand, ein großes Stück Gestein auf den ganzen Rücken gestürzt war. Der ganze Rücken geriet in Eiterung, das ganze Unterhautfettgewebe ging verloren, und obwohl man ihm die nahrhaftesten Speisen und die stärkendsten Mittel gab, nahm der Eiter zwar ab, die Muskeln des ganzen Rückens aber wurden trocken und schwarz, und er starb abgezehrt. So wie durch die übergroße Eiterung alle Kräfte schwanden, schwand auch jedes Vermögen zu verdauen und aufzunehmen. Die nahrhaftesten Speisen fielen bei ihm wie in einen leblosen Sack.",
         note="Der einzige tödliche Grubenunfall, den wir in Lentins Schriften gefunden haben. ‚Berg‘ heißt im Bergbau das taube Gestein. Der Mann bleibt namenlos, sein Tod ist ein Beispiel unter der Überschrift ‚Marasmus ulcerosus‘, Auszehrung durch Eiterung. Wann und auf welcher Grube das geschah, sagt Lentin nicht; der Band erschien 1798, Jahre nach seinem Weggang aus Clausthal; dass der Fall von dort stammt, schließen wir aus dem Wort ‚Grube‘. Der Text beschreibt die Wunde genau; wir geben ihn ungekürzt, weil er den Tod eines Arbeiters nicht ausstellt, sondern ärztlich festhält."),
    dict(n=5, titel="‚Fallen, Stoßen, Quetschen‘: Arnika am Harz", pg="Lentin 1808, S. 82–83", lang="nhd",
         orig="Am Harze, wo unter den Bergleuten Beschädigungen aller Art durch Fallen, Stoßen, Quetschen mehr als anderwärts vorkommen, habe ich gar vielfältige Gelegenheit gehabt die gute Wirkung dieses Krauts zu erfahren.\n\nAnmerk. Auch mir hat sich die Arnica bey innern und äußern Blutunterlaufungen öfter bewährt. So gab ich sie noch ganz kürzlich dem Kammerdiener der Frau Oberhofmarschallin von B. der bey der Plünderung, die unser Land leider von den Franzosen erfahren mußte!!! zur Erde geworfen und mit Füßen getreten war, der davon Fieber, Brustbeklemmung und kurzen Husten behalten hatte, mit dem vortreflichsten Erfolg.",
         en="Im Harz, wo unter den Bergleuten Verletzungen aller Art durch Fallen, Stoßen und Quetschen häufiger als anderswo vorkommen, hatte ich sehr oft Gelegenheit, die gute Wirkung dieses Krauts zu erfahren.\n\nAnmerkung. Auch mir hat sich die Arnika bei inneren und äußeren Blutergüssen öfter bewährt. So gab ich sie noch ganz kürzlich mit dem trefflichsten Erfolg dem Kammerdiener der Frau Oberhofmarschallin von B., der bei der Plünderung, die unser Land leider von den Franzosen erleiden musste, zu Boden geworfen und mit Füßen getreten worden war und davon Fieber, Brustbeklemmung und kurzen Husten zurückbehalten hatte.",
         note="Ein Satz genügt Lentin für den Alltag unter Tage: ‚Beschädigungen aller Art durch Fallen, Stoßen, Quetschen‘, häufiger als anderswo. Zahlen nennt er nicht. Die Anmerkung stammt nicht von Lentin (gestorben 1804 nach der neueren Literatur), sondern vom Herausgeber Wilhelm Sachse, Hofmedikus in Mecklenburg-Schwerin, und betrifft die französische Besetzung Mecklenburgs nach 1806 (nach der neueren Literatur). Wir geben sie mit, weil sie die Gewalt der anderen Seite dieser Jahre nennt, ausdrücklich: ein Diener, zu Boden geworfen und getreten."),
    dict(n=6, titel="‚Über 400 Menschen mehr‘, und freie Arznei", pg="Lentin 1808, S. 65–66", lang="nhd",
         orig="Nach diesem Grundsatze gelang es mir bey meinem zehnjährigen Aufenthalte am Harze, daß ich, nach sechszehn erlebten Epidemien mancherley Art, bey meinem Abzuge über 400 Menschen mehr hinterließ, als ich erhalten hatte. Allein die mehresten Kranken erhielten freyen Arzneygebrauch, der ihnen ein für allemal zukam, ohne nöthig zu haben diese Wohlthat bey jeder Bedürfniß von neuem zu erbetteln. […]\n\nIch erinnere mich hiebey eines Bergmanns, dem ich gegen Ausschlag am Kopfe und Drüsen am Halse die Werlhof'sche blutreinigende Lattwerge zu vier Unzen, mit zwey Quentchen Quecksilber-Mohr vermischt, täglich zweymal zu einem Theelöffel voll verordnet hatte. Dieser Mann aber aß den ganzen Vorrath in einem Tage aus. Hierauf entstand nach wenig Tagen eine außerordentlich starke Speichelung und Entzündung des Halses, die sich mit keinem Mittel bändigen ließ und den Kranken tödtete.",
         en="Nach diesem Grundsatz gelang es mir in meinen zehn Jahren am Harz, dass ich nach sechzehn erlebten Epidemien verschiedener Art bei meinem Weggang über 400 Menschen mehr zurückließ, als ich vorgefunden hatte. Allerdings bekamen die meisten Kranken freie Arznei, die ihnen ein für alle Mal zustand, ohne dass sie diese Wohltat bei jedem Bedarf von Neuem erbetteln mussten. […]\n\nIch erinnere mich dabei an einen Bergmann, dem ich gegen Ausschlag am Kopf und Drüsen am Hals die Werlhof'sche blutreinigende Latwerge, vier Unzen, mit zwei Quentchen Quecksilbermohr vermischt, täglich zweimal einen Teelöffel voll verordnet hatte. Dieser Mann aber aß den ganzen Vorrat an einem Tag auf. Darauf entstand nach wenigen Tagen ein außerordentlich starker Speichelfluss und eine Entzündung des Halses, die sich mit keinem Mittel bändigen ließ und den Kranken tötete.",
         note="Zwei Seiten der ärztlichen Bilanz, eine Seite auseinander. Lentin rechnet sich zu, die Einwohnerzahl um über 400 erhöht zu haben, und nennt eine Bedingung, die er für wesentlich hält: Die meisten Kranken bekamen ‚freyen Arzneygebrauch‘, ein Recht, kein Almosen. Nach der neueren Literatur gehörte das zu den Leistungen der Knappschaftskasse für Bergleute; Lentin sagt nicht, wer zahlte. Dann der Tod eines Bergmanns durch ein Quecksilbermittel, das der Arzt verordnet und der Kranke falsch eingenommen hatte. Lentin erzählt den Fall, um vor dem Mittel zu warnen, nicht um sich zu entlasten. Ausgelassen [‚…‘] ist ein Absatz über die ‚Merkurial-Bräune‘."),
]

doc = {
    "id": "arzt",
    "titel": "Der Bergarzt",
    "autor": "Lebrecht Friedrich Benjamin Lentin, Bergmedicus und Stadtphysicus zu Clausthal",
    "jahr": "1774–1808",
    "sprache": "de",
    "orig_sprache": "nhd",
    "pg_label": "",
    "quelle": "L. F. B. Lentin, Beobachtungen einiger Krankheiten (Göttingen: Vandenhoeck 1774), S. 14 (Internet Archive 11269090bsb); ders., Beyträge zur ausübenden Arzneywissenschaft [Bd. 1] (Leipzig: Crusius 1789), S. 4–15, 65, 95 (Internet Archive 11107337bsb); ders., Beyträge [...], Bd. 2 (1798), S. 153–154 (Internet Archive 11741619bsb); ders., Beyträge [...], Supplementband, hg. von W. Sachse (Leipzig: Crusius 1808), S. 65–66, 82–83 (Internet Archive 11741621bsb).",
    "hinweis": "Lentin war nach eigener Angabe zehn Jahre ‚am Harze‘; das Buch von 1774 unterschrieb er in Clausthal, die Beyträge von 1789 in Lüneburg. Über Clausthal schrieb er vor allem im Rückblick. Die Drucke von 1774 und 1789 in Fraktur, die von 1798 und 1808 in Antiqua, alle am Seitenbild gelesen und in ihrer Schreibung wiedergegeben; ‚ꝛc.‘ steht für ‚etc.‘. Die Anmerkung in Arbeit [5] stammt vom Herausgeber Sachse. Auslassungen stehen in eckigen Klammern.",
    "sections": [
        {"id": "stadt", "autor": "Lentin 1789, über Clausthal 1777–1781", "titel": "Eine Stadt auf dem Gebirge", "zk": "Stadt",
         "plates": ["lentin1789_titel", "lentin1789_s13"],
         "viz": "arzt",
         "blurb": "Der Stadtarzt beobachtet Clausthal wie ein Klima: Schnee bis in den Mai, ein Ostwind, der dreißig, vierzig Kranke bringt, frisches Gemüse erst im Juni, und die Heidelbeerzeit als gesündeste des Jahres. Er sieht die Armut, ‚Milch ist schon nicht für alle‘, und die Frauen, die Obst, Heu und Bier auf dem Rücken ins Gebirge tragen und unterwegs gebären. In der Stadt leben siebenhundert Frauen mehr als Männer.",
         "units": STADT},
        {"id": "arbeit", "autor": "Lentin 1774, 1789, 1798, 1808", "titel": "Was die Arbeit dem Körper tut", "zk": "Arbeit",
         "plates": ["lentin1774_titel", "lentin1789_s95"],
         "blurb": "Die ‚Hüttenkatze‘, die Bleivergiftung der Hüttenleute, lähmt die Hände; der Bergarzt schickt einen Kranken auf herrschaftliche Kosten ins Eisenbad und meldet stolz, er habe wieder auf der Silberhütte arbeiten können. Ein junger Bergmann stirbt, nachdem ihm ‚ein großes Stück Berg‘ auf den Rücken gefallen ist. ‚Fallen, Stoßen, Quetschen‘ seien am Harz häufiger als anderswo. Und die Kranken hatten freie Arznei, als Recht, nicht als Almosen.",
         "units": ARBEIT},
    ],
}

OUT.write_text(json.dumps(doc, ensure_ascii=False, indent=1), encoding="utf-8")
print("arzt.json:", sum(len(s["units"]) for s in doc["sections"]), "Einheiten")
