"""Modul 2: Das Bergamt. Löhneyß' Bericht vom Bergwerck, 1617. Schreibt data/bergamt.json.

Quelle, am Seitenbild gelesen: G. E. Löhneyß, Bericht vom Bergkwerck (Zellerfeld 1617),
Erstausgabe, Exemplar der ETH-Bibliothek Zürich (Rar 1553), e-rara, doi:10.3931/e-rara-15531
(Public Domain Mark). Seiten 191–235 entsprechen den Bildern 272–316 (Seite = Bild − 81).
"""
import json
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "data" / "bergamt.json"

VORREDE = [
    dict(n=1, titel="Metalle ins Erdreich gelegt, ‚im schweiß jhres Angesichts‘ zu gewinnen", pg="Widmung, Bl. [2r]", lang="fnhd",
         orig="Dem Durchläuchtigen/ Hochgebornen Fürsten unnd Herren/ Herrn Friederich Ulrich/ Hertzog zu Braunschweig und Lüneburgk ec. Meinem gnädigen Fürsten und Herren.\n\nDurchläuchtiger/ Hochgeborner Fürst/ E. F. Gn. sind meine Unterthänige gehorsame und bereitwillige dienste/ zu jederzeit mit trewem vleiß zuvorn/ Gnädiger Fürst und Herr/ Nach deme GOtt der Allmächtige den ersten Menschen auff Erden geschaffen/ hat er jhm zuvor durch seine unaußsprechliche Weißheit und güte/ zu seiner leiblichen erhaltung/ notturfft und gebrauch/ nicht allein allerley lebendige Thiere/ Fisch/ Vogel/ Bäume/ Kräuter/ Korn/ Laub und Graß verordnet/ wachsen lassen und jhm unterthänig gemacht/ sondern auch allerhandt jrrdische Cörper von mannicherley Metallen/ Bergksäfften/ und was des dinges mehr ist/ ins Erdtreich gelegt/ und in die Wasser verborgen/ die der Mensch unnd alle seine Nachkömlinge zu vielen nothwendigen Sachen/ im schweiß jhres Angesichts/ heraus gewinnen/ zu nutz machen und gebrauchen mag.",
         en="Dem durchlauchtigen, hochgeborenen Fürsten und Herrn, Herrn Friedrich Ulrich, Herzog zu Braunschweig und Lüneburg usw., meinem gnädigen Fürsten und Herrn.\n\nDurchlauchtiger, hochgeborener Fürst, Euer Fürstlichen Gnaden entbiete ich zuvor meine untertänigen, gehorsamen und bereitwilligen Dienste, jederzeit mit treuem Fleiß. Gnädiger Fürst und Herr: Nachdem Gott der Allmächtige den ersten Menschen auf Erden geschaffen hatte, hat er ihm zuvor durch seine unaussprechliche Weisheit und Güte zu seiner leiblichen Erhaltung, seinem Bedarf und Gebrauch nicht allein allerlei lebendige Tiere, Fische, Vögel, Bäume, Kräuter, Korn, Laub und Gras verordnet, wachsen lassen und ihm untertan gemacht, sondern auch allerhand irdische Körper von mancherlei Metallen, Bergsäften und was dergleichen mehr ist, ins Erdreich gelegt und in den Wassern verborgen, die der Mensch und alle seine Nachkommen zu vielen notwendigen Dingen im Schweiß ihres Angesichts herausgewinnen, nutzbar machen und gebrauchen sollen.",
         note="Georg Engelhard Löhneyß (1552–1622 nach dem Katalog der ETH-Bibliothek) nennt sich auf dem Titel ‚Fürstlichen Braunschweigischen Bergkhauptman‘ (Tafel). Er widmet das Buch dem regierenden Herzog Friedrich Ulrich von Braunschweig-Wolfenbüttel. ‚Bergsäfte‘ sind mineralische Lösungen und Salze. Der Bergbau wird aus Genesis 1 und 3 begründet: Gott hat die Metalle gegeben, und der Mensch muss sie ‚im Schweiß seines Angesichts‘ heben. Die Widmung ist undatiert; der Druck trägt das Jahr 1617."),
    dict(n=2, titel="Die Schreiber ‚ad Theoricam‘, und die Gruben, die ‚zu sumpff getrieben‘ werden", pg="Vorrede, Bl. [3r]", lang="fnhd",
         orig="Neben dem/ das gemelte Scribenten allein ad Theoricam gesehen/ und die Sachen im Werck selbst nicht erfahren/ verstanden/ geübet noch gebrauchet/ sondern jhre mühsehliche Werck von etlichen denen sie zu viel gegläubt/ auff blossen bericht zusammen getragen/ Dahero dann ein anfahender Bergkman/ oder die im Fewr arbeiten/ und sonst deren Sachen keinen grundt und rechten bericht haben/ nichts fruchtbarliches daraus lernen/ sondern vielmehr damit jrre gemacht werden.\n\nEs bezeugets die tägliche erfahrung/ und zwar der Augenschein selbst/ das durch gut regiment/ verständige Bergkleute/ gute anordnung und vleißige auffsicht/ geringe Bergkwerck da Ertz bricht/ wol zuerheben und in guten wolstand und uberschuß zu bringen seyn/ und dargegen durch unverstandt/ unordnung und hinläßigkeit der Bergkbeampten leichtlich herunter und zu sumpff getrieben wird/ wie der Exempel genugsam für Augen.\n\nIst derhalben bey solchen Leuten gute anordnung/ auffsicht und straff hoch von nöhten/ wil man anders das es richtig und wol zugehen soll/ sintemahl das Zellerfeldische/ Wildemännische/ Lautenthalische und Rammelßbergische Ertz/ in grosser menge herauß gefordert wird/ Derhalben sie auch mit gewalt müssen getrieben werden/ welches fast alles eine grobe Roßarbeit ist/ wie es dann zu solcher menge der Ertz/ die Notturfft erfordert.",
         en="Abgesehen davon, dass die genannten Schreiber nur auf die Theorie gesehen und die Dinge im Werk selbst nicht erfahren, verstanden, geübt und gebraucht, sondern ihre mühseligen Werke aus dem bloßen Bericht einiger Leute zusammengetragen haben, denen sie zu viel geglaubt haben: Daher kann ein angehender Bergmann oder wer im Feuer arbeitet und sonst keinen Grund und rechten Bericht dieser Dinge hat, nichts Fruchtbares daraus lernen, sondern wird vielmehr damit irregemacht.\n\nDie tägliche Erfahrung bezeugt es, ja der Augenschein selbst: Durch gutes Regiment, verständige Bergleute, gute Anordnung und fleißige Aufsicht sind auch geringe Bergwerke, in denen Erz bricht, wohl aufzurichten und in guten Wohlstand und Überschuss zu bringen; und umgekehrt werden sie durch Unverstand, Unordnung und Nachlässigkeit der Bergbeamten leicht heruntergewirtschaftet und zu Sumpf getrieben, wofür es Beispiele genug vor Augen gibt.\n\nDarum sind bei solchen Leuten gute Anordnung, Aufsicht und Strafe sehr nötig, wenn es richtig und gut zugehen soll, zumal das Erz von Zellerfeld, Wildemann, Lautenthal und vom Rammelsberg in großer Menge herausgefördert wird; deshalb müssen die Gruben auch mit Gewalt betrieben werden, was fast alles grobe Rossarbeit ist, wie es eine solche Menge Erz notwendig erfordert.",
         note="‚Ad Theoricam‘: Löhneyß meint die gelehrten Bergbücher seiner Vorgänger, nach der neueren Literatur vor allem Agricola (1556) und Ercker (1574), die er hier nicht nennt. Er schreibt als Praktiker gegen die Gelehrten, ein Gegensatz, der in diesem Apparat bei Leibniz wiederkehrt. ‚Zu Sumpf treiben‘: Der Sumpf ist der tiefste Teil der Grube, in dem sich das Wasser sammelt; eine Grube, die ‚zu Sumpf getrieben‘ wird, säuft ab. ‚Grobe Rossarbeit‘ meint die Göpel, in denen Pferde Erz und Wasser hoben. Wildemann und Lautenthal sind Bergstädte neben Zellerfeld; der Rammelsberg liegt bei Goslar."),
    dict(n=3, titel="Warum er schrieb: Unordnung und Missbräuche", pg="Vorrede, Bl. [3r–3v]", lang="fnhd",
         orig="Darumb E. F. Gn. Bergkwerck auch mit so viel Amptspersonen muß bestellet unnd regieret werden/ da dann ein jeder in seinem Ampt und Dienst genugsam zuverrichten hat/ und ich für mein Person/ halte es für eine grosse Wollthat Gottes/ wann ein Bergkwerck mit verständigen/ trewen ehrlichen Amptspersonen/ als Bergkmeister/ Geschworne/ Steiger/ Schichtmeister und schmeltzern ec. versehen und bestellet ist/ die da wissen wie sie Schürffen/ Schächte sincken/ Stollen und Querschläg treiben/ jhre Grubengebewde recht unnd wol anstellen/ und wissen/ was ein jedes Ertz im Schmeltzen für Zuschläg haben muß/ sintemahl alles wie gemeldt/ negst GOtt an guter anordnung und vleißiger auffsicht gelegen ist/ damit künfftig nicht allein der Landes Fürst/ sondern auch die bawenden Gewercken/ dessen zugeniessen und sich zuerfrewen haben.\n\nWeil ich dann gesehen/ das viel unordnung und mißbräuche in E. F. Gn. Bergkwercken eingerissen/ als habe ich zu forthsetzung desselben/ und denen die sich davon ernehren und erhalten/ diesen Tractat zu Ehren/ Nutz und gutem/ zu Pappier bracht/ Nemblich wie man die Ertz und Metallen erbawen/ dieselben Scheiden/ Puchen/ Waschen/ Röste/ Schmeltzen/ unnd was dergleichen Arbeiten mehr sind und darzu gehören [...]",
         en="Darum muss das Bergwerk Euer Fürstlichen Gnaden auch mit so vielen Amtspersonen besetzt und regiert werden, von denen jeder in seinem Amt und Dienst genug zu tun hat; und ich für meine Person halte es für eine große Wohltat Gottes, wenn ein Bergwerk mit verständigen, treuen, ehrlichen Amtspersonen versehen und besetzt ist, als Bergmeistern, Geschworenen, Steigern, Schichtmeistern und Schmelzern usw., die wissen, wie man schürft, Schächte abteuft, Stollen und Querschläge treibt und ihre Grubengebäude recht und gut anlegt, und die wissen, welche Zuschläge jedes Erz beim Schmelzen braucht; denn alles liegt, wie gesagt, nächst Gott an guter Anordnung und fleißiger Aufsicht, damit künftig nicht allein der Landesfürst, sondern auch die bauenden Gewerken es genießen und sich daran freuen können.\n\nWeil ich nun gesehen habe, dass in den Bergwerken Euer Fürstlichen Gnaden viel Unordnung und Missbräuche eingerissen sind, habe ich zu ihrer Fortsetzung und denen zu Ehren, Nutzen und Gutem, die sich davon ernähren und erhalten, diesen Traktat zu Papier gebracht: nämlich wie man Erze und Metalle gewinnt, sie scheidet, pocht, wäscht, röstet, schmilzt, und was es an derartigen Arbeiten mehr gibt und dazugehört [...]",
         note="Das Programm des Buches in zwei Sätzen: Ein Bergwerk wird durch seine Ämter regiert, und es ist in Unordnung geraten. Wer die ‚Missbräuche‘ waren, sagt die Vorrede nicht; die Bergordnung im zweiten Teil des Buches nennt sie (Ämter [1]). Zuschläge sind Zusätze wie Kalk oder Eisenerz, die das Schmelzen erleichtern. Die Gewerken sind die Anteilseigner der Gruben (Modul ‚Die Bergfreiheiten‘)."),
]

AEMTER = [
    dict(n=1, titel="Keine ‚versoffenen Buben‘; ‚kein Emptlein so klein‘", pg="S. 191", lang="fnhd",
         orig="Folget nun die Bergkordenung.\n\nWie und welcher gestalt ein Bergkampt mit düchtigen/ Qualificirten Personen zubestellen/ unnd was eines jeden Ampt/ Eydt/ Pflicht und befehlich vermag und mit sich bringet/ ist hiernach ördent: und unterschiedtlich verzeichnet/ und sollen die jenigen/ so nachfolgende Empter und dienste zu bestellen macht haben/ wol zusehen/ was sie für Leute darzu nehmen/ Ob sie auch Verstendig/ getrew/ erfahren und geschickt seyn/ damit ein jeder dienst der gebür nach/ mit ehrlichen/ düchtigen/ trewen Leuten bestellet werde/ und nicht umb eigenes genieß oder finantzen willen/ anrüchtige/ eigennützige/ geitzige/ betriegerische/ versoffene Buben darzu bestellen und befordern/ und das ein jeder/ der sich zu diesen diensten wil gebrauchen lassen/ trew und vleissig in seinem dienst erfunden werde/ dann es gehet bißweilen doch zu/ das es wol besser döchte/ und man zeucht offtmahls umb gunst/ freundtschafft oder finantzen willen die herfür/ die kein Verstandt hievon haben/ unnd wol jhr lebtag nie darbey gewesen sind.\n\nDann es gehöret viel glaubens darzu/ wo man einem ungezalt Gelt/ reich Ertz/ und ungewogen Silberkuchen vertrawen solle/ So ist kein Emptlein so klein/ söhlet es nicht/ so flecket es doch/ So können die Bawren auff Holtschuch gehen/ wann schon die Herren regnen lassen/ Und wer hütet des Hüters/ Die Weltkinder sind geschwinde/ unnd auff alle Tück abgerichtet [...] sintemahl die ördentliche besoldung unnd zugelassene einkommen zimblich gering/ dagegen die Außgabe/ Panckethieren und Zehrung ohne maß und uberschwencklich ist/ welches den Gewercken ein starck nachdencken machet/ wie es doch möge zugehen.",
         en="Es folgt nun die Bergordnung.\n\nWie und auf welche Weise ein Bergamt mit tüchtigen, geeigneten Personen zu besetzen ist und was das Amt, der Eid, die Pflicht und der Auftrag eines jeden umfasst und mit sich bringt, ist hiernach geordnet und einzeln aufgezeichnet. Und die, die die folgenden Ämter und Dienste zu besetzen haben, sollen gut zusehen, was sie für Leute dazu nehmen, ob sie auch verständig, treu, erfahren und geschickt sind, damit jeder Dienst gebührend mit ehrlichen, tüchtigen, treuen Leuten besetzt wird, und nicht um eigenen Vorteils oder Geldes willen anrüchtige, eigennützige, geizige, betrügerische, versoffene Buben dazu bestellen und befördern; und jeder, der sich zu diesen Diensten gebrauchen lassen will, soll treu und fleißig in seinem Dienst befunden werden. Denn es geht bisweilen doch so zu, dass es wohl besser taugte: Man zieht oft um Gunst, Freundschaft oder Geldes willen die hervor, die keinen Verstand davon haben und wohl ihr Lebtag nie dabei gewesen sind.\n\nDenn es gehört viel Vertrauen dazu, wenn man einem ungezähltes Geld, reiches Erz und ungewogene Silberkuchen anvertrauen soll. Kein Ämtlein ist so klein: Besohlt es nicht, so flickt es doch. Die Bauern können auf Holzschuhen gehen, auch wenn die Herren es regnen lassen. Und wer hütet den Hüter? Die Weltkinder sind geschwind und auf alle Tücke abgerichtet [...]; zumal die ordentliche Besoldung und das zugelassene Einkommen ziemlich gering, dagegen die Ausgaben, das Bankettieren und Zechen maßlos und überschwänglich sind, was den Gewerken sehr zu denken gibt, wie das wohl zugehen mag.",
         note="Der Eingang der Bergordnung, des zweiten großen Teils des Buches. ‚Finantzen‘ heißt hier noch ‚Geldgeschäfte, Bestechung‘. ‚Ist kein Emptlein so klein, söhlet es nicht, so flecket es doch‘: ein Sprichwort, nach dem auch das kleinste Amt seinem Inhaber etwas einbringt, und wenn nicht Sohlen, dann Flicken; übertragen ist es wörtlich. ‚Die Bauern können auf Holzschuhen gehen, wenn die Herren regnen lassen‘ ist dunkel, wohl: Die Kleinen wissen sich zu helfen, was die Großen auch tun. ‚Wer hütet den Hüter?‘ ist Juvenals ‚quis custodiet ipsos custodes‘. Ausgelassen sind weitere Sprichwörter über Betrug, die den Gedanken nur ausschmücken."),
    dict(n=2, titel="Der Eid: ‚mit allen Teuffeln verbant und verflucht‘", pg="S. 191–192", lang="fnhd",
         orig="Wil derohalben alle die/ so mit der Obrigkeit unnd Gewercken Gelt/ Ertz und Silber/ als vertrawtem Gut umbgehen/ und bey denen es sequestrirt und beygelegt wird/ hiemit erinnert haben/ das ein jeder/ der einen Eydt thut/ GOtt uber seine arme Seele zum Zeugen anrüfft/ nemblich/ wo ferne er wissentlich oder gefehrlicher weise seinem Herren und Gewercken das aller geringste veruntrawe/ oder an seinen nutz und frommen wende/ das GOtt deß solle Zeuge und Straffer seyn [...] wan einer seinen Eydt auff billige erforderung der Obrigkeit/ mit dieser Clausul beschleust:\n\nIch schwere bey dem Allmächtigen GOTT/ der aller Menschen Hertzen kennet/ und in alle winckel siehet/ und dem niemandt die Augen verdecken kan/ Das ich meiner gnädigsten Obrigkeit und den gemeinen Gewercken wil getrew seyn/ und wil jhren Schaden/ so viel mir Menschlich und müglich/ mit höchstem vleiß und sorge vorkommen/ unnd jhren frommen und bestes getrewlich fordern helffen/ als mir GOtt helffe und sein Heiliges Wort. Daß ist/ so ich diß nicht thun werde/ so sol mir GOtt nicht helffen/ ich wil mich auch meines theils am Euangelio und Reich Gottes wissentlich verzeihen/ und ewiglich mit allen Teuffeln verbant und verflucht seyn.\n\nDiß sind warlich harte und schreckliche Wort/ darüber einem die Haar solten zu Bergen stehen. Weil aber die Weltkinder leichtlich schweren/ und jhrer viel nicht bedencken was sie schweren/ auch manicher spricht: Es ist besser Eyde schweren/ dann Rüben graben/ Damit sich aber niemandts zu entschüldigen habe/ wann er an jenem Tage wieder in Anschnit gehet/ unnd eine klare richtige Rechnung von seiner verwaltung und diensten/ für JEsu Christo und aller Welt augen wird thun müssen.",
         en="Ich will darum alle, die mit dem Geld, dem Erz und dem Silber der Obrigkeit und der Gewerken als anvertrautem Gut umgehen und bei denen es verwahrt und hinterlegt wird, hiermit daran erinnert haben, dass jeder, der einen Eid leistet, Gott über seine arme Seele zum Zeugen anruft: nämlich, wenn er wissentlich oder auf gefährliche Weise seinem Herrn und den Gewerken auch das Allergeringste veruntreut oder zu seinem eigenen Nutzen und Vorteil verwendet, dass Gott dessen Zeuge und Strafer sein soll [...], wenn einer seinen Eid auf billiges Verlangen der Obrigkeit mit dieser Klausel schließt:\n\nIch schwöre bei dem allmächtigen Gott, der aller Menschen Herzen kennt und in alle Winkel sieht und dem niemand die Augen verdecken kann, dass ich meiner gnädigsten Obrigkeit und den gemeinen Gewerken treu sein und ihren Schaden, soweit es mir menschlich und möglich ist, mit höchstem Fleiß und Sorge verhüten und ihren Nutzen und ihr Bestes treulich fördern helfen will, so wahr mir Gott helfe und sein heiliges Wort. Das heißt: Wenn ich dies nicht tun werde, so soll mir Gott nicht helfen; ich will mich auch meinerseits wissentlich vom Evangelium und Reich Gottes lossagen und ewig mit allen Teufeln verbannt und verflucht sein.\n\nDas sind wahrlich harte und schreckliche Worte, über die einem die Haare zu Berge stehen sollten. Weil aber die Weltkinder leicht schwören und viele von ihnen nicht bedenken, was sie schwören, und mancher spricht: Es ist besser, Eide zu schwören, als Rüben zu graben, so soll sich niemand entschuldigen können, wenn er an jenem Tage wieder ‚in den Anschnitt geht‘ und vor Jesus Christus und den Augen aller Welt eine klare, richtige Rechnung über seine Verwaltung und seine Dienste ablegen muss.",
         note="Der Eid aller, die mit Geld, Erz und Silber umgehen. ‚Sequestrirt‘: in Verwahrung gegeben. Das Bild am Ende stammt aus dem Bergbau selbst: Der ‚Anschnitt‘ ist die wöchentliche Abrechnung am Samstag, bei der Schichtmeister vor Bergmeister und Geschworenen Rechnung legen (Ämter [6]); Löhneyß macht daraus das Jüngste Gericht. ‚Besser Eide schwören als Rüben graben‘: ein Spottwort über Leute, die ein Amt dem Feldbau vorziehen."),
    dict(n=3, titel="Die Ämter, vom Berghauptmann bis zum Häusling", pg="S. 193–194", lang="fnhd",
         orig="Der 1. Articul. Waß für Amptleute und Diener auff den Bergkwercken von nöhten seyn/ und wie sich ein jeder in seinem Ampt und befehlich verhalten sol.\n\nAuff daß dem gemeinen Bergkwerck getrewlich unnd wol vorgestanden/ diese und andere unsere publicirte Ordnung/ in allen Articuln stätt und fest gehalten/ das Unrecht gestraffet/ hergegen aber gemeiner Nutz befördert/ unnd jedermänniglichen bemelter Bergkwercke gebrauchen/ in gebürlichen Schutz/ Friede/ Recht und Gerechtigkeit erhalten werde/ Haben Wir unsere Bergkwercke mit hernach benanten Bergkverständigen Amptleuten unnd Dienern versehen und verordnet [...] alß nemblich:\n\n1. Den Bergk-Hauptman an des Fürsten statt. 2. Zehendtner. 3. Zehendtgegenschreiber. 4. Bergkschreiber und Bergkgegenschreiber.\nItem die/ so die Grubengebäwde verwalten/ als: 1. Ober Bergkmeister. 2. Bergkmeister. 3. Geschworne. 4. Einfahrer. 5. Steiger. 6. Schichtmeister. 7. Marscheider.\nIn Puchwercken. 1. Ober Puchsteiger. 2. Puchsteiger.\nDeßgleichen auch die/ so das Hüttenwerck und Schmeltzen verwalten/ als nemblich: 1. Hütten Reuter. 2. Hüttenschreiber. 3. Geschworne Probierer. 4. Silberbrenner. 5. Hüttenmeister. 6. Schmeltzer. 7. Abtreiber. 8. Vorläuffer. 9. Rostbrenner. 10. Hüttenwächter und Kollenmesser. 11. Eltesten und Jüngsten der Knapschafft. 12. Kuxkräntzler. 13. Einwohner und Häußling.\n\nVon der Bergkamptleute unnd Diener Eydt und Pflicht. Diese jetztbenante/ gesetzte und geordnete Amptleute und Diener/ deßgleichen alle andere/ sollen Uns und unsern Erben und Nachkommen/ gehorsamb/ gewehr/ und getrew zu seyn/ gebürliche Eydeßpflicht leisten [...]",
         en="Der 1. Artikel. Was für Amtleute und Diener auf den Bergwerken nötig sind und wie sich jeder in seinem Amt und Auftrag verhalten soll.\n\nDamit dem gemeinen Bergwerk treu und gut vorgestanden, diese und unsere anderen öffentlich gemachten Ordnungen in allen Artikeln stets und fest gehalten, das Unrecht bestraft, dagegen der gemeine Nutzen gefördert und jedermann, der die Bergwerke nutzt, in gebührlichem Schutz, Frieden, Recht und Gerechtigkeit erhalten werde, haben wir unsere Bergwerke mit den folgenden bergverständigen Amtleuten und Dienern versehen und bestellt [...], nämlich:\n\n1. den Berghauptmann an Stelle des Fürsten. 2. Zehntner. 3. Zehntgegenschreiber. 4. Bergschreiber und Berggegenschreiber.\nFerner die, die die Grubengebäude verwalten: 1. Oberbergmeister. 2. Bergmeister. 3. Geschworene. 4. Einfahrer. 5. Steiger. 6. Schichtmeister. 7. Markscheider.\nIn den Pochwerken: 1. Oberpochsteiger. 2. Pochsteiger.\nEbenso die, die das Hüttenwerk und das Schmelzen verwalten: 1. Hüttenreiter. 2. Hüttenschreiber. 3. geschworene Probierer. 4. Silberbrenner. 5. Hüttenmeister. 6. Schmelzer. 7. Abtreiber. 8. Vorläufer. 9. Röstbrenner. 10. Hüttenwächter und Kohlenmesser. 11. die Ältesten und Jüngsten der Knappschaft. 12. Kuxkränzler. 13. Einwohner und Häuslinge.\n\nVom Eid und der Pflicht der Bergamtleute und Diener: Diese jetzt genannten, eingesetzten und bestellten Amtleute und Diener, ebenso alle anderen, sollen uns, unseren Erben und Nachkommen den gebührenden Eid leisten, gehorsam, gewärtig und treu zu sein [...]",
         note="Die Liste ist das Gerüst dieses Moduls und des Begleitspiels. Es spricht der Landesfürst (‚Wir‘): Die Bergordnung ist eine fürstliche Verordnung, die Löhneyß abdruckt. Der Zehntner nimmt den Zehnten und das Silber ein; der Schichtmeister führt für die Gewerken die Rechnung einer Grube; der Markscheider vermisst die Gruben; der Probierer prüft den Gehalt der Erze; der Abtreiber scheidet das Silber aus dem Blei; der Kuxkränzler handelt mit Grubenanteilen. Die Bergleute selbst, die Hauer, Haspelknechte und Pochjungen, erscheinen nicht als Ämter, sondern nur als ‚Älteste und Jüngste der Knappschaft‘, ihre gewählten Vertreter, und als ‚Einwohner und Häuslinge‘ am Ende."),
    dict(n=4, titel="Löhne nach der Tafel; ‚an Leib und Gut gestraffet‘", pg="S. 194", lang="fnhd",
         orig="Von der Bergkamptleute Besoldung und gebür.\n\nDamit die Gewercken oder andere/ von dem Bergkmeister/ Zehendtner/ Geschworne/ Außtheiler/ Bergkschreiber/ Gegenschreiber/ Marscheider/ Probirer/ Silberbrenner/ mit jhrem Lohn nicht ubernommen/ und zu klagen ursache haben/ ist bey eines jeden Ampt und befehlich/ seine besoldung und gebür verzeichnet/ damit sie begnügig seyn sollen/ unnd darüber von den Gewercken oder jemandt anders/ weder durch sich oder ander/ ein mehrers zu fordern/ nicht gestattet werden.\n\nDa aber einer oder der ander/ sich an geordneter gebür nicht gnügen lassen/ und sich unterstünde newe auffsätze zu machen/ unnd ein mehrers von den Gewercken oder andern zu fordern/ der sol nach befindung des excess, an Leib und Gut gestraffet werden.\n\nWaß der Bergk-Hauptman/ Bergkmeister unnd Geschworne/ vermüge der Bergkordnung/ schaffen und befehlen/ dem sol gehorsamb geleistet werden. Alles das jenige/ so der Bergk-Hauptman/ Bergkmeister und Geschworne [...] mit Schichtmeistern/ Steigern/ Arbeitern/ Gewercken/ und allen andern/ so in Bergksachen [...] für jhnen zu thun haben [...] befehlen/ schaffen/ wissen/ gebieten [...] darin sollen sie jhnen ohn widerrede/ gehorsamb leisten [...] und sich keines weges mit spitzigen/ unbescheidenen Worten und Antwort gegen sie einlassen/ sondern ein jeder sol und mag seine notturfft und rede/ mit bescheidenheit darzu thun/ Würde aber das Wiederspiel befunden/ so sol derselbe Uberträtter mit ernst also gestrafft werden/ das er deß LandeßFürsten mißfall daraus vermercken sol.\n\nDa aber jemandt vermeindte/ jhm geschehe durch bemelte Amptleute ungütlich/ oder er würde wider die billigkeit beschweret/ der lasse es mit bescheidenheit an Uns/ als dem LandeßFürsten gelangen [...]",
         en="Von der Besoldung und den Gebühren der Bergamtleute.\n\nDamit die Gewerken oder andere vom Bergmeister, Zehntner, von den Geschworenen, dem Austeiler, Bergschreiber, Gegenschreiber, Markscheider, Probierer und Silberbrenner mit ihren Gebühren nicht übervorteilt werden und Grund zur Klage haben, ist bei jedem Amt und Auftrag seine Besoldung und Gebühr verzeichnet; damit sollen sie sich begnügen, und es soll ihnen nicht gestattet werden, darüber hinaus von den Gewerken oder jemand anderem, selbst oder durch andere, mehr zu fordern.\n\nWenn aber der eine oder andere sich mit der festgesetzten Gebühr nicht begnügt und sich unterstünde, neue Aufschläge zu machen und von den Gewerken oder anderen mehr zu fordern, der soll je nach dem Maß der Überschreitung an Leib und Gut bestraft werden.\n\nWas der Berghauptmann, der Bergmeister und die Geschworenen nach der Bergordnung anordnen und befehlen, dem soll Gehorsam geleistet werden. In allem, was der Berghauptmann, der Bergmeister und die Geschworenen [...] den Schichtmeistern, Steigern, Arbeitern, Gewerken und allen anderen, die in Bergsachen mit ihnen zu tun haben, befehlen, anordnen und gebieten [...], sollen diese ihnen ohne Widerrede gehorchen [...] und sich keineswegs mit spitzen, unbescheidenen Worten und Antworten gegen sie einlassen; sondern jeder soll und darf sein Anliegen und seine Rede mit Bescheidenheit vorbringen. Würde aber das Gegenteil befunden, so soll der Übertreter mit Ernst so bestraft werden, dass er das Missfallen des Landesfürsten daraus erkennt.\n\nWenn aber jemand meinte, ihm geschehe durch die genannten Amtleute Unrecht oder er würde wider die Billigkeit belastet, der bringe es mit Bescheidenheit an uns als den Landesfürsten [...]",
         note="Die Gebühren stehen in Tafeln bei jedem Amt; die des Bergmeisters zum Beispiel für das Verleihen einer Grube, eines Erbstollens oder eines ‚Wassers in einen Stollen‘ (S. 196–197, hier nicht abgedruckt). Die Ordnung schützt die Gewerken vor den Beamten und die Beamten vor den Bergleuten: Gehorsam ‚ohne Widerrede‘, Klage nur ‚mit Bescheidenheit‘ beim Landesfürsten. Der Austeiler verteilt die Ausbeute an die Gewerken."),
    dict(n=5, titel="Der Berghauptmann ‚an des Landeßfürsten statt‘", pg="S. 195", lang="fnhd",
         orig="Von des Bergk-Hauptmans befehl.\n\nDer Bergk-Hauptman sol an des Landeßfürsten statt vleissige auffsicht haben/ das Friede/ Gerechtigkeit/ unnd diese Ordnung unverbrüchlich gehalten/ aller Betrug/ Untrew und Unrecht abgewendet/ und wo es befunden/ mit ernst gestrafft/ gemeines Bergkwercks/ unnd alle der jenigen/ so sich dessen gebrauchen/ Nutz und frommen gefordert/ Schaden und Nachtheil aber/ so viel müglich/ verhütet werde/ Und sol der Bergk-Hauptman allen andern obbemelten Amptleuten und verordneten/ deßgleichen allen Amptsverwäsern unnd jederman zum Bergkwerck gehörent/ von unsernt wegen zu schaffen/ zu gebieten und zu verbieten haben/ deme auch biß zu unserer verenderung/ von jederman/ gleich unserer Person/ in allen billigen Sachen/ vollkommener gehorsamb/ bey vermeidung ernster straffe/ sol geleistet werden. [...]\n\nEr sol auch/ so ferne er durch andere geschefft nicht verhindert/ den Anschnits: Retardat tagen und andern nothwendigen Sachen/ auch allewege bey der Quartal Rechnung persönlich seyn [...]\n\nWann irrige Bergksachen/ die für Bergkmeister unnd Geschworne nicht könten vertragen werden/ ins Ampt wachsen/ sol unser Bergk-Hauptman zu ferner gütlichen handelung/ auffs förderlichste sie vorbescheiden [...]\n\nUnser Bergk-Hauptman und Bergkmeister sollen auch gebürliches einsehen thun/ damit die jenigen/ so mit Unßlit/ Eisen und andern zum Bergkwerck nothdürfftig/ handeln/ nach steigen und fallen der Kauff/ einen gleichen Kauff ordnen und machen/ das sie an einen zimblichen Gewiñ begnügig seyn/ damit kein beschwerliches Steigen eingeführet werde [...]",
         en="Vom Auftrag des Berghauptmanns.\n\nDer Berghauptmann soll an Stelle des Landesfürsten fleißig darauf achten, dass Friede, Gerechtigkeit und diese Ordnung unverbrüchlich gehalten, aller Betrug, alle Untreue und alles Unrecht abgewendet und, wo man es findet, mit Ernst bestraft werden, dass der Nutzen und das Wohl des gemeinen Bergwerks und aller, die es nutzen, gefördert, Schaden und Nachteil aber, soweit möglich, verhütet werden. Und der Berghauptmann soll allen anderen genannten Amtleuten und Verordneten, ebenso allen Amtsverwesern und jedermann, der zum Bergwerk gehört, in unserem Namen zu befehlen, zu gebieten und zu verbieten haben; ihm soll bis zu einer Änderung durch uns von jedermann wie unserer eigenen Person in allen billigen Sachen vollkommener Gehorsam geleistet werden, bei Vermeidung ernster Strafe. [...]\n\nEr soll auch, soweit ihn andere Geschäfte nicht hindern, an den Anschnitt- und Retardattagen und bei anderen notwendigen Sachen und immer bei der Quartalsrechnung persönlich anwesend sein [...]\n\nWenn strittige Bergsachen, die vor dem Bergmeister und den Geschworenen nicht beigelegt werden können, ins Amt kommen, soll unser Berghauptmann sie zur weiteren gütlichen Verhandlung schnellstens vorladen [...]\n\nUnser Berghauptmann und Bergmeister sollen auch gebührend darauf achten, dass die, die mit Unschlitt, Eisen und anderem für das Bergwerk Notwendigen handeln, je nach Steigen und Fallen der Preise einen gleichen Preis ordnen und festsetzen und mit einem angemessenen Gewinn zufrieden sind, damit kein beschwerliches Steigen eingeführt werde [...]",
         note="Der Berghauptmann ist der Stellvertreter des Fürsten, nicht ein Bergmann: Er gebietet allen, auch dem Bergmeister, und ihm ist zu gehorchen ‚gleich unserer Person‘. Löhneyß war selbst Berghauptmann. Retardattage sind die Termine, an denen festgestellt wurde, welche Gewerken ihre Zubuße schuldig geblieben waren; wer nicht zahlte, verlor seine Kuxe. Unschlitt (Talg) brauchte man für die Grubenlampen, Eisen für das Gezähe; der Berghauptmann setzt ihre Preise fest. Ausgelassen sind Bestimmungen über Beschwerden gegen den Berghauptmann und über die Aufsicht über die Register der Schichtmeister."),
    dict(n=6, titel="Der Bergmeister verleiht Zechen, Stollen und ‚Wassergefäll‘", pg="S. 195–196", lang="fnhd",
         orig="Der 2. Articul. Von des Bergkmeisters Ampt und befehl.\n\nUnser jetziger oder künfftiger Bergkmeister/ unser Bergkwerck zu N. sol mit allem vleiß darauff sehen/ und verschaffen/ das dem gemeinen Bergkwercke und den Gewercken getrewlich/ nützlich und wol vorgestanden/ die Gebäwde gefordert/ und was schaden drawet/ fürkommen/ einem jeden/ der jhn ansuchet/ in Sachen seinem Ampt zustendig/ was recht und billig ist/ gestatten und verhelffen.\n\nEr sol auch denen/ so Zechen/ Stollen/ Wassergefäll/ Hütten und Püchstäte begehren zu Muhten/ dieselben zuverleihen/ zu bestätigen/ die Gruben zu Marscheiden/ und jhnen Loch: oder Marstein zu setzen schuldig seyn/ unnd verhüten/ das kein vergeblich Gebäwde vorgenommen werde.\n\nAm Sonnabent sol er mit allen Geschwornen im Anschnitt seyn/ und aller Schichtmeister Rechnung anhören/ was die Wochen in der Gruben verbawet/ in Puchwercken und Schmeltzhütten für Unkosten auffgangen sey.\n\nUnd sol dieser unser Bergkordnung in allen Puncten trewlich geleben und nachsetzen/ das der auch von männiglich nachgesetzet werde/ verfügen/ an seiner zugeordneten und zugelassenen besoldung begnägig seyn [...]",
         en="Der 2. Artikel. Vom Amt und Auftrag des Bergmeisters.\n\nUnser jetziger oder künftiger Bergmeister unseres Bergwerks zu N. soll mit allem Fleiß darauf sehen und dafür sorgen, dass dem gemeinen Bergwerk und den Gewerken treu, nützlich und gut vorgestanden, die Gebäude gefördert und was Schaden droht verhütet werde, und jedem, der ihn ersucht, in Sachen, die zu seinem Amt gehören, gestatten und verhelfen, was recht und billig ist.\n\nEr soll auch denen, die Zechen, Stollen, Wassergefälle, Hütten und Pochstätten muten wollen, diese verleihen, bestätigen, die Gruben vermessen und ihnen Loch- oder Marksteine setzen, und verhüten, dass kein vergebliches Gebäude unternommen werde.\n\nAm Samstag soll er mit allen Geschworenen beim Anschnitt sein und die Rechnung aller Schichtmeister anhören, was in der Woche in der Grube verbaut worden ist und was in den Pochwerken und Schmelzhütten an Unkosten angefallen ist.\n\nUnd er soll dieser unserer Bergordnung in allen Punkten treu nachleben und nachkommen, dafür sorgen, dass sie auch von jedermann befolgt werde, und sich mit seiner zugeordneten und zugelassenen Besoldung begnügen [...]",
         note="‚Zu N.‘: Die Ordnung ist als Muster gedruckt, in das der Name der Bergstadt einzusetzen ist. ‚Muten‘ heißt, beim Bergamt die Verleihung eines Grubenfeldes beantragen. Neben Zechen, Stollen und Hütten verleiht der Bergmeister auch ‚Wassergefäll‘: das Recht, ein Gefälle des Wassers für ein Rad zu nutzen. Das Wasser war also ein Gut, das wie eine Grube verliehen wurde (vgl. Modul ‚Die Bergfreiheiten‘, Clausthal [5]). Der Bergmeister soll auch ‚vergebliche Gebäude‘ verhindern, Gruben, die nichts bringen können. Die Samstagsabrechnung ist der ‚Anschnitt‘, den Löhneyß im Eid zum Jüngsten Gericht macht (Ämter [2])."),
]

STOLLEN = [
    dict(n=1, titel="‚Die Juden sollen nicht geduldet noch gehauset werden‘", pg="S. 222", lang="fnhd",
         orig="Der 33. Articul. Die Juden sollen nicht geduldet noch gehauset werden.\n\nZU dem wird auch offtmahls solch Ertz und Silber/ den Juden/ so jhren unterschleiff unnd practiken heimlicher weise allenthalben in unsere Lande machen/ unterschoben/ und von jnen auffgekaufft/ und fürder aus den Landen verschleifft werde.\n\nDiesem vorzukommen/ ordnen Wir/ das hinforder kein Jude auff den Bergk-Städten mehr dann eine Nacht von jemandts unsern Unterthanen sol beherget/ da jhn aber jemandts/ es sey Wirth oder andere/ beherbergen würden/ der sol ernstlich darumb gestrafft werden/ unnd sollen sich gentzlich solcher Juden und jhres betrugs enthalten/ bey Leibßstraffe/ die jhnen jmfall der Ubertrettung begegnen sol.\n\nWürde aber ein Jude darüber betroffen/ so sol er den halben theil alles deß/ so bey jhm befunden/ der Obrigkeit/ unnd den andern theil/ dem/ der jhn zu Haffte bringen wird/ verfallen seyn/ und so er mehr dann einmahl brüchig/ sol er an Leib und Gut gestraffet werden.",
         en="Der 33. Artikel. Die Juden sollen nicht geduldet noch beherbergt werden.\n\nAußerdem wird solches Erz und Silber oft den Juden, die ihre Schleichgeschäfte und Praktiken heimlich überall in unseren Landen betreiben, zugeschoben, von ihnen aufgekauft und weiter aus den Landen geschmuggelt.\n\nUm dem zuvorzukommen, verordnen wir, dass künftig kein Jude auf den Bergstädten länger als eine Nacht von einem unserer Untertanen beherbergt werden soll; würde ihn aber jemand, sei es ein Wirt oder ein anderer, beherbergen, der soll dafür ernstlich bestraft werden; und sie sollen sich solcher Juden und ihres Betrugs gänzlich enthalten, bei Leibesstrafe, die ihnen im Fall der Übertretung treffen soll.\n\nWürde aber ein Jude dabei angetroffen, so soll die Hälfte von allem, was man bei ihm findet, der Obrigkeit und die andere Hälfte dem, der ihn in Haft bringt, verfallen sein; und wenn er mehr als einmal straffällig wird, soll er an Leib und Gut bestraft werden.",
         note="Dieser Artikel steht in der Bergordnung zwischen den Bestimmungen gegen den Diebstahl von Erz und Silber (der vorige Artikel bedroht Goldschmiede, die gestohlenes Erz kaufen) und wird hier abgedruckt, weil er zur Ordnung gehört, die der Apparat vorstellt. Er unterstellt Juden pauschal Hehlerei und Betrug, ohne einen Fall zu nennen. Er verbietet, sie länger als eine Nacht zu beherbergen, droht den Gastgebern Strafe an und setzt eine Belohnung für jeden aus, der einen Juden ‚zu Haft bringt‘: die Hälfte seines Besitzes. Das ist die Gewalt der Ordnung, die dieser Apparat beschreibt, und sie richtete sich gegen Menschen, die mit dem Bergbau nichts zu tun hatten, als Fremde zu sein. Ob und wie der Artikel angewandt wurde, sagt das Buch nicht."),
    dict(n=2, titel="Jeder Bergmann darf schürfen; der erste Finder", pg="S. 222", lang="fnhd",
         orig="Der ander Theil dieser Ordnung/ saget vom Schörffen/ Muhten/ Stollenstewr unnd Zubuß anlegen/ Quatembergelt/ Retardat Kuxen/ und andern des Bergkwercks nothwendigen Sachen mehr.\n\nDer 1. Articul. Vom Schörffen.\n\nEinem jeglichen Bergkman sol hiemit nachgelassen und vergünstiget seyn/ auff unsern Gründen unnd Boden/ nach allen Metallen/ Gängen/ Klüfften und Schichten/ ohn der Grundtherren und Besitzer der Güter/ eintracht/ zu Schörffen/ Unnd welcher also einen newen Gangk entblössen unnd außrichten wird/ der sol der erste Finder seyn/ auch des ersten Finders Recht/ nemblich ein Fundgrube haben/ die Massen aber sollen den ersten Muhtern verliehen werden.",
         en="Der zweite Teil dieser Ordnung handelt vom Schürfen, Muten, von der Stollensteuer, vom Anlegen der Zubuße, vom Quatembergeld, von den Retardatkuxen und anderen notwendigen Sachen des Bergwerks mehr.\n\nDer 1. Artikel. Vom Schürfen.\n\nJedem Bergmann soll hiermit erlaubt und vergönnt sein, auf unseren Gründen und Böden nach allen Metallen, Gängen, Klüften und Schichten zu schürfen, ohne Einwilligung der Grundherren und Besitzer der Güter. Und wer so einen neuen Gang freilegt und aufschließt, der soll der erste Finder sein und auch das Recht des ersten Finders haben, nämlich eine Fundgrube; die Maßen aber sollen den ersten Mutern verliehen werden.",
         note="Die ‚Bergbaufreiheit‘ im engeren Sinn: Gesucht werden darf überall, auch auf fremdem Grund, ohne dass der Grundbesitzer zustimmen muss. Der Finder erhält eine Fundgrube, das erste Grubenfeld; die anschließenden Felder (‚Maßen‘) erhalten die, die sie zuerst beim Bergmeister muten. Das Quatembergeld war eine Abgabe je Vierteljahr für jede Grube; Retardatkuxe die Anteile von Gewerken, die mit der Zubuße im Rückstand waren."),
    dict(n=3, titel="Der Erbstollen: das Wasser nehmen, das Neunte erhalten", pg="S. 233", lang="fnhd",
         orig="Der 33. Articul. Von der Stollen Gerechtigkeit unnd Erbteuffe.\n\nWir Ordnen und wollen/ das ein jeglicher Erbstolle und andere Stollen/ was in dieser unser nachfolgenden Bergkordnung nicht verendert wird/ sein Gerechtigkeit haben und behalten/ auch gebawet werden sol/ wie gemeine Bergk Recht/ unnd alte herkommende ubung das geben und außweisen/ Nemblich/ Wann der Stollen an die Marscheidt seiner Fundtgruben oder Massen kömpt/ so ist dieselbe Maß oder Fundtgrube schuldig dem Stollen/ nach erkäntniß Bergkmeisters und Geschworne/ Stewr zu geben.\n\nUnnd wann ein Erbstolle mit seiner Erbteuffe/ als zehendtehalb Lachter vom Rasen seiger gerade nieder/ auch mit seiner gebürlichen Wasserseige/ in eine Zeche kömpt/ uber die Erbschächte/ oder an das Ort/ da Ertz bricht/ erschlägt/ derselben Zechen Wasser benimpt/ und Wetter bringet/ dem sol der Hieb und das Neundte gegeben werden.\n\nDer 34. Articul. Wie hoch und weit ein Erbstollen das Ertz hawen mag.\n\nUnnd wo ein Erbstolle in Massen kömpt/ darinnen er Ertz trifft/ so mügen die Stöllner fünff viertel eines Lachters/ von der Wasserseige ubersich/ und ein halb Lachter in die weite (vierdtehalb Ellen für ein Lachter gerechnet) das Ertz hawen und zu sich nehmen.",
         en="Der 33. Artikel. Von der Gerechtigkeit der Stollen und der Erbteufe.\n\nWir verordnen und wollen, dass jeder Erbstollen und jeder andere Stollen, soweit in unserer folgenden Bergordnung nichts geändert wird, seine Gerechtigkeit haben und behalten und auch so betrieben werden soll, wie es das gemeine Bergrecht und die alte, herkömmliche Übung geben und ausweisen; nämlich: Wenn der Stollen an die Markscheide seiner Fundgrube oder Maßen kommt, so ist diese Maße oder Fundgrube dem Stollen nach Erkenntnis des Bergmeisters und der Geschworenen Steuer zu geben schuldig.\n\nUnd wenn ein Erbstollen mit seiner Erbteufe, nämlich neuneinhalb Lachter vom Rasen senkrecht gerade hinab, auch mit seiner gebührlichen Wasserseige in eine Zeche kommt, die Erbschächte oder den Ort, wo Erz bricht, anfährt, dieser Zeche das Wasser nimmt und Wetter bringt, dem soll der Hieb und das Neunte gegeben werden.\n\nDer 34. Artikel. Wie hoch und wie weit ein Erbstollen das Erz hauen darf.\n\nUnd wo ein Erbstollen in Maßen kommt, in denen er Erz trifft, dürfen die Stöllner fünf Viertel eines Lachters von der Wasserseige aufwärts und ein halbes Lachter in die Breite (dreieinhalb Ellen für ein Lachter gerechnet) das Erz hauen und für sich nehmen.",
         note="Das Recht des Wassers in einem Satz: Wer einen Erbstollen so tief unter dem Rasen (mindestens neuneinhalb Lachter) in eine Grube treibt, dass er ihr ‚das Wasser benimmt und Wetter bringt‘, erhält von dieser Grube das Neunte, den neunten Teil ihrer Erzförderung, und das Recht, im Stollen selbst Erz zu hauen (den Hieb). Ein Stollen war also ein eigenes Unternehmen mit eigenen Gewerken, den ‚Stöllnern‘, das von den Gruben lebte, die es entwässerte. Die Wasserseige ist die Rinne auf der Sohle des Stollens, in der das Wasser abläuft; Wetter ist frische Luft. Ein Lachter misst nach diesem Text dreieinhalb Ellen, nach der neueren Literatur am Oberharz knapp zwei Meter."),
    dict(n=4, titel="Keine ‚Gesprenge‘; die Wasserseige nicht senken", pg="S. 234", lang="fnhd",
         orig="Der 36. Articul. Von Gesprengen in Stollen nicht zu gestatten.\n\nAuch Ordnen unnd setzen Wir/ das ein jeglicher Erbstollen mit seiner Wasserseigen/ nach alten herkommen Bergk Recht unnd Brauch/ solche treiben/ unnd einig Gespreng darin zu machen/ nicht gestattet werden/ es begebe sich dañ/ das krümme oder festen vorfielen/ also/ das der Stollen aus wichtigen Ursachen müste erhoben werden/ welches dennoch ohn besichtigung und zulassung des Bergkmeisters/ nicht geschehen sol/ und wo eine Zeche Wassers oder Wetters halben/ eines Stollen bedürffte/ derselbigen Zechen mag der Stollen/ doch mit zulassung des Bergkmeisters/ und ohn das nicht mit dem Stollort/ durch gesprenge zu hülffe kommen/ und darumb in derselbigen Zechen/ das Neundte und seine Stollen Gerechtigkeit erlangen. [...]\n\nDer 37. Articul. Daß kein Stöllner seine erste Wasserseige sencken/ erheben oder verlassen sol.\n\nWelcher Stöllner erstlich unnd anfencklich in seiner Wasserseige untergekrochen/ dieselbige außgezimmert/ Treckbretter drüber geschlagen/ und sich also gelagert hat/ dem sol keines weges gestattet werden/ dieselbige Wasserseige weder in noch ausserhalb des Mundtlochs zu sencken/ oder tieffer zu holen/ ohn unsers Bergkhauptmans unnd Bergkmeister zulassung/ wo es aber geschehe/ so sollen sie es mit ernste straffen.",
         en="Der 36. Artikel. Gesprenge in Stollen sind nicht zu gestatten.\n\nAuch verordnen und setzen wir fest, dass jeder Erbstollen mit seiner Wasserseige nach altem, herkömmlichem Bergrecht und Brauch getrieben werden und kein Gesprenge darin gemacht werden darf; es sei denn, dass Krümmen oder feste Gesteine vorfielen, so dass der Stollen aus wichtigen Gründen angehoben werden müsste, was dennoch nicht ohne Besichtigung und Zulassung des Bergmeisters geschehen soll. Und wo eine Zeche wegen des Wassers oder der Wetter eines Stollens bedürfte, darf der Stollen dieser Zeche, doch mit Zulassung des Bergmeisters und nicht ohne sie, mit dem Stollort durch ein Gesprenge zu Hilfe kommen und dafür in dieser Zeche das Neunte und seine Stollengerechtigkeit erlangen. [...]\n\nDer 37. Artikel. Dass kein Stöllner seine erste Wasserseige senken, anheben oder verlassen soll.\n\nWelcher Stöllner zuerst und anfangs in seiner Wasserseige untergefahren ist, sie ausgezimmert, Tragbretter darübergeschlagen und sich so festgesetzt hat, dem soll keineswegs gestattet werden, diese Wasserseige innerhalb oder außerhalb des Mundlochs zu senken oder tiefer zu legen, ohne Zulassung unseres Berghauptmanns und Bergmeisters; geschieht es aber, so sollen sie es mit Ernst bestrafen.",
         note="Ein ‚Gesprenge‘ ist eine Stufe, ein Sprung in der Sohle eines Stollens. Der Erbstollen soll mit gleichmäßigem Gefälle getrieben werden, damit das Wasser ohne Unterbrechung abläuft, und nur der Bergmeister darf Ausnahmen erlauben. Ebenso darf kein Stöllner seine Wasserseige nachträglich tiefer legen: Wer tiefer liegt, nimmt mehr Gruben das Wasser und gewinnt mehr Neuntel, und das hätte die Rechte der anderen Stollen verschoben. ‚Treckbretter‘ (Tragbretter) sind die Bretter über der Rinne, auf denen gefahren wird; übertragen ist nach dem Sinn. Die Tiefe eines Stollens war Rechtssache: Darum stritten Stollen und Gruben, und darum ließ der Landesherr später die großen Stollen selbst treiben (Modul ‚Der Tiefe Georg-Stollen‘, geplant)."),
]

doc = {
    "id": "bergamt",
    "titel": "Das Bergamt: Löhneyß' Bericht vom Bergwerck, 1617",
    "autor": "Georg Engelhard Löhneyß, Berghauptmann",
    "jahr": "1617",
    "sprache": "de",
    "orig_sprache": "fnhd",
    "pg_label": "",
    "quelle": "G. E. Löhneyß, Bericht vom Bergkwerck, wie man dieselben bawen, und in guten Wolstandt bringen soll, sampt allen darzu gehörigen Arbeiten, Ordnung und rechtlichen Process ([Zellerfeld] 1617), Widmung, Vorrede und Bergordnung S. 191–196, 222, 233–234; Exemplar der ETH-Bibliothek Zürich (Rar 1553), e-rara, doi:10.3931/e-rara-15531 (Public Domain Mark). Übertragung: eigene Arbeit.",
    "hinweis": "Nach der Erstausgabe von 1617, am Seitenbild gelesen, in der Schreibung des Drucks; die Virgeln (/) des Frakturdrucks sind beibehalten, Abkürzungen mit Tilde (dañ) stehen wie gedruckt. Die Bergordnung, die Löhneyß im zweiten Teil seines Buches abdruckt, spricht im Namen des Landesfürsten (‚Wir‘) und ist als Muster gesetzt (‚unser Bergkwerck zu N.‘); welche Fassung im Oberharz 1617 tatsächlich galt, sagt das Buch nicht, und das ist hier nicht geprüft. Die Seitenzählung der Erstausgabe ist an zwei Stellen unterbrochen (Blätter statt Seiten); die Seitenzahlen der Bergordnung sind die des Drucks. Auslassungen sind mit [...] bezeichnet.",
    "sections": [
        {"id": "vorrede", "autor": "Georg Engelhard Löhneyß", "titel": "Widmung und Vorrede", "zk": "Vorrede",
         "plates": ["loehneyss_titel"],
         "blurb": "Ein Berghauptmann schreibt gegen die Gelehrten, die ‚allein ad Theoricam‘ gesehen haben: Gute Bergwerke gehen durch schlechte Beamte ‚zu sumpff‘, gute Ordnung macht auch geringe Gruben reich. Warum Löhneyß 1617 sein Buch drucken ließ und wem er es widmete.",
         "units": VORREDE},
        {"id": "aemter", "autor": "Die Bergordnung bei Löhneyß", "titel": "Die Ämter und der Eid", "zk": "Ämter",
         "plates": ["loehneyss_s193"],
         "viz": "aemter",
         "blurb": "Wer das Bergwerk regiert: vom Berghauptmann ‚an des Landeßfürsten statt‘ über Zehntner, Bergmeister, Geschworene, Steiger und Schichtmeister bis zu den Hüttenleuten, den Ältesten der Knappschaft und den Häuslingen. Dazu der Eid, mit dem einer sich ‚mit allen Teuffeln verbant und verflucht‘, wenn er untreu wird, und der Bergmeister, der Zechen, Stollen und ‚Wassergefäll‘ verleiht.",
         "units": AEMTER},
        {"id": "stollen", "autor": "Die Bergordnung bei Löhneyß", "titel": "Schürfen, Stollen, Wasserseige", "zk": "Stollen",
         "plates": ["loehneyss_s233"],
         "blurb": "Das Recht des Wassers: Wer einer Grube mit seinem Erbstollen ‚das Wasser benimmt und Wetter bringt‘, erhält das Neunte ihres Erzes. Kein Stollen darf seine Wasserseige eigenmächtig tiefer legen. Jeder Bergmann darf schürfen, auch auf fremdem Grund. Und ein Artikel, der Juden aus den Bergstädten fernhält, mit einer Belohnung für jeden, der einen Juden in Haft bringt.",
         "units": STOLLEN},
    ],
}

OUT.write_text(json.dumps(doc, ensure_ascii=False, indent=1), encoding="utf-8")
print("bergamt.json:", sum(len(s["units"]) for s in doc["sections"]), "Einheiten")
