"""Modul 7: Der Tiefe Georg-Stollen, 1777–1799. Schreibt data/stollen.json.

Quellen, am Seitenbild gelesen:
C. F. von Reden, Rede bey dem feyerlichen Anfange des Tiefen Georg-Stollen-Baues am 26. Julius
1777 unweit der Bergstadt Grund am Harze, nebst der Predigt [...] von G. C. Dahme (Clausthal 1777)
(Internet Archive 10293262bsb; Rede S. 3–12 = Blatt n14–n23, Predigt Blatt = S.+11).
G. S. O. Lasius, Beobachtungen über die Harzgebirge, Erster Theil (Hannover 1789), S. 37–38,
51–52 und Profiltafel (Internet Archive 10806207bsb; S. 37 = n68, Tafel n70, S. 51 = n84).
C. G. Horstig, Tageblätter unsrer Reise in und um den Harz (Leipzig 1805), S. 147–148
(Internet Archive 10469480bsb; n180–n181).
"""
import json
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "data" / "stollen.json"

REDE = [
    dict(n=1, titel="‚Die zu große Last der Grundwasser‘", pg="Reden 1777, S. 3–4", lang="nhd",
         orig="Nicht leicht wird einem der vielen hier Anwesenden unbekannt seyn, daß fast alle Gruben sowohl desjenigen Theiles unserer Harzgebürge, welches Ihro Majestät Unserm Allergnädigsten Könige und Herrn allein zustehet, als des andern Theiles, welches Allerhöchst-Denenselben mit Ihro Durchlauchten dem Herzoge zu Braunschweig Unserm Gnädigsten Herrn in Gemeinschaft zugehörig ist, allbereits eine ansehnliche Teufe erlanget haben, und daß sie, so wie ihre Gesenke im Betriebe sind, von Tage zu Tage tiefer werden.\n\nEine natürliche Folge hievon ist nicht nur die Vermehrung der Grundwasser, sondern auch daß selbige, mit der zunehmenden Teufe derer Gruben, durch mehrere Sätze und um so beschwerlicher auf die jetzt vorhandenen Stollen zu heben sind, worunter leider keiner ist, von dem man sagen könnte, daß er alle, nach der Lage unserer Gebürge mögliche, Teufe einbringe.\n\nMehrere ganze Züge haben bereits vor unsern Zeiten das traurige Schicksal erlitten, daß nicht sowohl der Mangel der Erze, (denn wie weit solche in die Teufe setzen, ist allen Naturerforschern und Bergwerksverständigen annoch unbekannt, und eine bloße zufällige Verringerung der Anbrüche, wovon bekanntlich auch die reichsten Gänge und Gruben von Zeit zu Zeit gar beträchtlichen Nachtheil verspüren, kann in diesem Betracht wohl nicht als entscheidend angesehen werden) als die zu große Last der Grundwasser zu ihrer Einstellung den Bewegungsgrund gegeben haben.",
         en="Kaum einem der vielen hier Anwesenden wird unbekannt sein, dass fast alle Gruben, sowohl in dem Teil unseres Harzgebirges, der Seiner Majestät, unserem allergnädigsten König und Herrn, allein gehört, als auch in dem anderen Teil, der Seiner Majestät gemeinsam mit Seiner Durchlaucht, dem Herzog von Braunschweig, unserem gnädigsten Herrn, gehört, schon eine ansehnliche Tiefe erreicht haben und dass sie, so wie ihre Gesenke betrieben werden, von Tag zu Tag tiefer werden.\n\nDie natürliche Folge davon ist nicht nur, dass das Grundwasser zunimmt, sondern auch, dass es mit der wachsenden Tiefe der Gruben über mehr Pumpensätze und umso mühsamer auf die vorhandenen Stollen gehoben werden muss, unter denen leider keiner ist, von dem man sagen könnte, er bringe alle Tiefe ein, die nach der Lage unserer Gebirge möglich ist.\n\nMehrere ganze Gangzüge haben schon vor unserer Zeit das traurige Schicksal erlitten, dass nicht so sehr der Mangel an Erz (denn wie weit es in die Tiefe reicht, wissen alle Naturforscher und Bergwerkskundigen bis heute nicht, und eine bloß zufällige Abnahme der Anbrüche, die bekanntlich auch die reichsten Gänge und Gruben von Zeit zu Zeit empfindlich spüren, kann in dieser Hinsicht wohl nicht als entscheidend gelten) als vielmehr die zu große Last des Grundwassers den Anlass gab, sie einzustellen.",
         note="Der Satz, aus dem der Titel des Begleitspiels stammt: ‚die zu große Last der Grundwasser‘. Der Berghauptmann Claus Friedrich von Reden spricht am Mundloch bei Grund vor den versammelten Bergleuten. Sein Argument verschiebt die Erklärung für den Niedergang: nicht das Erz gehe aus, sondern das Wasser werde zu schwer. Der König, von dem er spricht, ist Georg III. von Großbritannien, zugleich Kurfürst von Braunschweig-Lüneburg (Hannover); der Stollen trägt seinen Namen. ‚Einbringen‘ heißt im Bergbau: Tiefe gewinnen, unter der das Wasser frei abfließt."),
    dict(n=2, titel="Teiche, Gräben, Künste: ‚allemal sehr kostbar‘", pg="Reden 1777, S. 5–7", lang="nhd",
         orig="Gewiß hat der Anblick der traurigen Ueberbleibsel jener verlassenen Züge, ich meine ihrer Hallen und Pingen, bey mehreren unter uns, so wie bey mir, den rührenden Gedanken erreget: welche Belebung würde die Gewinnung derer an diesen Orten in der Teufe ohne Zweifel annoch verborgenen Schätze dem Harze und mithin andern Theilen unseres Vaterlandes geben, wenn diese Züge durch dienliche Einrichtungen und Mittel noch jetzt mit Nutzen zu betreiben stünden! […]\n\nDie Verbesserung des Kunstwerks, so wie der Teiche und der Wasserleitungen, ist, nebst Herbeyführung mehrerer Aufschlagewasser, insonderheit von jenen höhern bruchigten Gebürgen, wozu unsere Vorfahren die Bahn so rühmlich gebrochen haben, zeither einer der ersten Gegenstände der Aufmerksamkeit der hier gegenwärtigen Berg-Amts-Glieder gewesen, und niemand wird uns hierunter eines Mangels an Eifer mit Recht beschuldigen können.\n\nAllein bis daher haben wir hiedurch und durch andere zu ersinnende Verbesserungen der Arbeiten und des Haushalts bey dem Berg- Puch- und Hüttenwesen ein mehreres zu bewürken nicht vermogt, als die Gruben und Züge, welche von unseren Vorfahren uns im Betriebe sind überliefert worden, in selbigem zu erhalten, (obgleich ein ansehnlicher Theil davon vorhin dem Einstellen sehr nahe war,) und den Betrieb des Bergwerks im Ganzen unter göttlichem Seegen in etwas zu erweitern, auch manchem, wegen seines Unterhalts besorgten, ein gewisses Brodt zu verschaffen.\n\nKönnte man auch noch ferner noch so viele Aufschlagewasser zum Umtriebe der Wasserkünste herbey führen: so bleibt dieses Mittel, die Züge von denen Grundwassern zu befreyen, dennoch allemal sehr kostbar.\n\nNur einige mit vorzüglichen Anbrüchen gesegnete Gruben, wie sie nicht allgemein, sondern nur selten bey uns gefunden werden, können allenfalls, auf eine Reihe von Jahren, dergleichen schwere Kosten ertragen, und dennoch der Herrschaft Nutzen, ihren Gewerken aber reiche Ausbeute geben.\n\nDie allerwenigsten Gruben hingegen vermögen unter einer solchen Last empor zu kommen.",
         en="Gewiss hat der Anblick der traurigen Überreste jener verlassenen Züge, ich meine ihrer Halden und Pingen, bei mehreren von uns wie bei mir den bewegenden Gedanken geweckt: Welche Belebung würde es dem Harz und damit anderen Teilen unseres Vaterlandes geben, wenn man die Schätze, die an diesen Orten ohne Zweifel noch in der Tiefe verborgen sind, gewinnen und diese Züge mit geeigneten Einrichtungen und Mitteln noch heute mit Nutzen betreiben könnte! […]\n\nDie Verbesserung des Kunstwerks wie der Teiche und Wasserleitungen und die Heranführung von mehr Aufschlagwasser, besonders von jenen höheren, moorigen Bergen, wozu unsere Vorfahren so rühmlich den Weg gebahnt haben, ist bisher einer der wichtigsten Gegenstände der Aufmerksamkeit der hier anwesenden Mitglieder des Bergamts gewesen, und niemand wird uns darin mit Recht einen Mangel an Eifer vorwerfen können.\n\nAllein bisher haben wir dadurch und durch andere Verbesserungen der Arbeit und des Haushalts im Berg-, Poch- und Hüttenwesen nicht mehr bewirken können, als die Gruben und Züge, die uns unsere Vorfahren in Betrieb überliefert haben, in Betrieb zu halten (obwohl ein ansehnlicher Teil davon vorher kurz vor der Einstellung stand), den Betrieb des Bergwerks im Ganzen unter Gottes Segen etwas zu erweitern und manchem, der um seinen Unterhalt besorgt war, ein sicheres Brot zu verschaffen.\n\nKönnte man auch noch so viel Aufschlagwasser zum Betrieb der Wasserkünste heranführen, so bleibt dieses Mittel, die Züge vom Grundwasser zu befreien, doch immer sehr kostspielig.\n\nNur einige Gruben mit besonders reichen Anbrüchen, wie man sie nicht allgemein, sondern nur selten bei uns findet, können solche schweren Kosten allenfalls eine Reihe von Jahren tragen und dennoch der Herrschaft Nutzen und ihren Gewerken reiche Ausbeute geben.\n\nDie allermeisten Gruben dagegen können unter einer solchen Last nicht hochkommen.",
         note="Reden zieht die Bilanz der Module 3 und 4: Teiche, Gräben und Künste hätten das Bergwerk nur erhalten, nicht retten können. Die ‚höhern bruchigten Gebürge‘ sind die Moore des Bruchbergs, von denen der Dammgraben kommt (Modul 4). ‚Ein gewisses Brodt‘ heißt ein sicheres Auskommen; Reden nennt die Bergleute als Begünstigte, aber im Singular des Einzelnen, ‚manchem‘. Ausgelassen [‚…‘] sind die rhetorischen Fragen, ob es solche Mittel geben könne."),
    dict(n=3, titel="Ein wohlfeileres Mittel: der tiefe Hauptstollen", pg="Reden 1777, S. 7–9", lang="nhd",
         orig="Wie könnte man daher einen erwünschten Erfolg von der Wiederaufnahme verlassener Züge blos durch die Hülfe des Kunstwerks erwarten, wenn nicht zugleich besondere Umstände oder andere vorhin nicht vorhanden gewesene Hülfsmittel und Verbesserungen mit in Betracht kommen? […] so ist doch die Erwartung des Nutzens um so größer, wenn man versichert seyn kann, die Grundwasser ohne große Kosten los zu werden.\n\nEs war demnach ein wohlfeileres und entscheidendes Mittel zu möglichster Abtrocknung nicht nur der im Betriebe seyenden, sondern auch einiger verlassenen Züge zu suchen, und nach Nummer 17 des Bergamts-Protocolls von Nummer 7 Trinitatis 1771 glaubte man, selbiges und die damit in Verbindung stehende Ausbreitung unseres Bergwerks, so wie die Fortsetzung desselben auf die Nachkommenschaft, in der Herbeytreibung eines tiefen Hauptstollens zu finden, und es wurden von dem Bergamte, nachdem dieser wichtige Gegenstand, in Gemäßheit des Vorschlages, in reifliche Untersuchung war genommen worden, die zu Beförderung der Absicht diensamen Vorstellungen an höhern Ort pflichtmäßig abgestattet.\n\nKönigliches Ministerium sahe, nach seiner ausgebreiteten durchdringenden Einsicht, den völligen Nutzen dieser Unternehmung leicht ein, und ohnverfehlete, nach dem höchst rühmlichen Eifer für den Dienst Seiner Majestät und das Beste des Landes, Allerhöchst-Denenselben die nöthigen Vorträge zu Ausführung des Vorhabens zu thun. […]\n\nDie gar mannigfaltigen und mit Beschwerde und Sorgfalt verknüpft gewesenen Untersuchungen und Ueberlegungen, welche der Ausführung der Unternehmung nothwendig vorher gehen mußten, um von einem guten Erfolge eine völlige Versicherung zu erhalten, haben gleichwohl, nebst denen Communicationen über diese Angelegenheit zwischen beyden Allerhöchsten und Höchsten Herrschaftlichen Häusern, den Angriff der Arbeit selbst bis daher aufgehalten.",
         en="Wie könnte man daher von der Wiederaufnahme verlassener Züge einen erwünschten Erfolg allein durch die Hilfe des Kunstwerks erwarten, wenn nicht zugleich besondere Umstände oder andere, früher nicht vorhandene Hilfsmittel und Verbesserungen hinzukommen? […] so ist die Erwartung des Nutzens doch umso größer, wenn man sicher sein kann, das Grundwasser ohne große Kosten loszuwerden.\n\nEs war also ein billigeres und entscheidendes Mittel zu suchen, um nicht nur die betriebenen, sondern auch einige verlassene Züge so weit wie möglich trockenzulegen; und nach Nummer 17 des Bergamtsprotokolls Nummer 7 vom Quartal Trinitatis 1771 glaubte man, dieses Mittel und die damit verbundene Ausdehnung unseres Bergwerks sowie seine Fortsetzung für die Nachkommen im Vortrieb eines tiefen Hauptstollens zu finden. Nachdem diese wichtige Sache dem Vorschlag gemäß gründlich untersucht worden war, erstattete das Bergamt pflichtgemäß die Berichte an höherer Stelle, die der Absicht dienlich waren.\n\nDas königliche Ministerium erkannte mit seiner umfassenden, durchdringenden Einsicht leicht den vollen Nutzen dieses Unternehmens und versäumte nicht, Seiner Majestät aus höchst rühmlichem Eifer für den Dienst des Königs und das Beste des Landes die nötigen Vorträge zur Ausführung des Vorhabens zu halten. […]\n\nDie vielfältigen, mit Mühe und Sorgfalt verbundenen Untersuchungen und Überlegungen, die der Ausführung notwendig vorangehen mussten, um eines guten Erfolgs völlig sicher zu sein, haben jedoch, zusammen mit den Verhandlungen zwischen den beiden höchsten Herrscherhäusern über diese Sache, den Beginn der Arbeit selbst bis heute aufgehalten.",
         note="Vom Protokoll zur Feier: Reden zitiert die Aktennummer des Beschlusses von 1771 in einer Festrede. Sechs Jahre vergehen bis zum ersten Schlag, und er nennt den Grund: die Verhandlungen zwischen Hannover und Braunschweig, denen der Oberharz gemeinsam gehörte (die ‚Kommunion‘, vgl. Modul 5 und 6). Ausgelassen [‚…‘] sind die Sätze über verlassene Züge mit neuen Hilfsmitteln und ein Lob des Königs, der die Kosten bewilligt und das Werk ‚mit ohnunterbrochener selbst eigener Allerhöchsten Aufmerksamkeit‘ betrieben habe. Die Kosten nennt Reden nicht."),
    dict(n=4, titel="4910 Lachter bis zur Caroline", pg="Reden 1777, S. 10–11", lang="nhd",
         orig="Nachdem jedoch der hier vor uns liegende Platz zum Mundloch des vorberührten Hauptstollens, welcher, in Gemäßheit der deshalbigen Muthung, mit dem Nahmen\n\nTiefer Georg-Stollen\n\njederzeit soll beleget werden, benebst dessen ganzer Tour (welche bis z. B. in das Feld der Grube Caroline, alwo er 162 Lachter Teufe vom Tage und 80 Lachter unter dem daselbst vorhandenen so genannten Dreyzehn-Lachter-Stollen einbringt, 4910 Lachter lang werden wird) bis in den Rosenhöfer- und Burgstädter- auch den Silbernaaler- und den Communion-Hauptzug und denen auf selbiger Tour nöthigen Lichtlöchern, wovon das tiefste eine Teufe von 113 Lachtern erhalten wird, bestimmet worden, nächst dem auch über die, mit dem Stollenbetriebe in Verbindung stehende, Gegenstände ein Receß zwischen beyderseitigen Allerhöchsten und Höchsten Communion-Herrschaftlichen Häusern geschlossen und in denen Berg-Aemtern gehörig publiciret ist: so steht nunmehro der Ausführung des, dem ganzen Harze wichtigen, Werkes nichts ferner im Wege: und es liegt mir eines der angenehmsten Geschäfte ob, dessen mich zu entledigen ich jetzt im Begriff bin, durch Verrichtung des ersten Schlages nemlich den Anfang mit der würklichen Handarbeit zu machen.",
         en="Nachdem aber der Platz, der hier vor uns liegt, für das Mundloch des genannten Hauptstollens bestimmt worden ist, der nach der entsprechenden Mutung für immer den Namen\n\nTiefer Georg-Stollen\n\ntragen soll, samt seinem ganzen Verlauf (der zum Beispiel bis in das Feld der Grube Caroline, wo er 162 Lachter Tiefe unter Tage und 80 Lachter unter dem dort vorhandenen sogenannten Dreizehn-Lachter-Stollen einbringt, 4910 Lachter lang werden wird) bis in den Rosenhöfer und den Burgstätter, auch den Silbernaaler und den Kommunion-Hauptzug, und samt den auf diesem Verlauf nötigen Lichtlöchern, deren tiefstes 113 Lachter tief werden wird; und nachdem auch über die Dinge, die mit dem Stollenvortrieb zusammenhängen, ein Rezess zwischen den beiden Kommunion-Herrscherhäusern geschlossen und in den Bergämtern ordnungsgemäß bekannt gemacht worden ist: so steht der Ausführung dieses für den ganzen Harz wichtigen Werks nun nichts mehr im Weg, und mir obliegt eines der angenehmsten Geschäfte, das ich jetzt zu erledigen im Begriff bin: nämlich mit dem ersten Schlag den Anfang der eigentlichen Handarbeit zu machen.",
         note="Die Zahlen des Plans: 4910 Lachter lang, an der Caroline 162 Lachter unter Tage, 80 Lachter tiefer als der bisher tiefste Stollen; das tiefste Lichtloch 113 Lachter. Ein Lachter ist knapp zwei Meter (nach der neueren Literatur); der Stollen sollte also rund zehn Kilometer lang werden. Lichtlöcher sind Schächte von oben, von denen aus man den Stollen gleichzeitig an mehreren Stellen vortreiben und belüften kann. Lasius nennt 1789 für das dritte Lichtloch 111 Lachter (Vortrieb [1]). Der Name steht im Druck in großer Schrift für sich, wie auf einem Schild."),
    dict(n=5, titel="Der erste Schlag und ‚Glück auf!‘", pg="Reden 1777, S. 11–12", lang="nhd",
         orig="Nicht nur der Anfang der Arbeit ist nun glücklich gemacht, sondern ich habe auch die erste Stuffe in den zum ewigen Andenken dieser Handlung allhier befestigten Stein gehauen, von welcher anzurechnen denen hier gegenwärtigen Bergleuten von dem Herrn Oberbergmeister Steltzner in wenigen Minuten zum ersten mahle wird verdungen werden.\n\nGroßer, unbegreiflich großer Schöpfer unzählbarer Millionen himmlischer Körper und auch unseres Weltkörpers, wovon diese von uns bewohnten Gebürge ein gar kleines Theil sind! Keinesweges hast Du ohne Absicht diejenigen Schätze in sie geleget, deren Aufsuchung und Vorbereitung zum fernern menschlichen Nutzen unser Berufsgeschäfte ist: Du willst es sicher, daß sie aus ihren Lagerstätten genommen und zum Nutzen Deiner vernünftigen Geschöpfe verwandt werden sollen. Hilf also, daß die nun angefangene Arbeit, welche wir für ein Haupthülfsmittel zu Erreichung unsers, auf die Erhaltung mehrerer tausend Menschen zugleich abzielenden, Endzwecks erachten, einen erwünschten schleunigen Fortgang und glückliche Endschaft haben möge!\n\nKein Mißverständnis müsse ihr jemals einen Aufenthalt machen!\n\nGlück auf!",
         en="Nicht nur ist der Anfang der Arbeit nun glücklich gemacht, sondern ich habe auch die erste Stufe in den Stein gehauen, der zum ewigen Andenken an diese Handlung hier befestigt ist; von ihr an gerechnet wird Herr Oberbergmeister Stelzner den hier anwesenden Bergleuten in wenigen Minuten zum ersten Mal die Arbeit verdingen.\n\nGroßer, unbegreiflich großer Schöpfer unzählbarer Millionen Himmelskörper und auch unseres Weltkörpers, von dem diese Gebirge, die wir bewohnen, nur ein ganz kleiner Teil sind! Keineswegs hast du ohne Absicht die Schätze in sie gelegt, deren Aufsuchen und Aufbereiten für den weiteren menschlichen Nutzen unser Beruf ist: Du willst gewiss, dass sie aus ihren Lagerstätten genommen und zum Nutzen deiner vernünftigen Geschöpfe verwendet werden. Hilf also, dass die nun begonnene Arbeit, die wir für ein Haupthilfsmittel halten, um unser Ziel zu erreichen, das auf die Erhaltung mehrerer tausend Menschen zugleich zielt, einen erwünschten, schnellen Fortgang und ein glückliches Ende haben möge!\n\nKein Missverständnis möge sie jemals aufhalten!\n\nGlück auf!",
         note="Der Berghauptmann haut die erste ‚Stufe‘, ein Stück Gestein, aus einem Gedenkstein; dann übernimmt der Oberbergmeister und ‚verdingt‘ die Arbeit, das heißt: Er vergibt sie den Bergleuten im Gedinge, als Akkord nach geschaffter Strecke. Der feierliche Akt und der Arbeitsvertrag folgen im Abstand von ‚wenigen Minuten‘. Das Gebet begründet den Bergbau mit dem Willen Gottes und sein Ziel mit der ‚Erhaltung mehrerer tausend Menschen‘. Der letzte Wunsch, ‚Kein Mißverständnis‘, ist nach sechs Jahren Verhandlung zwischen zwei Höfen wohl auch politisch gemeint (Rede [3]). Horstig sah 1800 eine Inschrift am Mundloch, die den Herzog von York als Grundsteinleger nannte (Vortrieb [3])."),
]

PREDIGT = [
    dict(n=1, titel="‚Von diesem Tage an will ich Seegen geben‘", pg="Dahme 1777, S. 17–19", lang="nhd",
         orig="Mein Text bestehet aus wenigen Worten, die aber Worte GOttes sind. Wir finden ihn in dem zweyten Capitel der Weissagungen Haggai am Ende des zwanzigsten Verses. GOtt sprach:\n\nVon diesem Tage an will ich Seegen geben.\n\nVon diesem Tage an (es war der vierundzwanzigste des neunten Jüdischen Monats) will ich Seegen geben! Mit welcher Freude muß nicht diese Verheissung von den Israeliten, die mit Dürre, Brandkorn und Hagel waren heimgesucht worden und damahls aus dem Anblicke ihres Landes noch keine Hofnung zu einem bessern Jahre schöpfen konnten, (der Saame lag noch in der Scheuren: es trug noch nichts, weder Weinstöcke, Feigenbäume, Granatbäume, noch Oelbäume,) mit welcher herzlichen und dankbaren Freude, sage ich, muß diese Verheissung GOttes von jenem Volke nicht seyn aufgenommen worden? von ihnen, die wußten, daß des HErrn Wort wahrhaftig ist, daß er hält, was er zusaget? Und wie? wenn nun GOtt jetzt zu uns spräche: Von dem gestrigen sechsundzwanzigsten Tage eures siebenten Monats an, da der erste Schlag zum feyerlichen Anfange des tiefen Stollens von eurem Oberhaupte im Namen des Königs geschahe, von diesem Tage an will ich Seegen geben. Alle die reizenden Hofnungen, die ihr euch von dieser Unternehmung machet, sollen erfüllt werden. Der Bergbau soll sich noch weit mehr aufnehmen. Es sollen die ergiebigsten, besten Zeiten kommen, solche Zeiten, als jene, von denen ihr den Wohlstand eurer Cassen anrechnet! — Wie? wenn GOtt durch einen Propheten so jetzt zu uns spräche: würde uns denn nicht ebenfalls die sanfteste Wonne einnehmen? Würde nicht einer dem andern mit Frohlocken Glück wünschen, der Ehemann seiner Gattin, der Vater seinen Söhnen, die Mutter ihren Töchtern, der Freund dem Freunde, der Nachbar dem Nachbar?",
         en="Mein Text besteht aus wenigen Worten, aber es sind Gottes Worte. Wir finden ihn im zweiten Kapitel des Propheten Haggai am Ende des zwanzigsten Verses. Gott sprach:\n\nVon diesem Tage an will ich Segen geben.\n\nVon diesem Tag an (es war der vierundzwanzigste des neunten jüdischen Monats) will ich Segen geben! Mit welcher Freude muss diese Verheißung von den Israeliten aufgenommen worden sein, die von Dürre, Brandkorn und Hagel heimgesucht worden waren und damals beim Anblick ihres Landes noch keine Hoffnung auf ein besseres Jahr schöpfen konnten (die Saat lag noch in der Scheune; noch trug nichts, weder Weinstöcke noch Feigenbäume, Granatbäume oder Ölbäume) – mit welcher herzlichen, dankbaren Freude, sage ich, muss jenes Volk diese Verheißung Gottes aufgenommen haben, sie, die wussten, dass das Wort des Herrn wahr ist und dass er hält, was er zusagt! Und wie? Wenn Gott nun zu uns spräche: Vom gestrigen sechsundzwanzigsten Tag eures siebten Monats an, an dem euer Oberhaupt im Namen des Königs den ersten Schlag zum feierlichen Anfang des tiefen Stollens getan hat, von diesem Tag an will ich Segen geben. Alle die schönen Hoffnungen, die ihr euch von diesem Unternehmen macht, sollen erfüllt werden. Der Bergbau soll noch viel mehr aufblühen. Es sollen die ergiebigsten, besten Zeiten kommen, solche Zeiten wie jene, von denen ihr den Wohlstand eurer Kassen herleitet! – Wie? Wenn Gott jetzt durch einen Propheten so zu uns spräche, würde uns dann nicht ebenfalls die sanfteste Wonne erfüllen? Würde nicht einer dem andern jubelnd Glück wünschen, der Ehemann seiner Frau, der Vater seinen Söhnen, die Mutter ihren Töchtern, der Freund dem Freund, der Nachbar dem Nachbarn?",
         note="Die Predigt hielt der Generalsuperintendent Georg Christoph Dahme am Tag nach dem ersten Schlag, Sonntag, dem 27. Juli 1777 (dem 9. Sonntag nach Trinitatis), ‚auf Befehl der Regierung‘ in Clausthal. Er legt das Datum des Propheten Haggai auf das Datum des Stollens: der 26. des siebten Monats, der 26. Juli. Das ‚Wie? wenn‘ ist ein Konjunktiv, kein Versprechen; worauf Dahme hinauswill, steht in der nächsten Einheit. Aus dem Satz stammt ein zweiter Titelvorschlag für das Begleitspiel."),
    dict(n=2, titel="‚Gleichwohl ist […] unser Glück ehemahls grösser gewesen‘", pg="Dahme 1777, S. 19–21", lang="nhd",
         orig="Und nicht wir allein würden uns freuen: alle unsre Bergbrüder, (die zumtheil heute für unser Werk auch öffentlich beten *) würden sich mit uns freuen. Bis in die Ebenen, bis in die Residenz würde sich unsre Freude verbreiten, die höchsten Räthe des Königs, die Säulen unsers Staats, umfassen, jeden redlichen Landesbürger durchwallen, über das Meer, selbst bis in die Brust des besten Königs, der das nun angefangene und nach seinem Namen genennete Werk mit solchem wirksamen Eifer befördert hat und dem unsre Wohlfarth so theuer ist […]!\n\nZwar ist unser Zustand (gelobet sey GOtt!) noch keinesweges bejammernswürdig. Der HErr hat uns seinen Seegen bisher nicht entzogen. Unsre Arbeit ist noch nicht vergeblich gewesen: wir dürfen nicht klagen. Nur erst noch in den letzten Jahren sind hier Verbesserungen getroffen, die den jährlichen Gewinn zum Erstaunen erhöhet haben und den Namen ihres Stifters durch ihre fortdaurende Wohlthätigkeit unsern spätesten Nachkommen noch werth erhalten werden. ** Gleichwohl ist in Ansehung der Gruben unser Glück ehemahls grösser gewesen. Verschiedene, die sonst Ausbeute gaben, fordern jetzt Zubusse, oder geben doch nichts: andere sind liegen geblieben: noch andere könnten ohne eine solche Hülfe, als der neue Stollen ihnen verschaffen wird, nicht lange mehr fortgebauet werden.\n\n* Zu St. Andreasberg, Altenau und Lerbach geschahe dies.\n** Die Hohe-Ofen-Arbeit auf der Hütte, ein Werk des Herrn Geheimte-Cammerraths und Berghauptmanns von Reden.",
         en="Und nicht nur wir würden uns freuen: alle unsere Bergbrüder (die zum Teil heute auch öffentlich für unser Werk beten *) würden sich mit uns freuen. Bis in die Ebenen, bis in die Residenz würde sich unsere Freude verbreiten, die höchsten Räte des Königs, die Säulen unseres Staates, erfassen, jeden redlichen Landesbürger durchströmen, über das Meer bis in die Brust des besten Königs, der das nun begonnene und nach seinem Namen benannte Werk mit so wirksamem Eifer gefördert hat und dem unser Wohl so teuer ist […]!\n\nZwar ist unser Zustand (Gott sei gelobt!) noch keineswegs beklagenswert. Der Herr hat uns seinen Segen bisher nicht entzogen. Unsere Arbeit ist noch nicht vergeblich gewesen; wir dürfen nicht klagen. Erst in den letzten Jahren sind hier Verbesserungen eingeführt worden, die den jährlichen Gewinn erstaunlich erhöht haben und den Namen ihres Urhebers durch ihre fortdauernde Wohltat noch unseren spätesten Nachkommen wert halten werden. ** Gleichwohl ist unser Glück, was die Gruben angeht, früher größer gewesen. Manche, die sonst Ausbeute gaben, verlangen jetzt Zubuße oder geben doch nichts; andere sind liegen geblieben; wieder andere könnten ohne eine solche Hilfe, wie sie ihnen der neue Stollen verschaffen wird, nicht mehr lange weiter betrieben werden.\n\n* In St. Andreasberg, Altenau und Lerbach geschah dies.\n** Die Hochofenarbeit auf der Hütte, ein Werk des Herrn Geheimen Kammerrats und Berghauptmanns von Reden.",
         note="Die Predigt sagt nüchterner als die Rede, wie es um die Gruben stand: Zubuße statt Ausbeute, liegen gebliebene Gruben. Zugleich schmeichelt sie dem Berghauptmann in einer Fußnote für seine Hochöfen. Die Freude reicht bis zum König ‚über das Meer‘: Georg III. regierte von London aus und hat Hannover nie betreten (nach der neueren Literatur). Ausgelassen [‚…‘] ist der Satz über die ‚unzuvergleichende Landesmutter‘."),
    dict(n=3, titel="‚Mit Zuverlässigkeit nicht!‘ – kein Wunder im Berg", pg="Dahme 1777, S. 21–23", lang="nhd",
         orig="Ob wir denn hoffen können, daß dies sein Rath sey? — Mit Zuverlässigkeit nicht, meine Geliebten; mit Zuverlässigkeit nicht! Wer hat des HErrn Sinn erkannt? Seine Gerichte sind oft unbegreiflich, seine Wege unerforschlich, seine Gedanken anders, als der Menschen Gedanken. Er läßt wohl die sichersten Erwartungen nicht eintreffen: die Geschichte liefert davon aus allen Zeitläuften merkwürdige Beyspiele. So viel ist indessen gewiß, daß wir das völligste Recht haben, es für höchst wahrscheinlich zu halten, daß GOtt uns durch diese neue Unternehmung seegnen könne. Es ist nicht ein unüberlegtes oder von Unkundigen angerathenes und beschlossenes Werk: es ist lange und reiflich erwogen, von einer Versammlung, die nicht allein die dazu durchaus nöthige Kenntniß und Erfahrung hat, sondern in der sogar Männer von ausserordentlicher Fähigkeit, von dem durchdringendsten Verstande, und der gesündesten, richtigsten Beurtheilung sitzen. Die Hofnung, daß durch dieses Werk aus den schon bearbeiteten Gruben neue Schätze können geschöpfet werden, ist höchst vernünftig. Auch kann es seyn, daß wir dadurch auf neue, noch verborgene, reiche Gänge geleitet werden: denn ohne Zweifel sind solche noch da; ohne Zweifel sind noch nicht alle gefunden. Die noch nicht durchsuchte Masse ist zu groß und die Zeit, seitdem der Harz bebauet ist, zu kurz: noch können wohl nicht alle Adern dieses wunderbaren Körpers entdeckt seyn. Wir dürfen also hoffen, daß GOtt uns durch unsern tiefen Stollen seegnen könne, ohne in den Gegenden, durch die er gehen wird, neue reiche Gänge, oder in den bisherigen Gruben neue reiche Tiefen, nun erst zu erschaffen, das ist, ohne Wunder zu thun. Denn einen solchen Seegen dürfen wir nicht erwarten: er ist uns nicht verheissen. Die Erde ist gemacht: die Gesetze der Natur sind da: auf eine Art, wie diese seyn würde, weicht GOtt davon jetzt nicht ab.",
         en="Ob wir also hoffen können, dass dies sein Ratschluss ist? – Mit Gewissheit nicht, meine Lieben, mit Gewissheit nicht! Wer hat den Sinn des Herrn erkannt? Seine Gerichte sind oft unbegreiflich, seine Wege unerforschlich, seine Gedanken anders als die der Menschen. Er lässt wohl die sichersten Erwartungen nicht eintreffen; die Geschichte liefert dafür aus allen Zeiten bemerkenswerte Beispiele. Soviel ist jedoch gewiss, dass wir allen Grund haben, es für höchst wahrscheinlich zu halten, dass Gott uns durch dieses neue Unternehmen segnen kann. Es ist kein unüberlegtes oder von Unkundigen angeratenes und beschlossenes Werk; es ist lange und gründlich erwogen worden von einer Versammlung, die nicht nur die dafür unbedingt nötige Kenntnis und Erfahrung hat, sondern in der sogar Männer von außerordentlicher Fähigkeit, von durchdringendstem Verstand und gesündestem, richtigstem Urteil sitzen. Die Hoffnung, dass durch dieses Werk aus den schon bearbeiteten Gruben neue Schätze gewonnen werden können, ist höchst vernünftig. Es kann auch sein, dass wir dadurch auf neue, noch verborgene reiche Gänge geführt werden, denn ohne Zweifel gibt es sie noch, ohne Zweifel sind noch nicht alle gefunden. Die noch nicht durchsuchte Masse ist zu groß und die Zeit, seit der Harz bebaut wird, zu kurz; es können wohl noch nicht alle Adern dieses wunderbaren Körpers entdeckt sein. Wir dürfen also hoffen, dass Gott uns durch unseren tiefen Stollen segnen kann, ohne in den Gegenden, durch die er führen wird, neue reiche Gänge oder in den bisherigen Gruben neue reiche Tiefen erst zu erschaffen, das heißt, ohne ein Wunder zu tun. Denn einen solchen Segen dürfen wir nicht erwarten; er ist uns nicht verheißen. Die Erde ist gemacht, die Naturgesetze sind da; auf eine solche Art weicht Gott jetzt nicht von ihnen ab.",
         note="Eine Predigt der Aufklärung: Dahme verspricht nichts. Der Segen, auf den man hoffen darf, wirkt durch Naturgesetze und durch die Klugheit des Bergamts, nicht durch Wunder; das Erz ist da oder nicht. Bemerkenswert ist das Argument, das Werk sei ‚nicht ein unüberlegtes oder von Unkundigen angerathenes‘: Hundert Jahre nach Leibniz (Modul 5) und den Erfindern des 17. Jahrhunderts (Modul 3) wird der Stollen ausdrücklich als Plan der Fachleute gerechtfertigt."),
    dict(n=4, titel="Treue in der Arbeit, und die Armenkasse", pg="Dahme 1777, S. 50–52", lang="nhd",
         orig="Ueberdies empfehle ich einem jeden besonders die Treue in der Arbeit. Der Christ thut auch im verborgenen recht: er dünkt sich nie im verborgenen. Der Christ hat an seinem Gewissen immer eine Welt um sich: dies ist ihm mehr, als eine Welt! * Und ist nicht GOtt an allen Orten, auch da, wo kein Auge uns beobachtet, um uns? Und sollten wirs je wagen, das vor seinem Angesichte zu thun, was wir vor dem Angesichte unsrer Vorgesetzten nicht thun würden? Ist nicht jede Untreue, sie heisse, wie sie wolle, sie sey verkleidet, wie sie wolle, sie sey auch noch so hergebracht, Entwendung? Und drücket diese nicht ein Fluch GOttes? […]\n\nDa ich wohl nicht leicht eine so grosse Anzahl von Gliedern meiner geliebtesten Gemeine wieder vor mir sehen werde: so will ich doch auch das noch sagen, was ich schon längst einmahl habe sagen wollen. Man hat mir geklaget, daß die Sammlung für unsre Armen an den Sonnabenden gegenwärtig beträchtlich geringer wäre, als sie anfangs gewesen ist: ein grosser Schade für unsre Armencasse! Aber jetzt sind ja, Gottlob, keine theuren Zeiten und vielleicht hat uns GOtt gestern noch eine neue Quelle der Nahrung geöfnet: werdet Ihr es denn wohl für unbillig halten, wenn ich Euch bitte, den Beytrag wieder zu vermehren? und werden nicht diejenigen vorzüglich meine Bitte willig erfüllen, welchen GOtt Ueberfluß geschenket hat? Ich hoffe dies desto freudiger, da ich die Versicherung unsrer würdigen Stadtobrigkeit hinzusetzen kann, daß der Hausbetteley immer noch mehr gesteuret werden solle. […] Nehmet Euch indeß nicht bloß der öffentlichen Armen an: gedenket auch der verborgenen, der verschämten, derer, welchen Abkunft oder Stand nicht zulassen, Euch anzusprechen.\n\n* Nullum theatrum virtuti conscientia majus est. Cic.",
         en="Außerdem empfehle ich jedem besonders die Treue in der Arbeit. Der Christ tut auch im Verborgenen recht; er hält sich nie für verborgen. Der Christ hat an seinem Gewissen immer eine Welt um sich, und das ist ihm mehr als eine Welt! * Und ist Gott nicht an allen Orten um uns, auch dort, wo kein Auge uns beobachtet? Und sollten wir es je wagen, vor seinem Angesicht zu tun, was wir vor den Augen unserer Vorgesetzten nicht tun würden? Ist nicht jede Untreue, wie sie auch heiße, wie sie auch verkleidet, wie hergebracht sie auch sei, eine Entwendung? Und lastet auf ihr nicht ein Fluch Gottes? […]\n\nDa ich wohl nicht so bald wieder eine so große Zahl von Gliedern meiner geliebtesten Gemeinde vor mir sehen werde, will ich doch auch das noch sagen, was ich schon lange einmal sagen wollte. Man hat mir geklagt, dass die Sammlung für unsere Armen an den Samstagen jetzt beträchtlich geringer sei als anfangs: ein großer Schaden für unsere Armenkasse! Aber jetzt sind ja, Gott sei Dank, keine teuren Zeiten, und vielleicht hat uns Gott gestern noch eine neue Quelle der Nahrung eröffnet: Werdet ihr es also für unbillig halten, wenn ich euch bitte, den Beitrag wieder zu erhöhen? Und werden nicht vor allem diejenigen meine Bitte gern erfüllen, denen Gott Überfluss geschenkt hat? Ich hoffe das umso freudiger, als ich die Zusicherung unserer würdigen Stadtobrigkeit hinzufügen kann, dass dem Betteln an den Haustüren noch mehr gewehrt werden soll. […] Nehmt euch aber nicht nur der öffentlichen Armen an; denkt auch an die verborgenen, die verschämten, an diejenigen, denen Herkunft oder Stand nicht erlauben, euch anzusprechen.\n\n* Das Gewissen ist für die Tugend die größte Bühne. Cicero.",
         note="Was die Predigt von den Zuhörern verlangt: Treue in der Arbeit ‚auch da, wo kein Auge uns beobachtet‘, also unter Tage, wo der Steiger nicht immer ist. Untreue nennt Dahme ‚Entwendung‘, ‚auch noch so hergebracht‘: Er spielt offenbar auf Gewohnheiten an, Erz oder Material mitzunehmen, ohne sie zu benennen. Dann die Armenkasse: Die Sammlung sei zurückgegangen; zugleich soll dem Betteln an den Häusern ‚gesteuret‘ werden. Wer in Clausthal arm war, sagt Dahme nicht; dass es viele waren, setzt er voraus. Ausgelassen [‚…‘] sind ein Absatz über Redlichkeit und ein Satz über die Mildtätigkeit. Die Fußnote zitiert Cicero (Tusculanae disputationes II, 64)."),
    dict(n=5, titel="‚Ohne Unglücksfälle; ja, Vater, bewahre das Leben‘", pg="Dahme 1777, S. 54–55", lang="nhd",
         orig="HErr, den wir als den Ursprung alles Guten, dessen wir bedürfen und das wir uns wünschen, mit Ueberzeugung verehren, wir, die Glieder dieser Gemeine, die Einwohner dieser Stadt, kommen zu Dir mit der, uns, dem ganzen Harze, den ersten Räthen des Königs, diesem Landesvater selbst, so angelegentlichen Bitte, daß Du den Tiefen-Stollen-Bau, der gestern, in Deinem Namen, feyerlich angefangen ist, beglücken, daß Du ihn reichlich seegnen wollest. Daß er erfunden wurde; daß alle Hindernisse, die sich ihm entgegen setzten, weggeräumt sind, daß man zur Ausführung desselben die Mittel siehet, hat; daß er jetzt wirklich unternommen ist; dies alles haben wir Dir schon zu danken und danken wir Dir herzlich. Laß aber dieses Werk nun auch gelingen. Wehre allem, was es aufhalten, was es wohl gar wieder vernichten könnte: fördere es: die Arbeit gehe ununterbrochen fort, und ohne Unglücksfälle; ja, Vater, bewahre das Leben und die Gesundheit unsrer Brüder! Dies Werk sey auch von dem größten Nutzen! Alle Hofnungen, die wir uns davon machen, werden unter der Klugheit, der Wachsamkeit und dem Fleisse derer, die ihm vorstehen, erfüllet: der Harz bekomme dadurch ein neues Leben: Nahrung, Freude, Wohlhabenheit werden dadurch befestiget, vermehret: noch für unsre entfernteste Nachkommenschaft habe es die besten Folgen!",
         en="Herr, den wir als Ursprung alles Guten, dessen wir bedürfen und das wir uns wünschen, aus Überzeugung verehren: Wir, die Glieder dieser Gemeinde, die Einwohner dieser Stadt, kommen zu dir mit der Bitte, die uns, dem ganzen Harz, den ersten Räten des Königs und diesem Landesvater selbst so am Herzen liegt, dass du den Bau des tiefen Stollens, der gestern in deinem Namen feierlich begonnen wurde, glücken lassen und reichlich segnen mögest. Dass er erdacht wurde, dass alle Hindernisse, die sich ihm entgegenstellten, aus dem Weg geräumt sind, dass man die Mittel zu seiner Ausführung sieht und hat, dass er jetzt wirklich begonnen ist: Das alles verdanken wir schon dir, und wir danken dir herzlich. Lass dieses Werk nun aber auch gelingen. Wehre allem, was es aufhalten oder gar wieder vernichten könnte; fördere es: Die Arbeit gehe ohne Unterbrechung voran, und ohne Unglücksfälle; ja, Vater, bewahre das Leben und die Gesundheit unserer Brüder! Dieses Werk sei auch von größtem Nutzen! Alle Hoffnungen, die wir uns davon machen, mögen unter der Klugheit, der Wachsamkeit und dem Fleiß derer, die es leiten, erfüllt werden; der Harz bekomme dadurch ein neues Leben; Nahrung, Freude, Wohlstand mögen dadurch gefestigt und vermehrt werden; noch für unsere fernsten Nachkommen habe es die besten Folgen!",
         note="Die einzige Stelle in allen Texten zum Stollen, die von Unglücksfällen spricht, und sie steht in einem Gebet: ‚bewahre das Leben und die Gesundheit unsrer Brüder‘. Die Gefahr war allen bewusst, die am Sonntag in der Kirche saßen. Ob und wie viele Bergleute in den Jahren des Vortriebs verunglückten, sagt keine der hier abgedruckten Quellen; wir haben dafür keinen gedruckten Beleg gefunden. Im weiteren Gebet bittet Dahme für Reden und den Oberbergmeister namentlich, dass sie das Ende des Werks noch sehen mögen."),
]

BAU = [
    dict(n=1, titel="1789: ‚für die Ewigkeit geführet‘", pg="Lasius 1789, S. 51–52", lang="nhd",
         orig="Nun muß ich auch noch der kostbarsten von allen Harzischen Wasserleitungen erwähnen, die, wenn sie dereinst wird vollendet seyn, als ein sehr wichtiges Werk vom ersten Range, allgemeine Aufmerksamkeit verdient. Es ist dieses der im Jahre 1777. angefangene tiefe Georgstollen.\n\nSchon seit langen Jahren sind die zwey Hauptstollen zu Clausthal und Zellerfeld, nemlich der 19 Lachterstollen und der bisherige tiefste, der 13 Lachterstollen, die beyde neben der Bergstadt Wildemann zu Tage ausgehen, vorhanden und hinlänglich gewesen. Allein, da jetzo die Gruben so tief sind und immer noch tiefer werden, so können die Künste die Wasser nicht alle gewältigen und zu der erforderlichen Höhe auf den Stollen heraufheben und ausgießen. Deswegen hat man gleich unterhalb Grund den tiefen Georgstollen angesetzt, den man durch verschiedene ersoffene Gruben des Silbernen Aalerzuges, durch den Rosenhofer Zug, unter Clausthal durch bis zur Caroline und neuen Benedicte hinaufführen wird. Seine ganze Länge wird nahe an 5000 Lachter betragen. Außer den Grubenschächten, die dem Stollen als Lichtlöcher dienen, sind noch besonders sechs Schächte alter verlaßner Gruben zu Lichtlöchern niedergetrieben, deren eins, nemlich das dritte, 111 Lachter Tiefe hat. Auf der Grube Dorothea und Caroline wird er 162 Lachter Teufe einbringen, also 80 Lachter mehr als der bisherige tiefeste Stollen; und damit er für die Ewigkeit geführet werde, wird er an den Stellen, wo das Gestein nicht fest genug ist, in einer elliptischen Figur bloß mit Steinen, ohne alle Mauerspeise ausgemauert.",
         en="Nun muss ich auch noch die kostspieligste aller Harzer Wasserleitungen erwähnen, die, wenn sie einmal vollendet sein wird, als ein sehr wichtiges Werk ersten Ranges allgemeine Aufmerksamkeit verdient. Es ist der 1777 begonnene Tiefe Georg-Stollen.\n\nSchon seit langen Jahren gab es die zwei Hauptstollen von Clausthal und Zellerfeld, nämlich den Neunzehn-Lachter-Stollen und den bisher tiefsten, den Dreizehn-Lachter-Stollen, die beide neben der Bergstadt Wildemann zutage austreten, und sie reichten aus. Da aber die Gruben jetzt so tief sind und immer noch tiefer werden, können die Künste nicht mehr alles Wasser bewältigen und bis zur nötigen Höhe auf den Stollen heben und ausgießen. Deshalb hat man gleich unterhalb von Grund den Tiefen Georg-Stollen angesetzt, den man durch mehrere abgesoffene Gruben des Silbernaaler Zugs, durch den Rosenhöfer Zug, unter Clausthal hindurch bis zur Caroline und zur Neuen Benedicte hinaufführen wird. Seine ganze Länge wird nahezu 5000 Lachter betragen. Außer den Grubenschächten, die dem Stollen als Lichtlöcher dienen, sind noch eigens sechs Schächte alter, verlassener Gruben zu Lichtlöchern abgeteuft worden, von denen eines, nämlich das dritte, 111 Lachter tief ist. Auf den Gruben Dorothea und Caroline wird er 162 Lachter Tiefe einbringen, also 80 Lachter mehr als der bisher tiefste Stollen; und damit er für die Ewigkeit angelegt ist, wird er an den Stellen, wo das Gestein nicht fest genug ist, in elliptischer Form allein mit Steinen, ohne jeden Mörtel, ausgemauert.",
         note="Zwölf Jahre nach dem ersten Schlag ist der Stollen ‚noch nicht ganz vollendet‘ (Vortrieb [2]). Lasius bestätigt Redens Zahlen und ergänzt, was 1777 noch Plan war: sechs alte Schächte als Lichtlöcher, eine Mauerung ‚ohne alle Mauerspeise‘, also ohne Mörtel, in elliptischer Form. Die ‚ersoffenen Gruben‘ des Silbernaaler Zugs sind genau die verlassenen Züge, von denen Reden sprach (Rede [1]). Lasius rechnet den Stollen unter die ‚Wasserleitungen‘, in eine Reihe mit Teichen und Gräben (Modul 4)."),
    dict(n=2, titel="Das Profil des Harzes, mit drei Stollen", pg="Lasius 1789, S. 37–38", lang="nhd",
         orig="Aus obiger Tabelle habe ich nun beygehendes Profil der Harzgebirge nach ihrer Erhöhung über der Fläche der Ostsee entworfen, und dazu die Puncte Windehausen, Grund, die drey Lichtlöcher des tiefen Georgstollens und die Grube Thurm Rosenhof zu Clausthal, nach dem Nivellement des Markscheiders Herrn Länge zu Clausthal aufgetragen. Nach diesem ist auch der bey dem ersten Lichtloche zu Tage ausgehende Frankenscharner Stollen: der zu Wildemann ausgehende bis jetzo der tiefeste, nemlich der Dreyzehn-Lachterstollen (hier nur durch eine punctirte Linie angedeutet) imgleichen der jetzt noch nicht ganz vollendete tiefe Georgstollen, so bey der Bergstadt Grund zu Tage ausgeht; mit ins Profil gebracht. Nicht weniger ist auch der tiefeste Punct, zu welchem man bis jetzt auf dem Harze abgesunken, durch den Thurm Rosenhofer Schacht angedeutet, daß man also die Höhe des besagten tiefesten Puncts, über der Fläche der Ostsee, darnach übersehen kann.",
         en="Aus der obigen Tabelle habe ich nun das beigefügte Profil der Harzgebirge nach ihrer Höhe über dem Spiegel der Ostsee entworfen und dazu die Punkte Windehausen, Grund, die drei Lichtlöcher des Tiefen Georg-Stollens und die Grube Turm Rosenhof in Clausthal nach dem Nivellement des Markscheiders Herrn Länge in Clausthal eingetragen. Danach ist auch der Frankenscharner Stollen, der beim ersten Lichtloch zutage austritt, der in Wildemann austretende, bisher tiefste, nämlich der Dreizehn-Lachter-Stollen (hier nur durch eine punktierte Linie angedeutet), und ebenso der noch nicht ganz vollendete Tiefe Georg-Stollen, der bei der Bergstadt Grund zutage austritt, ins Profil aufgenommen. Ebenso ist der tiefste Punkt, bis zu dem man bisher im Harz abgeteuft hat, durch den Schacht Turm Rosenhof angedeutet, so dass man die Höhe dieses tiefsten Punkts über dem Spiegel der Ostsee daran ablesen kann.",
         note="Lasius' Kupfertafel ‚Profil der Harz Gebirge‘ (Tafel in diesem Abschnitt) zeigt den Harz im Längsschnitt vom Meeresspiegel bis zum Brocken, und darin, übereinander, die drei Stollen: Frankenscharner, Dreizehn-Lachter, Tiefer Georg. Darunter reicht nur noch ein Strich, der Schacht Turm Rosenhof, als tiefster Punkt. Die Höhen hatte Lasius nach dem Luftdruck berechnet (seine Tabelle nennt das ‚mittlere Gewicht der Athmosphäre‘) und auf die Ostsee bezogen; die Lage der Stollen übernahm er vom Clausthaler Markscheider. Die Grafik dieses Moduls folgt seinem Schnitt."),
    dict(n=3, titel="1800: Linden am Mundloch", pg="Horstig 1805, S. 147–148", lang="nhd",
         orig="Den 2. October.\n\nBey trübem Himmel giengen wir heute nach Grund, in die letzte Bergstadt des Harzes, um den großen Georgstollen zu sehen, der vor kurzen bey seinem völligen Durchbruche mit einer außerordentlichen Feyerlichkeit eingeweiht worden war. Schön kündigt sich dieser Georgstollen an. Eine vielfache Reihe junger Linden fasset den Ausfluß der unterirdischen Harzgewässer ein, die über zwey Stunden weit von Clausthal hier abgeleitet werden. Eine Inschrift bewahrt hier die der bergmännischen Nachwelt denkwürdige Namen von Rheden und Stelzner, und verkündigt zugleich, daß der Herzog von York den Grundstein zu diesem größten aller Stollen gelegt habe.\n\nAehnlich dem wilden Manne liegt die an sich nicht viel bedeutende Stadt Grund tief in die Berge versenkt. Der Harz über ihr raucht und dampft wie ein siedender Kessel; während daß im auffallendsten Contraste die Sonne freundliche Strahlen ins Land hineinwirft, welches wir von der Höhe vor Grund nach langen Entbehrnissen zum erstenmal wieder erblicken. Und nun lebe wohl, graubärtiger Harz, von uns mit Sehnsucht empfangen und mit Wehmuth verlassen.",
         en="Den 2. Oktober.\n\nBei trübem Himmel gingen wir heute nach Grund, der letzten Bergstadt des Harzes, um den großen Georg-Stollen zu sehen, der vor Kurzem bei seinem vollständigen Durchschlag mit einer außerordentlichen Feierlichkeit eingeweiht worden war. Schön kündigt sich dieser Georg-Stollen an. Eine mehrfache Reihe junger Linden fasst den Ausfluss der unterirdischen Harzgewässer ein, die hier über zwei Stunden weit von Clausthal abgeleitet werden. Eine Inschrift bewahrt hier die für die bergmännische Nachwelt denkwürdigen Namen von Reden und Stelzner und verkündet zugleich, dass der Herzog von York den Grundstein zu diesem größten aller Stollen gelegt habe.\n\nÄhnlich wie Wildemann liegt die an sich nicht sehr bedeutende Stadt Grund tief in die Berge versenkt. Der Harz über ihr raucht und dampft wie ein siedender Kessel, während im auffälligsten Gegensatz die Sonne freundliche Strahlen ins Land wirft, das wir von der Höhe vor Grund nach langer Entbehrung zum ersten Mal wieder erblicken. Und nun lebe wohl, graubärtiger Harz, von uns mit Sehnsucht empfangen und mit Wehmut verlassen.",
         note="Carl Gottlieb Horstig reiste mit seiner Frau ab dem 31. August 1800 durch den Harz; den 2. Oktober verbrachten sie in Grund. Der Stollen war ‚vor kurzen‘ durchgeschlagen und gefeiert worden; nach der neueren Literatur wurde er 1799 vollendet. Was der Reisende sieht, ist ein Ort, kein Bergwerk: Linden, eine Inschrift, Wasser, das ausfließt. Die Inschrift nennt nach Horstig den Herzog von York, einen Sohn Georgs III., als Grundsteinleger. Das widerspricht nicht notwendig Reden, der 1777 den ‚ersten Schlag‘ selbst tat (Rede [5]); ob der Herzog später einen Grundstein für das gemauerte Mundloch legte, können wir aus diesen Quellen nicht klären. Horstig schreibt ‚Rheden‘. Von den Bergleuten, die über zwanzig Jahre an dem Stollen arbeiteten, steht auf der Inschrift, soweit er sie wiedergibt, kein Name."),
]

doc = {
    "id": "stollen",
    "titel": "Der Tiefe Georg-Stollen",
    "autor": "Claus Friedrich von Reden und Georg Christoph Dahme (1777), Georg Sigismund Otto Lasius (1789), Carl Gottlieb Horstig (1805)",
    "jahr": "1771–1800",
    "sprache": "de",
    "orig_sprache": "nhd",
    "pg_label": "",
    "quelle": "C. F. von Reden, Rede bey dem feyerlichen Anfange des Tiefen Georg-Stollen-Baues am 26. Julius 1777 unweit der Bergstadt Grund am Harze, nebst der Predigt, die auf Befehl der Regierung am Tage darauf [...] zu Clausthal deswegen gehalten wurde von Georg Christoph Dahme (Clausthal: Wendeborn 1777), Rede S. 3–12, Predigt S. 17–23, 50–55 (Internet Archive 10293262bsb); G. S. O. Lasius, Beobachtungen über die Harzgebirge, Erster Theil (Hannover 1789), S. 37–38, 51–52 und Profiltafel (Internet Archive 10806207bsb); C. G. Horstig, Tageblätter unsrer Reise in und um den Harz (Leipzig 1805), S. 147–148 (Internet Archive 10469480bsb).",
    "hinweis": "Reden, Dahme und Lasius nach den Fraktur-Drucken, am Seitenbild gelesen (die Texterkennung ist unbrauchbar), Horstig nach dem Antiquadruck, ebenfalls am Seitenbild geprüft; alle in ihrer Schreibung. Die Wochentage sind nachgerechnet: Der 26. Juli 1777 war ein Samstag, der 9. Sonntag nach Trinitatis der 27. Juli. Auslassungen stehen in eckigen Klammern.",
    "sections": [
        {"id": "rede", "autor": "Claus Friedrich von Reden, 26. Juli 1777", "titel": "Die Rede am Mundloch", "zk": "Rede",
         "plates": ["reden_titel", "reden_s10"],
         "viz": "stollen",
         "blurb": "Am 26. Juli 1777 steht der Berghauptmann bei Grund vor den Bergleuten und erklärt, warum der Oberharz einen neuen Stollen braucht: Nicht das Erz gehe aus, sondern ‚die zu große Last der Grundwasser‘ lege die Gruben still. Teiche und Künste könnten das Bergwerk nur erhalten. Dann nennt er die Zahlen, 4910 Lachter bis zur Grube Caroline, haut die erste Stufe und schließt mit ‚Glück auf!‘.",
         "units": REDE},
        {"id": "predigt", "autor": "Georg Christoph Dahme, 27. Juli 1777", "titel": "Die Predigt am Tag danach", "zk": "Predigt",
         "plates": [],
         "blurb": "Am Sonntag predigt der Generalsuperintendent in Clausthal ‚auf Befehl der Regierung‘ über Haggai: ‚Von diesem Tage an will ich Seegen geben.‘ Aber er verspricht nichts: kein Wunder im Berg, nur Naturgesetze und kluge Planung. Er mahnt zur Treue in der Arbeit, bittet für die Armenkasse und betet, die Arbeit möge ‚ohne Unglücksfälle‘ fortgehen.",
         "units": PREDIGT},
        {"id": "bau", "autor": "Lasius 1789, Horstig 1805", "titel": "Im Bau und fertig", "zk": "Vortrieb",
         "plates": ["lasius_profil", "lasius_s51"],
         "blurb": "1789 ist der Stollen ‚noch nicht ganz vollendet‘. Georg Sigismund Otto Lasius zeichnet ihn in ein Profil des ganzen Harzes und beschreibt die Mauerung ‚für die Ewigkeit‘, ohne Mörtel. Im Oktober 1800 steht ein Reisender am fertigen Mundloch bei Grund: junge Linden, eine Inschrift, und das Wasser aus Clausthal, das nun von selbst abfließt.",
         "units": BAU},
    ],
}

OUT.write_text(json.dumps(doc, ensure_ascii=False, indent=1), encoding="utf-8")
print("stollen.json:", sum(len(s["units"]) for s in doc["sections"]), "Einheiten")
