"""Modul 10: Das System um 1866. Schreibt data/system.json.

Quellen, am Seitenbild gelesen:
A. Dumreicher, Gesammtüberblick über die Wasserwirthschaft des nordwestlichen Oberharzes
(Clausthal: Grosse 1868), S. 1–2, 10, 12–15, 23–24, 29–31, 33–37, 39, 44
(Bayerische Staatsbibliothek, bsb10060258; Bildnummer = S.+6).
B. Kerl, Der Oberharz. Ein Wegweiser beim Besuche der Oberharzer Gruben [...] (Clausthal:
Schweiger 1852), S. 15, 18–19, 26, 37, 96–97 (bsb10293058; Bildnummer = S.+12).
"""
import json
from pathlib import Path

OUT = Path(__file__).resolve().parent.parent / "data" / "system.json"

ANLAGE = [
    dict(n=1, titel="‚Stets nur das eine Agens „Wasser“‘", pg="Dumreicher 1868, S. 1–2", lang="nhd",
         orig="Der seit mehreren hundert Jahren in ununterbrochenem Betriebe stehende Oberharzer-Gangbergbau hat von seinem Anfange bis zur Jetztzeit als bewegende Kraft der mannigfachen maschinellen Anlagen, durch welche die Gewinnung der rohen Erze sowie deren Umwandlung in brauchbares Metall ermöglicht werden, stets nur das eine Agens „Wasser“ zur Verfügung gehabt.\n\nDie allmäligen Vergrößerungen des Betriebes nach Flächenraum und vornehmlich nach der Tiefenrichtung haben die Nothwendigkeit einer immer größeren Vervollkommnung der Wasserwirthschaft hervorgerufen, so daß dieselbe in dem langen Zeitraume ihres Bestehens durch unausgesetzt sorgsame Pflege zu einer Ausdehnung und einer dem Bedürfnisse entsprechenden systematischen Anordnung herangewachsen ist, wie solche kaum in einer andern Gebirgsgegend angetroffen werden wird. […]\n\n[…] und wodurch jetzt zu erreichen steht, daß der Hauptsache nach erst dann erhebliche Störungen im Leben und Treiben des großen Baues eintreten, wenn die Natur 14 Wochen lang das Lebenselement „den Regen“ versagt.\n\nDie Sicherheit ist durch das Vorhandensein von 67 größeren und kleineren Reservoiren (Teiche) gegeben, die in den verschiedensten Höhen dem Terrain und der Bodenbeschaffenheit anpassend angelegt worden sind, und denen durch eine große Anzahl künstlicher Wasserleitungen (Sammelgräben), deren Gesammtlänge etwa 16½ Meilen beträgt, zu Regenzeiten die an den Bergabhängen und in den Schluchten herunterfließenden Wasser zur Füllung zugeführt werden. Aus den Teichen befördern wieder andere Wasserleitungen (Aufschlaggräben) in einer Gesammtlänge von 11 Meilen in den verschiedensten Richtungen und Niveauabständen die Wasser auf 196 Motoren der einzelnen Werke, nach einer wohlgeordneten Reihenfolge, so daß nach Möglichkeit stets die untern Motoren durch das auf den darüber liegenden verbrauchte Wasser ihre bewegende Kraft erhalten.",
         en="Der seit mehreren hundert Jahren ununterbrochen betriebene Oberharzer Gangbergbau hat von seinem Anfang bis heute als bewegende Kraft für die vielfältigen maschinellen Anlagen, mit denen die rohen Erze gewonnen und in brauchbares Metall verwandelt werden, immer nur ein einziges Mittel zur Verfügung gehabt: das Wasser.\n\nDie allmähliche Ausdehnung des Betriebs in der Fläche und vor allem in die Tiefe hat eine immer größere Vervollkommnung der Wasserwirtschaft nötig gemacht, so dass sie in der langen Zeit ihres Bestehens durch unablässige, sorgfältige Pflege zu einer Ausdehnung und einer dem Bedarf entsprechenden planmäßigen Anordnung herangewachsen ist, wie man sie kaum in einer anderen Gebirgsgegend finden wird. […]\n\n[…] und wodurch heute erreicht werden kann, dass im Wesentlichen erst dann erhebliche Störungen im Leben und Treiben des großen Werks eintreten, wenn die Natur 14 Wochen lang das Lebenselement, den Regen, verweigert.\n\nDiese Sicherheit geben 67 größere und kleinere Speicher (Teiche), die in den verschiedensten Höhen dem Gelände und dem Boden angepasst angelegt worden sind und denen eine große Zahl künstlicher Wasserleitungen (Sammelgräben) von zusammen etwa 16½ Meilen Länge bei Regen das Wasser zuführt, das an den Hängen und in den Schluchten herabfließt. Aus den Teichen bringen wieder andere Wasserleitungen (Aufschlaggräben) von zusammen 11 Meilen Länge das Wasser in den verschiedensten Richtungen und Höhen auf 196 Motoren der einzelnen Werke, in einer wohlgeordneten Reihenfolge, so dass möglichst immer die unteren Motoren ihre Kraft von dem Wasser erhalten, das die darüberliegenden schon verbraucht haben.",
         note="Alfred Dumreicher (1833–1913), königlicher Maschinenmeister in Clausthal (so das Titelblatt), schreibt 1868 die erste Gesamtbeschreibung des Systems, zwei Jahre nachdem der Oberharz mit dem Königreich Hannover an Preußen gekommen war. Der erste Satz fasst diesen ganzen Apparat zusammen: Alles, was sich im Oberharz bewegte, bewegte Wasser. 14 Wochen ohne Regen hält das System 1868 aus; 1763 waren es nach Calvör ‚fast ein Quartal‘, also gut 13 Wochen (Modul 3). Der Satz über die ‚untern Motoren‘ beschreibt die Kaskade aus Modul 4, die jetzt bis auf 196 Motoren angewachsen ist. Ausgelassen [‚…‘] sind zwei Sätze über den Fleiß der Vorfahren."),
    dict(n=2, titel="Der Damm aus der Katastrophe von 1733", pg="Dumreicher 1868, S. 10", lang="nhd",
         orig="In alter Zeit legte man die wasserabdichtende Wand, Rasenhaupt genannt, schräg der Böschung des Dammes entsprechend an die Wasserseite, dieselbe unten breit, 10 bis 12 Fuß, ansetzend und nach oben schmäler, auf 4 Fuß, auslaufen lassend, wornach dann die Anschüttung nur an der dem Wasser abgekehrten Seite lag.\n\nDiese Methode bewährte sich jedoch nicht, da das frei liegende Rasenhaupt durch Wellenschlag, Eis und Mauselöcher leicht Beschädigungen erlitt, und verschiedene nach dieser Bauart ausgeführte Dämme ausbrachen. — Man hat später daher das Rasenhaupt senkrecht in der Mitte des Dammes, 8 Fuß stark, aufgeführt, und die Anschüttung zu beiden Seiten gleichmäßig angestürzt […].\n\nDas Rasenhaupt in die Mitte zu legen geschah zuerst auf dem Oberharze am unteren Schalker-Teiche, nachdem derselbe am 2. Weihnachtstage 1733 bei starkem Regenwetter ausgebrochen war, und verbesserte man nach und nach fast sämmtliche Teichdämme nach dieser Bauart, welche bereits 1714 zum Lauterberge angewandt worden, woselbst man in Erfahrung gebracht, daß sich dieselbe zu Straßberg und Ilmenau im Stollbergschen bewährt hatte.",
         en="Früher legte man die abdichtende Wand, das sogenannte Rasenhaupt, schräg entsprechend der Dammböschung an die Wasserseite, unten breit, 10 bis 12 Fuß, und nach oben schmaler auslaufend, bis auf 4 Fuß; die Aufschüttung lag dann nur auf der dem Wasser abgewandten Seite.\n\nDiese Bauweise bewährte sich aber nicht, weil das frei liegende Rasenhaupt durch Wellenschlag, Eis und Mauselöcher leicht beschädigt wurde und mehrere so gebaute Dämme brachen. – Deshalb hat man das Rasenhaupt später senkrecht in der Mitte des Dammes, 8 Fuß stark, aufgeführt und die Aufschüttung auf beiden Seiten gleichmäßig angeschüttet […].\n\nDas Rasenhaupt in die Mitte zu legen, geschah im Oberharz zuerst am Unteren Schalker Teich, nachdem dieser am zweiten Weihnachtstag 1733 bei starkem Regen gebrochen war, und man verbesserte nach und nach fast alle Teichdämme nach dieser Bauart, die schon 1714 in Lauterberg angewandt worden war, wo man erfahren hatte, dass sie sich in Straßberg und Ilmenau im Stolbergischen bewährt hatte.",
         note="Die Katastrophe, die Calvör 1763 in einem einzigen Satz notierte (Modul 4, Verzeichnis [2]), hat 135 Jahre später ihren Platz in der Technikgeschichte: Nach dem Bruch des Unteren Schalker Teichs baute man die Dämme anders, mit der Dichtung in der Mitte. ‚Verschiedene […] Dämme ausbrachen‘: Dumreicher nennt keine Zahl und keine Opfer. Ausgelassen [‚…‘] ist der Satz über Steinschüttung und Trockenmauer auf der Wasserseite."),
    dict(n=3, titel="Grabensteiger im Regen, und das trockene Jahr 1857", pg="Dumreicher 1868, S. 12–13", lang="nhd",
         orig="Zu solchen Zeiten hat dann das die Wartung der Teiche und Gräben zu besorgende Personal, bestehend aus Grabensteigern, Grabenuntersteigern und Mitgängern, wohl Acht zu geben, daß vor Allem die am höchst gelegenen Teiche zuerst gefüllt werden. Der Ueberfluß wird dann den weiter unten liegenden zugeführt, und müssen bei starken anhaltenden Regengüssen die überflüssigen Wasser zu rechter Zeit durch die betreffenden Fehlschläge der Gräben oder Ausfluthen der Teiche in die Freifluthen und Thalwasser abgeführt werden, damit weder die Grabenbrust noch Dammkrone der betreffenden Gräben und Teiche eine Ueberschwemmung erleiden, wodurch nicht nur die Beschädigung der Anlagen sondern auch großes Unglück durch Ausbruch von Teichen entstehen könnte. […]\n\nDie mit der Zeit so vorzüglich ausgearbeitete Disposition sämmtlicher Anlagen gestattet auf diese Weise, daß der großartige Betrieb 14 bis 16 Wochen lang ohne Regen fortgeführt werden kann, wodurch eine große Sicherheit erzielt worden, da sich der Oberharz gemeiniglich bei einer jährlichen Regenmenge von etwa 53–54 Zoll Höhe einer gesegneten Nässe zu erfreuen hat. Nur in außerordentlich seltenen Fällen, so in dem überaus trockenen Jahre 1857, traten erhebliche Störungen, durch Wassermangel veranlaßt, in dem Oberharzer Bergbaubetriebe ein. In dem genannten Jahre war selbst der Hirschler-Teich, dessen Grundstriegel das letzte Sammelwasser auf dem höchsten Punkte hält, und der nur mit Genehmigung der obersten technischen Verwaltungsbehörde, des Königlichen Berg- und Forstamts, angezogen werden darf, völlig leer, ein Fall der seit vielen Jahren nicht vorgekommen war.",
         en="In solchen Zeiten muss das Personal, das Teiche und Gräben wartet, nämlich Grabensteiger, Grabenuntersteiger und Mitgänger, gut darauf achten, dass vor allem die am höchsten gelegenen Teiche zuerst gefüllt werden. Der Überschuss wird dann den tiefer liegenden zugeführt, und bei starken, anhaltenden Regengüssen muss das überflüssige Wasser rechtzeitig durch die Fehlschläge der Gräben oder die Überläufe der Teiche in die Freifluten und Bäche abgeleitet werden, damit weder die Grabenbrust noch die Dammkrone überflutet wird, wodurch nicht nur die Anlagen beschädigt würden, sondern auch großes Unglück durch den Bruch von Teichen entstehen könnte. […]\n\nDie im Laufe der Zeit so vorzüglich ausgearbeitete Anordnung aller Anlagen erlaubt auf diese Weise, den großartigen Betrieb 14 bis 16 Wochen lang ohne Regen fortzuführen. Damit ist eine große Sicherheit erreicht, denn der Oberharz erfreut sich gewöhnlich bei einer jährlichen Regenmenge von etwa 53 bis 54 Zoll einer gesegneten Nässe. Nur in außerordentlich seltenen Fällen, so im überaus trockenen Jahr 1857, traten durch Wassermangel erhebliche Störungen im Oberharzer Bergbau ein. In diesem Jahr war selbst der Hirschler Teich völlig leer, dessen Grundzapfen das letzte Sammelwasser am höchsten Punkt hält und der nur mit Genehmigung der obersten technischen Behörde, des Königlichen Berg- und Forstamts, gezogen werden darf, ein Fall, der seit vielen Jahren nicht vorgekommen war.",
         note="Zwei Gefahren, eine Mannschaft: Bei Regen müssen die Grabensteiger das Wasser rechtzeitig ablassen, damit kein Damm bricht, ‚großes Unglück‘; bei Dürre wird um jeden Tropfen gerechnet, und der letzte Teich darf nur mit Erlaubnis der Behörde gezogen werden. 1857 war er leer. Was ‚erhebliche Störungen‘ für die Bergleute hieß, sagt Dumreicher nicht; Calvör hatte 1763 geschrieben, dass sie bei Wassermangel ‚abgeleget‘ wurden (Modul 5, Urteile [2]). Die Grabensteiger mit ihren ‚Mitgängern‘ sind die Nachfolger des ersten Teichwärters von 1565 (Modul 4). Ausgelassen [‚…‘] sind zwei Sätze über die Teiche als Regulatoren."),
    dict(n=4, titel="‚Rad Wasser‘: eine Einheit nach Gefühl", pg="Dumreicher 1868, S. 14–15", lang="nhd",
         orig="Der Ausdruck „Rad Wasser“ ist ein am Oberharze alt hergebrachter, und rührt vermuthlich aus jener ältesten Zeit des Bergbaues, in welcher nur Kunst- und Kehrräder von ziemlich gleichen und nach jetzigen Verhältnissen geringen Dimensionen bei durchschnittlich gleicher Leistung auch gleiche Betriebswasser erforderten. Bis auf den heutigen Tag geschieht die Schätzung des Wasserverbrauchs aus den Teichen nach Rädern Wasser, ohne daß jedoch eine bestimmte Quelle aufzufinden ist für Angabe einer absoluten Größenzahl. Da wo solche erforderlich, setzt man 160 Cubikfuß pro Minute gleich einem Rade Wasser, eine Zahl, die wohl dem Ausdrucke entsprechend in alter Zeit richtig gewesen sein mag, für die Neuzeit aber nicht mehr zutreffend ist. […]\n\nFür ein Betriebsrad werden je nach Umständen 2, 2½, auch 3 Räder Wasser angezogen, ein Sprachgebrauch, dessen Größenbemessung lediglich der Hauptsache nach Gefühlssache des damit beschäftigten Personals ist, da es sich im Resultate einfach um den Betrieb eines Wasserrades handelt, das je nach dem zeitigen Wasservorrathe oder der zu leistenden Arbeit sein Wasserquantum zugeführt bekommt.",
         en="Der Ausdruck „Rad Wasser“ ist im Oberharz althergebracht und stammt vermutlich aus der ältesten Zeit des Bergbaus, als nur Kunst- und Kehrräder von ziemlich gleicher und nach heutigen Verhältnissen geringer Größe bei durchschnittlich gleicher Leistung auch gleich viel Aufschlagwasser brauchten. Bis heute schätzt man den Wasserverbrauch aus den Teichen nach ‚Rädern Wasser‘, ohne dass sich jedoch eine Quelle für eine absolute Größe finden ließe. Wo eine solche nötig ist, setzt man 160 Kubikfuß pro Minute einem Rad Wasser gleich, eine Zahl, die dem Ausdruck entsprechend in alter Zeit richtig gewesen sein mag, für die Gegenwart aber nicht mehr zutrifft. […]\n\nFür ein Betriebsrad zieht man je nach den Umständen 2, 2½ oder auch 3 Räder Wasser, ein Sprachgebrauch, dessen Größe im Wesentlichen reine Gefühlssache des damit beschäftigten Personals ist, da es sich im Ergebnis einfach um den Betrieb eines Wasserrades handelt, dem je nach dem vorhandenen Wasservorrat oder der zu leistenden Arbeit seine Wassermenge zugeführt wird.",
         note="Der Ingenieur misst die Sprache der Praktiker nach und findet: Ihre Grundeinheit ist ‚Gefühlssache‘. ‚Rad Wasser‘ stammt aus Calvörs Zeit (‚4 Rad Wasser auf 5 Kehr- und 14 Kunsträder‘, Modul 3, Mangel [1]) und hat die Räder überlebt, die es einmal maß. Dumreicher rechnet deshalb jedes einzelne Rad selbst nach (Räder [3]). Ausgelassen [‚…‘] ist sein Vergleich mit Juglers Angabe von 1854 (260 Kubikfuß) und seiner eigenen (360)."),
    dict(n=5, titel="Der Dammgraben: ‚der eigentliche Lebensnerv‘", pg="Dumreicher 1868, S. 23–24", lang="nhd",
         orig="Nach dem bis jetzt Gesagten zeigt sich somit, daß die Hauptwasserleitung über Tage, der Dammgraben mit Zubehör, die uns dem Ausdrucke gemäß jetzt nicht mehr als ein einfacher Graben erscheint, sondern als ein sinnreiches System, geordnet nach Zu- und Abführung, als der eigentliche Lebensnerv unserer ganzen Wasserwirthschaft zu betrachten ist, und hat man ihr deshalb auch mit Recht von jeher die größte Sorgfalt zugewandt.\n\nDies beschriebene System ist nicht nach einem zur Zeit der Entstehung angefertigten Generalprojecte zur Ausführung gekommen, sondern jemehr das Bedürfniß es verlangte, von geringem Anfange zu seiner ganzen Ausdehnung erst in der Neuzeit gelangt.\n\nSchon 1657 wurde das Project, die Wasser der quellenreichen Abhänge des Bruchberges nach Clausthal zu führen, überlegt, scheiterte aber in damaliger Zeit an der Ueberführung zwischen Isenkopf und Tränkeberg. Erst 1718 und 1719 wurde diese Angelegenheit wieder ernstlich in Angriff genommen, und sollte eine große Commission die Sache prüfen, um darnach betreffende Vorschläge machen zu können. Nach langen Berathungen, in denen die mannigfachsten Projecte, wie thönerne oder gußeiserne Röhrentouren oder solche von Blei, sowie die Idee an beiden Bergen Schächte abzusinken und diese durch eine unterirdische Strecke zu verbinden, so daß die ersteren nach Art von communicirenden Röhren wirken würden, verworfen waren, entschloß man sich einen entsprechend hohen Damm aufzutragen. Somit wurde in 75 Wochen vom 21. April 1732 bis 2. Mai 1734 der Sperberhayerdamm gebaut. […]\n\nErst in diesem Jahrhundert, 1820 bis 1840, sind die verschiedenen Zuführgräben für den Dammgraben so wie dessen Verlängerung bis zur Blochschleife entstanden, wobei namentlich der 1847 verstorbene Oberbergmeister Ey, wie überall für die Wasserwirthschaft, sich große Verdienste erworben hat.",
         en="Nach dem bisher Gesagten zeigt sich also, dass die Hauptwasserleitung über Tage, der Dammgraben mit seinem Zubehör, der uns jetzt nicht mehr, wie sein Name sagt, als einfacher Graben erscheint, sondern als sinnreiches System, geordnet nach Zu- und Abführung, als der eigentliche Lebensnerv unserer ganzen Wasserwirtschaft zu betrachten ist; und man hat ihm deshalb auch mit Recht seit jeher die größte Sorgfalt gewidmet.\n\nDieses System ist nicht nach einem Gesamtplan ausgeführt worden, der bei seiner Entstehung angefertigt wurde, sondern ist, je nachdem der Bedarf es verlangte, von kleinem Anfang erst in neuerer Zeit zu seiner ganzen Ausdehnung gelangt.\n\nSchon 1657 wurde der Plan erwogen, das Wasser der quellreichen Hänge des Bruchbergs nach Clausthal zu führen; er scheiterte damals aber an der Überquerung zwischen Isenkopf und Tränkeberg. Erst 1718 und 1719 nahm man die Sache wieder ernsthaft in Angriff, und eine große Kommission sollte sie prüfen, um danach Vorschläge machen zu können. Nach langen Beratungen, in denen die verschiedensten Pläne verworfen wurden, etwa Rohrleitungen aus Ton, Gusseisen oder Blei oder die Idee, an beiden Bergen Schächte abzuteufen und durch eine unterirdische Strecke zu verbinden, so dass sie wie kommunizierende Röhren wirken würden, entschloss man sich, einen entsprechend hohen Damm aufzuschütten. So wurde in 75 Wochen, vom 21. April 1732 bis zum 2. Mai 1734, der Sperberhaier Damm gebaut. […]\n\nErst in diesem Jahrhundert, 1820 bis 1840, entstanden die verschiedenen Zuleitungsgräben für den Dammgraben und seine Verlängerung bis zur Blochschleife, wobei sich besonders der 1847 verstorbene Oberbergmeister Ey, wie überall in der Wasserwirtschaft, große Verdienste erworben hat.",
         note="Dumreicher bestätigt Calvörs Zahlen zum Dammgraben (Modul 4, Gräben [1]) und führt die Geschichte weiter, bis zum Brockenfeld. Sein Satz über das ‚Generalproject‘ ist die wichtigste historische Einsicht des Buchs: Das System war nie geplant, es ist gewachsen, Teich um Teich und Graben um Graben, ‚jemehr das Bedürfniß es verlangte‘. Ausgelassen [‚…‘] sind die Maße des Damms (488 Lachter lang, 8 Lachter hoch) und die Namen der Bauleiter Hansen und Hartzig."),
]

TIEFE = [
    dict(n=1, titel="‚In der Höhenlage […] der Stollen spricht sich die Geschichte des Bergbaues aus‘", pg="Dumreicher 1868, S. 29", lang="nhd",
         orig="Würden die sämmtlichen Gruben mit ihren Bauen gleichzeitig sich überblicken lassen, so würde man sehen, wie aus allen den hunderten von Gängen, welche der Bergmann zur Gewinnung des Erzes in das feste Gestein treibt, die aus demselben bald in stärkeren bald in schwächeren Strahlen entquellenden Wasser sämmtlich den Hauptadern, den Stollen, zugeführt werden, um durch diese im Verein mit den Abfallwassern der unterirdischen Motoren sowie denen, welche von diesen aus der Tiefe emporgehoben sind, zu Tage geleitet zu werden.\n\nIn der Höhenlage und der geographischen Situation der Stollen spricht sich die Geschichte des Bergbaues aus. Man ersieht wie in älterer Zeit eine geringere Teufe dem Bedürfniß genügt hat, und welche Gruben in so gewinnbringenden Betriebe gestanden, daß es der hohen Kosten lohnte, die Grubenwasser derselben mittelst Stollen zu lösen.\n\nWenn dann die Tiefe zunahm, und selbst die durch die vermehrten Tageswasser gesteigerte Kraft für die künstlichen Hubvorrichtungen der Grundwasser auf die Stollen nicht mehr ausreichen wollte, so trat die Nothwendigkeit ein, die Abführung auf einem tieferen Niveau zu bewerkstelligen und sind dadurch in bestimmten Zeiträumen die Hauptstollen entstanden […].\n\nIn neuester Zeit ist somit das große Riesenwerk, der Ernst-August-Stollen beendet, mit welchem die Reihe der größeren zu Tage ausgehenden Hauptwasserleitungen als geschlossen zu betrachten sein dürfte.\n\nDerselbe endet seinen unterirdischen Lauf bei Gittelde, schon außerhalb des eigentlichen Harzgebirges, in einer absoluten Höhe von 646 Fuß, so daß die Anlage eines tieferen zu Tage geleiteten Stollens, wenn er entsprechend genügende Teufe einbringen soll, bezüglich der Länge nach heutigen bergmännischen Begriffen nimmermehr zur Ausführung kommen wird.",
         en="Könnte man alle Gruben mit ihren Bauen zugleich überblicken, so sähe man, wie aus all den Hunderten von Gängen, die der Bergmann zur Gewinnung des Erzes in das feste Gestein treibt, das Wasser, das daraus in stärkeren oder schwächeren Strahlen hervorquillt, den Hauptadern, den Stollen, zugeführt wird, um durch sie zusammen mit dem Abwasser der unterirdischen Motoren und dem Wasser, das diese aus der Tiefe heben, zutage geleitet zu werden.\n\nIn der Höhenlage und der geografischen Lage der Stollen drückt sich die Geschichte des Bergbaus aus. Man sieht, wie in älterer Zeit eine geringere Tiefe dem Bedarf genügte und welche Gruben so gewinnbringend betrieben wurden, dass es die hohen Kosten lohnte, ihr Grubenwasser mit Stollen zu lösen.\n\nWenn dann die Tiefe zunahm und selbst die durch mehr Aufschlagwasser gesteigerte Kraft der künstlichen Hebevorrichtungen nicht mehr ausreichte, das Grundwasser auf die Stollen zu heben, wurde es nötig, das Wasser auf einem tieferen Niveau abzuführen, und so sind in bestimmten Zeitabständen die Hauptstollen entstanden […].\n\nIn neuester Zeit ist nun das große Riesenwerk, der Ernst-August-Stollen, vollendet, mit dem die Reihe der größeren, zutage austretenden Hauptwasserleitungen als abgeschlossen gelten dürfte.\n\nEr endet seinen unterirdischen Lauf bei Gittelde, schon außerhalb des eigentlichen Harzgebirges, in einer absoluten Höhe von 646 Fuß, so dass ein tieferer, zutage geführter Stollen, wenn er genügend Tiefe einbringen soll, wegen seiner Länge nach heutigen bergmännischen Begriffen niemals ausgeführt werden wird.",
         note="Dumreicher liest die Stollen wie Jahresringe: Jeder liegt tiefer als der vorige, und jeder wurde gebaut, als der vorige nicht mehr reichte. Was Reden 1777 ‚die zu große Last der Grundwasser‘ nannte (Modul 7), ist hier das Gesetz des Systems. Und er zieht einen Schlussstrich: Der Ernst-August-Stollen, 1864 vollendet, sei der letzte; ‚nimmermehr‘ werde ein tieferer gebaut. Damit endet die Reihe, die in diesem Apparat mit den Stollen der Bergfreiheiten begann (Modul 1). Ausgelassen [‚…‘] ist ein Verweis auf die folgenden Paragrafen."),
    dict(n=2, titel="Kähne 1300 Fuß unter Clausthal", pg="Dumreicher 1868, S. 30–31", lang="nhd",
         orig="Nach Beendigung des Tiefen-Georgstollens wurde zu selbigem Zwecke für diesen die s. g. Tiefe Wasserstrecke verwandt, welche 60 Lachter unter demselben (Niveau des später gebauten Ernst-August-Stollens) die Gruben des Burgstädter, Zellerfelder und Rosenhöfer Revieres mit einander verband. In diese ergossen die Hubvorrichtungen der verschiedenen Gruben je nach Bedürfniß die betreffenden Grundwasser, und wurden diese sämmtlich im Silber-Segener Schachte durch zwei nebeneinander arbeitende Wassersäulenmaschinen auf den Tiefen-Georgstollen befördert.\n\nDie bezeichnete Strecke, so weit sie die Gruben des Burgstädter und Rosenhöfer Revieres verbindet, hat noch einen zweiten Dienst für den Bergbau zu verrichten, den wir hier nicht unerwähnt lassen dürfen.\n\nDer Wasserstand wird durchschnittlich auf 60 Zoll erhalten, und ist die Strecke so hoch und weit ausgehauen, daß sie als Canal für größere Transportboote benutzt wird, durch welche die in der Tiefe gewonnenen Erze des Burgstädter Zuges 1300 Fuß unter der Stadt Clausthal nach dem Rosenhöfer Zuge geschifft werden, um sie von hier aus zu Tage gefördert, den Aufbereitungswerken des Clausthaler Thales übergeben zu können. Es ist somit nicht erforderlich, die Erze aus den Tiefbauen im Burgstädter Reviere höher wie bis zur Tiefen Wasserstrecke zu fördern, und fällt der theure Axentransport über Tage weg, indem ein Mann per Boot 136 bis 140 Centner fortschafft.\n\nNach Beendigung des Ernst-August-Stollens wird nunmehr in 120 Lachter Tiefe unter demselben, also 324 Lachter unter Tage von der Hängebank der Grube Caroline, und 118 Fuß hannov. unter dem Nordseespiegel, die s. g. Tiefste Wasserstrecke angelegt, welche die Hauptgruben miteinander verbindend nach ihrer Vollendung wiederum als großes Wasserreservoir anzusehen ist.",
         en="Nach der Vollendung des Tiefen Georg-Stollens benutzte man für ihn zum selben Zweck die sogenannte Tiefe Wasserstrecke, die 60 Lachter unter ihm (auf dem Niveau des später gebauten Ernst-August-Stollens) die Gruben des Burgstätter, Zellerfelder und Rosenhöfer Reviers miteinander verband. In sie gossen die Hebevorrichtungen der verschiedenen Gruben je nach Bedarf ihr Grundwasser, und es wurde insgesamt im Silbersegener Schacht von zwei nebeneinander arbeitenden Wassersäulenmaschinen auf den Tiefen Georg-Stollen gehoben.\n\nDie genannte Strecke hat, soweit sie die Gruben des Burgstätter und Rosenhöfer Reviers verbindet, noch einen zweiten Dienst für den Bergbau zu leisten, den wir hier nicht unerwähnt lassen dürfen.\n\nDer Wasserstand wird im Durchschnitt auf 60 Zoll gehalten, und die Strecke ist so hoch und weit ausgehauen, dass sie als Kanal für größere Transportboote dient, mit denen die in der Tiefe gewonnenen Erze des Burgstätter Zugs 1300 Fuß unter der Stadt Clausthal zum Rosenhöfer Zug geschifft werden, um von dort zutage gefördert und den Aufbereitungswerken im Clausthaler Tal übergeben zu werden. So braucht man die Erze aus den Tiefbauen des Burgstätter Reviers nicht höher als bis zur Tiefen Wasserstrecke zu fördern, und der teure Wagentransport über Tage entfällt, da ein Mann mit einem Boot 136 bis 140 Zentner fortschafft.\n\nNach der Vollendung des Ernst-August-Stollens wird nun 120 Lachter unter ihm, also 324 Lachter unter der Hängebank der Grube Caroline und 118 hannoversche Fuß unter dem Spiegel der Nordsee, die sogenannte Tiefste Wasserstrecke angelegt, die die Hauptgruben miteinander verbindet und nach ihrer Vollendung wieder als großes Wasserspeicher dienen soll.",
         note="Ein unterirdischer Kanal mit 60 Zoll Wasser, auf dem ein Mann ein Boot mit 136 bis 140 Zentnern Erz durch den Berg zieht, 1300 Fuß unter der Stadt. Kerl beschreibt 1852, wie: Der Schiffer ‚ergreift‘ in regelmäßigen Abständen ein unter der Decke gespanntes Drahtseil ‚und zieht sich nebst dem Boote fort‘, 1937 Lachter in 8½ Stunden (Kerl S. 14–15, hier nicht abgedruckt). Und die nächste Tiefe ist schon begonnen: 118 Fuß unter dem Meeresspiegel. Die Tiefe Wasserstrecke ist das unterirdische Gegenstück zu den Teichen über Tage, ein Speicher für Grundwasser, wie Dumreicher eigens sagt (S. 30)."),
    dict(n=3, titel="Der Tiefe Georg-Stollen: 22 Jahre, 5481 Lachter", pg="Dumreicher 1868, S. 33–34", lang="nhd",
         orig="§. 6. Der Tiefe-Georg-Stollen bringt auf der Grube Caroline 149 L. Teufe ein, und mündet, bei einem Gefälle von durchschnittlich 15 Zoll auf 100 Lachter, unterhalb der Stadt Grund mit einer Höhenlage seines Mundloches von 1006 Fuß hannov. über der Nordsee. Sein ursprünglicher Lauf, unter den Gruben des Burgstädter Zuges von da nach dem Rosenhöfer Reviere und dem Silbern-Aaler Zuge bis nach dem Mundloche, ist den 26. Juli 1777 angefangen und den 5. September 1799 beendet, später aber durch Fortführung in das Zellerfelder Revier bis Wildemann und vom alten Johanneser-Schachte über Spiegelthals-Hoffnung nach den Bockswieser Schächten um ein Bedeutendes verlängert.\n\nSeine Länge beträgt vom Mundloche bis zum Rosenhöfer Reviere 3738 L., von hier bis zum Herzog-Georg-Wilhelm-Schachte 807 L., und von diesem bis zur Grube Caroline 936 L., demnach die ursprüngliche in 22 Jahren beendete Länge 5481 Lachter. […]\n\nAngefangen und beendet wurde der Stollen unter der Regierung Georg III. Zur Zeit des Angriffs war Friedrich von Rheden Berghauptmann, zur Zeit der Einweihung nach der Vollendung fungirte der Vice-Berghauptmann von Meding als solcher. Die größten Verdienste bei Projectirung und dem Baue dieses bedeutenden bergmännischen Werkes gebührt dem Oberbergmeister Stelzner.",
         en="§ 6. Der Tiefe Georg-Stollen bringt auf der Grube Caroline 149 Lachter Tiefe ein und mündet bei einem Gefälle von durchschnittlich 15 Zoll auf 100 Lachter unterhalb der Stadt Grund; sein Mundloch liegt 1006 hannoversche Fuß über der Nordsee. Sein ursprünglicher Verlauf, unter den Gruben des Burgstätter Zugs von dort zum Rosenhöfer Revier und zum Silbernaaler Zug bis zum Mundloch, wurde am 26. Juli 1777 begonnen und am 5. September 1799 vollendet, später aber durch Fortführung in das Zellerfelder Revier bis Wildemann und vom alten Johanneser Schacht über Spiegeltaler Hoffnung zu den Bockswieser Schächten bedeutend verlängert.\n\nSeine Länge beträgt vom Mundloch bis zum Rosenhöfer Revier 3738 Lachter, von dort bis zum Herzog-Georg-Wilhelm-Schacht 807 Lachter und von diesem bis zur Grube Caroline 936 Lachter, die ursprüngliche, in 22 Jahren vollendete Länge also 5481 Lachter. […]\n\nBegonnen und vollendet wurde der Stollen unter der Regierung Georgs III. Zur Zeit des Beginns war Friedrich von Reden Berghauptmann, zur Zeit der Einweihung nach der Vollendung amtierte der Vizeberghauptmann von Meding. Die größten Verdienste um Planung und Bau dieses bedeutenden bergmännischen Werks gebühren dem Oberbergmeister Stelzner.",
         note="Was der Tiefe Georg-Stollen am Ende war, 89 Jahre nach Redens Rede (Modul 7). Dumreicher liefert das Datum, das dort nur aus der neueren Literatur stand: vollendet am 5. September 1799, nach 22 Jahren. Die Länge ist größer als geplant (5481 statt 4910 Lachter), die Tiefe an der Caroline kleiner (149 statt 162). Dumreicher nennt den Berghauptmann ‚Friedrich von Rheden‘; der Druck von 1777 nennt ihn Claus Friedrich von Reden. Ausgelassen [‚…‘] ist die Verlängerung auf 9500 Lachter. Die Arbeiter nennt auch er nicht."),
    dict(n=4, titel="Der Ernst-August-Stollen, 1851–1864", pg="Dumreicher 1868, S. 34–35", lang="nhd",
         orig="§. 7. Der Ernst-August-Stollen, ein bergmännisches Riesenwerk, wie ich es wohl schon genannt, oder die Hauptpulsader der Wasserwirthschaft unter Tage, bringt auf der Grube Caroline 204 Lachter Teufe ein, und mündet, bei durchschnittlich nur 5⁴⁄₁₀ Zoll Gefälle auf 100 Lachter Länge, nahe dem Herzoglich Braunschweigschen Flecken Gittelde.\n\nDie Sohle desselben im Mundloche liegt 646 Fuß über der Nordsee. Der Lauf des in 13 Jahren ausgeführten Stollens, mit Ausschluß der nunmehr dazu gehörigen aber schon früher gebauten Tiefen Wasserstrecke, beginnt beim Schreibfeder-Schachte, nimmt seine Richtung dann über den Haus-Sachsener-Schacht nach dem Ernst-August-Schachte bei Wildemann, von hier nach dem Silbern-Aaler Zuge, und so unter Berührung des 4. Lichtlochschachtes für den T. Georgstollen und der Grube Hülfe Gottes bei Grund, nach Gittelde.\n\nAngefangen ist derselbe am 21. Juli 1851, beendet am 22. Juni 1864. […]\n\nDer Anfang dieses großen für den Betrieb des Harzer Bergbaues so überaus wichtigen Bauwerkes fällt in die Regierungszeit Ernst August I., das Ende in die von Georg V. […]\n\nDas Verdienst, mit energischer Ausdauer alle zu Gebote stehenden Mittel angewandt zu haben, um diesen Stollen in 13 Jahren herzustellen, gebührt dem Bergrathe Koch, und hat sich der Markscheider, nachherige Bergmeister Borchers durch die meisterhaften Nivellementarbeiten das wohlverdiente Lob aller Sachverständigen erworben.",
         en="§ 7. Der Ernst-August-Stollen, ein bergmännisches Riesenwerk, wie ich ihn schon genannt habe, oder die Hauptschlagader der Wasserwirtschaft unter Tage, bringt auf der Grube Caroline 204 Lachter Tiefe ein und mündet bei durchschnittlich nur 5⁴⁄₁₀ Zoll Gefälle auf 100 Lachter nahe dem herzoglich braunschweigischen Flecken Gittelde.\n\nSeine Sohle liegt am Mundloch 646 Fuß über der Nordsee. Der Verlauf des in 13 Jahren gebauten Stollens, ohne die jetzt dazugehörige, aber schon früher gebaute Tiefe Wasserstrecke, beginnt am Schreibfeder-Schacht, führt dann über den Haus-Sachsener Schacht zum Ernst-August-Schacht bei Wildemann, von dort zum Silbernaaler Zug und so, am 4. Lichtlochschacht des Tiefen Georg-Stollens und an der Grube Hülfe Gottes bei Grund vorbei, nach Gittelde.\n\nBegonnen wurde er am 21. Juli 1851, vollendet am 22. Juni 1864. […]\n\nDer Beginn dieses für den Harzer Bergbau so überaus wichtigen Bauwerks fällt in die Regierungszeit Ernst Augusts I., das Ende in die Georgs V. […]\n\nDas Verdienst, mit energischer Ausdauer alle verfügbaren Mittel eingesetzt zu haben, um diesen Stollen in 13 Jahren herzustellen, gebührt dem Bergrat Koch, und der Markscheider und spätere Bergmeister Borchers hat sich durch seine meisterhaften Nivellierarbeiten das wohlverdiente Lob aller Sachverständigen erworben.",
         note="Der letzte der großen Stollen, 55 Lachter tiefer als der Tiefe Georg-Stollen, in 13 statt 22 Jahren gebaut, mit gut einem Drittel von dessen Gefälle. Er wurde unter dem letzten König von Hannover vollendet, Georg V., zwei Jahre bevor das Königreich 1866 an Preußen fiel. Wieder sind es die Namen der Beamten, die bleiben: Koch, Borchers. Ausgelassen [‚…‘] sind die Teillängen und die Namen der Berghauptleute (von dem Knesebeck, von Linsingen)."),
]

RAEDER = [
    dict(n=1, titel="193 Wasserräder, alle aus Fichtenholz", pg="Dumreicher 1868, S. 36–37", lang="nhd",
         orig="§. 1. Die gesammte für uns in Betracht kommende Wasserkraft wird zur Zeit durch 193 Wasserräder und 3 Wassersäulmaschinen zur Nutzung gebracht. Turbinen und Henschelsche Kettengebläse sind vorhanden gewesen (Bauhof und ehemalige Silbern-Aaler-Frischhütte) jedoch innerhalb der letzten 10 Jahre, durch besondere Betriebsumstände veranlaßt, abgeworfen. Erst bei den neuen Pochwerksanlagen im Clausthaler-Thale und zu Lautenthal werden wieder Turbinen eingebaut werden. […]\n\nDie Construction der Räder, durchweg von Holz, bietet mit Ausnahme von wenigen keine besondere Verschiedenheit von der gewöhnlich für hölzerne Wasserräder angewandten Methode. […]\n\nDie Verarmung ist durchweg um die Welle angebracht, und nur in einzelnen Fällen, z. B. Grube Dorothea, wo die Arme ihrer Länge wegen, 40 Fuß, nicht in die Grube hätten geschafft werden können, sind gußeiserne Armsterne auf die Welle gekeilt und in deren Taschen die Arme eingelegt und festgeschraubt. […] Sämmtliche Räder über und unter Tage sind von Fichtenholz, die Wellen dagegen, je nach der Anwendung und den localen Umständen entsprechend, von Fichten oder Eichenholz.",
         en="§ 1. Die gesamte Wasserkraft, die für uns in Betracht kommt, wird derzeit von 193 Wasserrädern und 3 Wassersäulenmaschinen genutzt. Turbinen und Henschel'sche Kettengebläse hat es gegeben (Bauhof und ehemalige Silbernaaler Frischhütte), sie sind aber in den letzten 10 Jahren aus besonderen betrieblichen Gründen stillgelegt worden. Erst bei den neuen Pochwerken im Clausthaler Tal und in Lautenthal werden wieder Turbinen eingebaut werden. […]\n\nDie Bauart der Räder, durchweg aus Holz, unterscheidet sich bis auf wenige Ausnahmen nicht von der für hölzerne Wasserräder üblichen. […]\n\nDie Arme sind durchweg um die Welle angebracht; nur in einzelnen Fällen, etwa auf der Grube Dorothea, wo die Arme wegen ihrer Länge von 40 Fuß nicht in die Grube hätten gebracht werden können, sind gusseiserne Armsterne auf die Welle gekeilt und die Arme in deren Taschen eingelegt und festgeschraubt. […] Alle Räder über und unter Tage sind aus Fichtenholz, die Wellen dagegen je nach Verwendung und örtlichen Umständen aus Fichten- oder Eichenholz.",
         note="1868, als anderswo schon Dampfmaschinen liefen, drehen sich im Oberharz 193 Wasserräder aus Fichtenholz. Turbinen waren versucht und wieder ‚abgeworfen‘ worden. Das Holz kommt aus dem Wald, den Modul 6 beschreibt; das Wasser aus den Teichen. Die 40 Fuß langen Arme für die Räder der Dorothea, der Grube, in der Heine 1824 den Bergleuten begegnet war (Modul 9), mussten in Stücken unter Tage gebracht werden. Eine einzige Dampfmaschine nennt Dumreicher, außerhalb des Systems, im Lerbacher Tal (S. 45). Ausgelassen [‚…‘] sind die rückschlächtigen Räder und die Laschen der Radkränze."),
    dict(n=2, titel="2869 Pferdekräfte", pg="Dumreicher 1868, S. 39", lang="nhd",
         orig="Die schon oben erwähnten 193 Wasserräder und 3 Wassersäulmaschinen repräsentiren zusammen eine Rohkraft von 2869 Pferdekräften à 516 Fußpfund hannoversch pro Secunde, oder nach obigen Annahmen 1870 Pferdekraft Netto.\n\nNach einzelnen Abtheilungen vertheilt sind vorhanden:\n\n[Für — Anzahl Räder — Pferdekraft brutto — netto]\nGrubenbetrieb über Tage — 50 — 883 — } 1072\nGrubenbetrieb unter Tage — 26 — 547 — }\nWassersäulmaschinen — 3 — 105 — 70\nAufbereitungswerke — 60 — 646 — 323\nSilberhütten 14, Bauhof 2, Altenauer Eisenhütte 3, Sägemühlen 3 — 366 — 244\nPrivate und Schmieden — 10 — 95 — 47½\nMahlmühlen — 25 — 227 — 113½\nSumma Räder 193, Wassersäulmaschinen 3 — 2869 — 1870",
         en="Die schon erwähnten 193 Wasserräder und 3 Wassersäulenmaschinen leisten zusammen eine Rohkraft von 2869 Pferdestärken zu 516 hannoverschen Fußpfund pro Sekunde, nach den obigen Annahmen also 1870 Pferdestärken netto.\n\nNach Abteilungen verteilt sind vorhanden:\n\n[Für – Zahl der Räder – Pferdestärken brutto – netto]\nGrubenbetrieb über Tage – 50 – 883 – } 1072\nGrubenbetrieb unter Tage – 26 – 547 – }\nWassersäulenmaschinen – 3 – 105 – 70\nAufbereitungswerke – 60 – 646 – 323\nSilberhütten 14, Bauhof 2, Altenauer Eisenhütte 3, Sägemühlen 3 – 366 – 244\nPrivate und Schmieden – 10 – 95 – 47½\nMahlmühlen – 25 – 227 – 113½\nSumme: 193 Räder, 3 Wassersäulenmaschinen – 2869 – 1870",
         note="Die erste Gesamtrechnung der Wasserkraft des Oberharzes, Rad für Rad, weil die alte Einheit ‚Rad Wasser‘ dafür nicht taugte (Anlage [4]). Knapp 1900 Pferdestärken netto, verteilt auf fast zweihundert Räder: Das System bewegte einen ganzen Bergbau mit Wasser, das es über Jahrhunderte gesammelt, gestaut und von Rad zu Rad weitergegeben hatte. Die Tabelle ist in eckigen Klammern vereinfacht wiedergegeben."),
    dict(n=3, titel="Nachts gepocht, tags gewaschen", pg="Dumreicher 1868, S. 41", lang="nhd",
         orig="Für die Kehr- oder Förderräder, welche zwischen 11 und 23 Pferdekraft variiren, kann durchschnittlich der Mehrzahl gemäß die Zahl 18 angenommen werden.\n\nFür die Wasserhaltung sind die Grenzen etwa zwischen 17 und 33 Pferdekraft, und kann im Durchschnitt ein Wasserrad für dieselbe über Tage mit 19 Pferdekraft, ein solches unter Tage mit 21 bis 22 angesetzt werden.\n\nDie Räder, welche zur Wasserhaltung und zugleich zur Fahrung der Mannschaft benutzt werden, sind durchschnittlich stärker und sind hier, bei den Grenzen von 19 bis 30 Pferdekraft, im Durchschnitt etwa über Tage 20 und unter Tage 23 Pferdekraft anzunehmen.\n\nDie Räder für die Aufbereitung sind sehr verschieden und richten sich meistens nach der Anzahl Stempel in den Pochzeugen, da bei den meisten älteren Etablissement's dieser Art des Nachts gepocht und bei Tage die Wäscharbeit betrieben wird. Die größere Anzahl der Pochwerke hat 6 Stempel im Pochzeuge wo für durchschnittlich 11 bis 12 Pferdekraft in normalem Betrieb disponibel sind. Es würde demnach bei 50 % Nutzeffect des Rades pro Stempel eine Pferdekraft netto zu rechnen sein, das den Resultaten die ich durch sorgfältig ausgeführte Bremsversuche erhalten habe, völlig entspricht, wenn das durchschnittliche Gewicht eines armirten Stempels zu 400 Pfd. bei 60 Hüben pro Minute und 10 Zoll Hub angenommen wird.",
         en="Für die Kehr- oder Förderräder, die zwischen 11 und 23 Pferdestärken leisten, kann man im Durchschnitt, der Mehrzahl entsprechend, 18 annehmen.\n\nFür die Wasserhaltung liegen die Grenzen etwa zwischen 17 und 33 Pferdestärken, und man kann im Durchschnitt ein Wasserrad dafür über Tage mit 19, unter Tage mit 21 bis 22 Pferdestärken ansetzen.\n\nDie Räder, die zugleich für die Wasserhaltung und für die Fahrung der Mannschaft dienen, sind im Durchschnitt stärker; hier sind bei Grenzen von 19 bis 30 Pferdestärken im Mittel über Tage etwa 20 und unter Tage 23 Pferdestärken anzunehmen.\n\nDie Räder für die Aufbereitung sind sehr verschieden und richten sich meist nach der Zahl der Stempel in den Pochwerken, da in den meisten älteren Anlagen dieser Art nachts gepocht und tagsüber gewaschen wird. Die Mehrzahl der Pochwerke hat 6 Stempel, für die im normalen Betrieb durchschnittlich 11 bis 12 Pferdestärken zur Verfügung stehen. Bei 50 % Wirkungsgrad des Rades wäre also je Stempel eine Pferdestärke netto zu rechnen, was den Ergebnissen meiner sorgfältigen Bremsversuche völlig entspricht, wenn man das durchschnittliche Gewicht eines beschlagenen Stempels mit 400 Pfund bei 60 Hüben pro Minute und 10 Zoll Hub annimmt.",
         note="Zwischen den Zahlen steht ein Satz über den Arbeitstag: In den älteren Pochwerken wird ‚des Nachts gepocht und bei Tage die Wäscharbeit betrieben‘. Das Wasser läuft Tag und Nacht, und die Arbeit folgt ihm. Wer in den Pochwerken arbeitete, sagt Kerl 1852: Knaben ab zehn Jahren (Fahrkunst [3]). 400 Pfund Stempel, 60 Hübe pro Minute: Der Lärm eines Pochwerks lässt sich aus diesen Zahlen erahnen. Die Räder ‚zur Fahrung der Mannschaft‘ treiben die Fahrkunst (Fahrkunst [1])."),
    dict(n=4, titel="Was sich nach 1864 schon ändert", pg="Dumreicher 1868, S. 44", lang="nhd",
         orig="§. 4. Die hierorts nun noch in Betracht kommenden Aenderungen, welche in den letzten Jahren eingetreten, beschränken sich auf etwa folgende Fälle:\n\nIm Spiegelthale sind auf der Grube Spiegelthalshoffnung schon vor mehreren Jahren Kunst- und Kehrrad gänzlich abgeworfen, und wird es von den Betriebsumständen der Grube abhängen, ob und wann dieselben wieder eingebaut werden.\n\nAuf der Grube Joachim ist das obere Kunstrad nach dem Durchschlage des Ernst-August-Stollens abgeworfen.\n\nIm Ernst-August-Schachte wird das Kunstrad jetzt nur zur Fahrkunst benutzt.\n\nAuf der Frankenscharner Hütte sind 1866 beide Räder des oberen Gefälles abgeworfen, und dort nur ein Gefälle jetzt in Nutzung.\n\nDie beiden Wassersäulmaschinen im Silber-Segener Schachte sind im Abbaue begriffen.\n\nDie Wasserkunsträder resp. die combinirten Wasser- und Fahrkunsträder der Schächte, 4tes Lichtloch des Tiefen-Georg-Stollens, Knesebeck und Hülfe Gottes werden nur zur Fahrkunst benutzt.",
         en="§ 4. Die Änderungen, die hier noch in Betracht kommen und in den letzten Jahren eingetreten sind, beschränken sich etwa auf folgende Fälle:\n\nIm Spiegeltal sind auf der Grube Spiegeltaler Hoffnung schon vor mehreren Jahren Kunst- und Kehrrad ganz stillgelegt worden, und es wird von den Betriebsumständen der Grube abhängen, ob und wann sie wieder eingebaut werden.\n\nAuf der Grube Joachim ist das obere Kunstrad nach dem Durchschlag des Ernst-August-Stollens stillgelegt worden.\n\nIm Ernst-August-Schacht wird das Kunstrad jetzt nur noch für die Fahrkunst benutzt.\n\nAuf der Frankenscharner Hütte sind 1866 beide Räder des oberen Gefälles stillgelegt worden, dort ist jetzt nur noch ein Gefälle in Nutzung.\n\nDie beiden Wassersäulenmaschinen im Silbersegener Schacht werden abgebaut.\n\nDie Wasserkunsträder bzw. die kombinierten Wasser- und Fahrkunsträder der Schächte 4. Lichtloch des Tiefen Georg-Stollens, Knesebeck und Hülfe Gottes werden nur noch für die Fahrkunst benutzt.",
         note="Das Ende dieses Apparats in einer Liste. Seit der Ernst-August-Stollen das Grundwasser tiefer ableitet, werden Kunsträder überflüssig, die jahrhundertelang Wasser gehoben hatten; manche heben jetzt nur noch Menschen. Auf der Hütte werden 1866 Räder ‚abgeworfen‘. Was danach kam, Dampfmaschinen, Elektrizität und nach der neueren Literatur die Schließung der letzten Oberharzer Gruben im 20. Jahrhundert, liegt jenseits der Grenze, die sich dieser Apparat gesetzt hat."),
]

FAHRKUNST = [
    dict(n=1, titel="Die Fahrkunst, 1833: ‚mit Brustbeschwerden behaftet‘", pg="Kerl 1852, S. 18–19", lang="nhd",
         orig="Das Ein- und Ausfahren der Mannschaft geschieht auf mehr oder weniger geneigten, gut befestigten Leitern (Fahrten), welche auf den Bühnen aufstehen. Bühnen nennt man die immer in einiger Entfernung unter einander im Fahrschacht angebrachten Fussböden von Holzpfosten, welche mit einer Oeffnung, dem Fahrloche, versehen sind, aus welchem die auf der darunter befindlichen Bühne aufstehende Fahrt hervorragt. Bei den immer tiefer werdenden Schächten, (die tiefsten Schächte am Oberharze sind der Samsoner bei Andreasberg mit 410 Lchtr. und der Herzog Georg Wilhelmer Schacht im Burgstädter Reviere mit 315 Lchtr. Teufe) erforderte das Ein- und Ausfahren auf der Fahrt bedeutende körperliche Anstrengung und grossen Zeitaufwand; nur junge, kraftvolle Arbeiter konnten für die Tiefbaue bestimmt werden, aber schon nach einigen Jahren muste man sie, mit Brustbeschwerden behaftet, wieder umwechseln. Diese Uebelstände sind durch die von dem jetzigen Bergmeister Dörell zu Zellerfeld im Jahre 1833 erfundenen Fahrmaschinen (Fahrkünste) beseitigt, welche im Wesentlichen folgende Einrichtung haben: In etwa 20\" Entfernung von einander gehen im Fahrschachte zwei aus einzelnen Stangen zusammengefügte Holzgestänge, in die wohl noch markartig ein Drahtseil eingelegt wird, von oben bis unten hin. An jedem derselben ist abwechselnd ein Tritt und darüber ein Griff in solcher Entfernung befestigt, dass der auf dem Tritt stehende Mann mit der Hand den Griff bequem erreichen kann. […] Tritt nun der Bergmann z. B. mit dem linken Fusse auf den Tritt des links gelegenen Gestänges und hält sich mit der linken Hand an dem Griffe fest, so wird er beim Aufwärtsgehen des Gestänges, während das andere unbelastete niedergeht, etwa um 60 Zoll gehoben; dann bleiben die Gestänge einen Augenblick stehen, während dessen der Mann den rechten Fuss auf den Tritt des rechten Gestänges gesetzt und gleichzeitig den darüber befindlichen Griff erfasst hat, worauf er wieder mit dem Gestänge gehoben wird. Durch dies abwechselnde Hin- und Hertreten auf den auf- und niedergehenden Gestängen, zwischen welchen eine Fahrt zum etwaigen Abtreten befestigt ist, wird die Mannschaft zu Tage gefördert.",
         en="Die Mannschaft fährt auf mehr oder weniger geneigten, gut befestigten Leitern (Fahrten) ein und aus, die auf den Bühnen stehen. Bühnen nennt man die Böden aus Holzbohlen, die in gewissen Abständen übereinander im Fahrschacht angebracht und mit einer Öffnung, dem Fahrloch, versehen sind, aus dem die auf der darunterliegenden Bühne stehende Leiter herausragt. Bei den immer tiefer werdenden Schächten (die tiefsten Schächte im Oberharz sind der Samsoner bei Andreasberg mit 410 Lachter und der Herzog-Georg-Wilhelm-Schacht im Burgstätter Revier mit 315 Lachter Tiefe) erforderte das Ein- und Ausfahren auf der Leiter große körperliche Anstrengung und viel Zeit; nur junge, kräftige Arbeiter konnten für die Tiefbaue eingeteilt werden, aber schon nach einigen Jahren musste man sie, mit Brustbeschwerden behaftet, wieder auswechseln. Diese Übelstände sind durch die Fahrmaschinen (Fahrkünste) beseitigt, die der jetzige Bergmeister Dörell in Zellerfeld im Jahr 1833 erfunden hat und die im Wesentlichen so eingerichtet sind: In etwa 20 Zoll Abstand voneinander laufen im Fahrschacht zwei aus einzelnen Stangen zusammengesetzte Holzgestänge, in deren Kern wohl noch ein Drahtseil eingelegt wird, von oben bis unten. An jedem ist abwechselnd ein Tritt und darüber ein Griff so befestigt, dass der Mann auf dem Tritt den Griff bequem mit der Hand erreichen kann. […] Tritt nun der Bergmann zum Beispiel mit dem linken Fuß auf den Tritt des linken Gestänges und hält sich mit der linken Hand am Griff fest, so wird er, wenn das Gestänge hochgeht und das andere, unbelastete hinabgeht, etwa 60 Zoll gehoben; dann stehen die Gestänge einen Augenblick still, in dem der Mann den rechten Fuß auf den Tritt des rechten Gestänges setzt und zugleich den Griff darüber fasst, worauf er wieder mit diesem Gestänge gehoben wird. Durch dieses abwechselnde Hin- und Hertreten auf den auf- und abgehenden Gestängen, zwischen denen eine Leiter zum etwaigen Absteigen befestigt ist, wird die Mannschaft zutage gefördert.",
         note="Bruno Kerl (1824–1905) schreibt 1852 einen ‚Wegweiser‘ für Besucher. Darin der Satz, der Heines Leiterfahrt von 1824 (Modul 9) ins Medizinische übersetzt: Die Leitern waren so anstrengend, dass man die jungen Bergleute ‚schon nach einigen Jahren […] mit Brustbeschwerden behaftet‘ austauschen musste. Die Fahrkunst, 1833 vom Zellerfelder Bergmeister Dörell erfunden, hebt die Menschen mit derselben Technik, mit der seit 1565 das Wasser gehoben wurde: Gestänge, Kunstkreuz, Kunstrad, Wasser aus den Teichen. Ausgelassen [‚…‘] ist ein Satz über den Antrieb."),
    dict(n=2, titel="Das Drahtseil, 1834, und ‚fahr Niemand do har‘", pg="Kerl 1852, S. 15, 96–97", lang="nhd",
         orig="An der Welle eines gewöhnlich über Tage in der Radstube befindlichen doppelt geschaufelten Wasserrades (Kehrrad) von 24–36 Fuss Durchmesser ist eine Trommel (Korb) befestigt, um welche ein geflochtenes Drahtseil *) so geschlungen ist, dass sich dasselbe beim Umgange der Trommel an dem einen Ende auf, am andern abwickelt.\n\n*) Die Erfindung der Drahtseile rührt von dem verstorbenen Oberbergrath Albert zu Clausthal her. […]\n\n[…] Von Zeit zu Zeit schnurrt im Treibschachte die mit Erz beladene Tonne am Seile empor. Seltener als früher reissen die jetzigen geflochtenen Drahtseile. Bis 1750 waren am Oberharze eiserne Ketten allgemein in Anwendung, seitdem hanfene Treibseile und seit 1772 auch aus Draht von verschiedner Dicke gelenkweise zusammengeschweisste Ketten, welche seit 1834 den geflochtenen Drahtseilen gewichen sind. […]\n\nDa stehen auf hohem Gebrücke ein paar Kammeraden, bemüht, im Schweisse des Angesichts unter taktmässigen Fäustelschlägen Löcher ins harte Gestein zu bohren; dort besetzen Andere die Löcher mit Pulver und schlagen bedächtig, damit sie am Gestein nicht Feuer reisse, die Nadel heraus, während aus der Ferne der warnende Ruf: fahr Niemand do har (fahre Niemand daher) ertönt und bald darauf ein donnerndes Krachen erfolgt, dass das Felsgestein erbebt. Wir eilen nach dem Orte, wo der Schuss geschehen, und finden, obgleich sich der Pulverdampf noch nicht verzogen hat, den Bergmann schon damit beschäftigt, das losgeschossene Gestein wegzuräumen […].",
         en="An der Welle eines doppelt beschaufelten Wasserrads (Kehrrad) von 24 bis 36 Fuß Durchmesser, das gewöhnlich über Tage in der Radstube steht, ist eine Trommel (Korb) befestigt, um die ein geflochtenes Drahtseil *) so geschlungen ist, dass es sich beim Drehen der Trommel an einem Ende auf-, am anderen abwickelt.\n\n*) Die Erfindung der Drahtseile stammt von dem verstorbenen Oberbergrat Albert in Clausthal. […]\n\n[…] Von Zeit zu Zeit schnurrt im Treibschacht die mit Erz beladene Tonne am Seil empor. Seltener als früher reißen die heutigen geflochtenen Drahtseile. Bis 1750 benutzte man im Oberharz allgemein eiserne Ketten, danach Hanfseile und seit 1772 auch Ketten aus Draht verschiedener Dicke, gliedweise zusammengeschweißt, die seit 1834 den geflochtenen Drahtseilen gewichen sind. […]\n\nDa stehen auf einer hohen Bühne ein paar Kameraden und bohren im Schweiße ihres Angesichts mit taktmäßigen Fäustelschlägen Löcher ins harte Gestein; dort besetzen andere die Löcher mit Pulver und ziehen bedächtig, damit sie am Gestein keinen Funken schlagen, die Nadel heraus, während aus der Ferne der warnende Ruf ertönt: ‚fahr Niemand do har‘ (fahre niemand hierher), und bald darauf ein donnerndes Krachen folgt, dass der Fels erbebt. Wir eilen zu der Stelle, wo geschossen wurde, und finden, obwohl sich der Pulverdampf noch nicht verzogen hat, den Bergmann schon dabei, das losgeschossene Gestein wegzuräumen […].",
         note="Das Drahtseil, 1834 in Clausthal vom Oberbergrat Albert eingeführt, ersetzte die Ketten und Hanfseile, die ‚früher‘ öfter rissen. Was ein gerissenes Seil im Treibschacht bedeutete, sagt Kerl nicht; Heines Steiger warnte 1824 vor genau diesem Schacht (Modul 9, Fahrt [2]). Dann die Sprengarbeit: Der Warnruf in Oberharzer Mundart, ‚fahr Niemand do har‘, und der Bergmann, der in den Pulverdampf zurückgeht, bevor er sich verzogen hat. Der Besucher sieht ‚reges, thätiges Leben‘; für den Bergmann ist es Arbeit im Rauch. Ausgelassen [‚…‘] sind die Quellenangaben zum Drahtseil und die Bauweise des Seils."),
    dict(n=3, titel="Vom Pochknaben zum Bergmann, und die Knappschaftskasse", pg="Kerl 1852, S. 26, 37", lang="nhd",
         orig="Die Knappschafts- und Bergbau-Casse stehen gleichfalls unter der Verwaltung des Berg- und Forstamtes. Aus ersterer werden hülfsbedürftige Bergarbeiter unterstützt; letztere soll dazu dienen, allgemeine bergmännische Unternehmungen zu fördern, woraus ihr bei günstigem Erfolg derselben wieder Vortheil erwachsen kann. […]\n\nAls Knabe von 10–14 Jahren beginnt der Oberharzer Bergarbeiter in einem Pochwerke seine bergmännische Laufbahn mit einem wöchentlichen Lohne von 8 Ggr., welcher mit der Zeit bis auf 1 Thlr. 4 Ggr. steigt. Die stärkeren und älteren Arbeiter vom Aufbereitungspersonal werden mit einem höheren Lohne auf den Halden zum Fördern der Erze von den Gruben nach den Pochwerken, zum Teich- und Grabenbau etc. verwandt, bis sie mit ihrem 26. bis 28. Jahre auf den Gruben angenommen werden können.",
         en="Die Knappschaftskasse und die Bergbaukasse stehen ebenfalls unter der Verwaltung des Berg- und Forstamts. Aus der ersten werden hilfsbedürftige Bergarbeiter unterstützt; die zweite soll allgemeine bergmännische Unternehmungen fördern, aus denen ihr bei günstigem Ausgang wieder Vorteil erwachsen kann. […]\n\nAls Knabe von 10 bis 14 Jahren beginnt der Oberharzer Bergarbeiter seine bergmännische Laufbahn in einem Pochwerk mit einem Wochenlohn von 8 Gutegroschen, der mit der Zeit bis auf 1 Taler 4 Gutegroschen steigt. Die stärkeren und älteren Arbeiter der Aufbereitung werden mit höherem Lohn auf den Halden beim Fördern der Erze von den Gruben zu den Pochwerken, beim Teich- und Grabenbau usw. eingesetzt, bis sie mit 26 bis 28 Jahren auf den Gruben angenommen werden können.",
         note="Der ganze Lebenslauf eines Oberharzer Bergmanns in zwei Sätzen. Mit zehn Jahren ins Pochwerk, für 8 Gutegroschen in der Woche, in die Pochwerke, die ‚des Nachts‘ liefen (Räder [3]); Lentin hatte 1789 die Krämpfe der Pochknaben beschrieben (Modul 8). Danach Erzförderung und, ausdrücklich, ‚Teich- und Grabenbau‘: Die Teiche und Gräben dieses Apparats bauten junge Männer zwischen Pochwerk und Grube. Erst mit 26 bis 28 Jahren unter Tage, wo sie die Leitern ‚nach einigen Jahren mit Brustbeschwerden‘ verließen (Fahrkunst [1]). Die Knappschaftskasse unterstützte ‚hülfsbedürftige‘ Bergarbeiter; mit 1 Taler 4 Groschen in der Woche war wenig zurückzulegen."),
]

doc = {
    "id": "system",
    "titel": "Das System um 1866",
    "autor": "Alfred Dumreicher (1868), Bruno Kerl (1852)",
    "jahr": "1833–1868",
    "sprache": "de",
    "orig_sprache": "nhd",
    "pg_label": "",
    "quelle": "A. Dumreicher, Gesammtüberblick über die Wasserwirthschaft des nordwestlichen Oberharzes (Clausthal: Verlag der Grosse'schen Buchhandlung 1868), S. 1–2, 10, 12–15, 23–24, 29–31, 33–37, 39, 41, 44 (Bayerische Staatsbibliothek, A.hydr. 1513 a, digitale-sammlungen.de bsb10060258); B. Kerl, Der Oberharz. Ein Wegweiser beim Besuche der Oberharzer Gruben, Pochwerke, Silberhütten und sonstigen damit in Verbindung stehenden Anstalten (Clausthal: Schweiger 1852), S. 15, 18–19, 26, 37, 96–97 (Bayerische Staatsbibliothek, Metall. 68 lc, bsb10293058).",
    "hinweis": "Dumreicher nach dem Fraktur-Druck, Kerl nach dem Antiqua-Druck, beide am Seitenbild gelesen und in ihrer Schreibung wiedergegeben; die Texterkennung der Bayerischen Staatsbibliothek diente nur zum Auffinden. Die Pferdekraft-Tabelle in Räder [2] ist vereinfacht in eckigen Klammern wiedergegeben. Dumreichers Karten (Grundriss und Profil) sind im benutzten Exemplar nicht digitalisiert. Auslassungen stehen in eckigen Klammern.",
    "sections": [
        {"id": "anlage", "autor": "Alfred Dumreicher, 1868", "titel": "Teiche, Gräben, ein System", "zk": "Anlage",
         "plates": ["dumreicher_titel", "dumreicher_s2"],
         "viz": "system",
         "blurb": "Zwei Jahre nach dem Übergang an Preußen beschreibt ein Clausthaler Maschinenmeister zum ersten Mal das ganze System: 67 Teiche, 27½ Meilen Gräben, 196 Motoren, und alles bewegt nur ‚das eine Agens Wasser‘. Es hält 14 Wochen ohne Regen aus; 1857 war selbst der letzte Teich leer. Und es wurde nie geplant, sondern ist gewachsen, ‚jemehr das Bedürfniß es verlangte‘.",
         "units": ANLAGE},
        {"id": "tiefe", "autor": "Alfred Dumreicher, 1868", "titel": "Stollen und Wasserstrecken", "zk": "Tiefe",
         "plates": [],
         "blurb": "‚In der Höhenlage […] der Stollen spricht sich die Geschichte des Bergbaues aus.‘ Unter Clausthal fahren Kähne mit Erz durch eine geflutete Strecke. Der Tiefe Georg-Stollen ist 1799 fertig geworden, der Ernst-August-Stollen 1864, und einen tieferen werde es ‚nimmermehr‘ geben.",
         "units": TIEFE},
        {"id": "raeder", "autor": "Alfred Dumreicher, 1868", "titel": "193 Wasserräder", "zk": "Räder",
         "plates": ["dumreicher_s39"],
         "blurb": "193 Wasserräder aus Fichtenholz und drei Wassersäulenmaschinen, zusammen 2869 Pferdestärken, Rad für Rad nachgerechnet. Die Pochwerke pochen nachts und waschen tags. Und nach 1864 werden die ersten Kunsträder ‚abgeworfen‘.",
         "units": RAEDER},
        {"id": "fahrkunst", "autor": "Bruno Kerl, 1852", "titel": "Fahrkunst, Drahtseil, Pochknaben", "zk": "Fahrkunst",
         "plates": ["kerl_titel", "kerl_s18"],
         "blurb": "Zwei Clausthaler Erfindungen: die Fahrkunst von 1833, die die Bergleute statt der Leitern aus dem Schacht hebt, weil man die jungen Männer ‚schon nach einigen Jahren […] mit Brustbeschwerden‘ austauschen musste, und das Drahtseil von 1834. Dazu ein Lebenslauf: mit zehn ins Pochwerk, mit 26 unter Tage.",
         "units": FAHRKUNST},
    ],
}

OUT.write_text(json.dumps(doc, ensure_ascii=False, indent=1), encoding="utf-8")
print("system.json:", sum(len(s["units"]) for s in doc["sections"]), "Einheiten")
